import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { DatePipe, DecimalPipe } from '@angular/common';
import { ClassService, AppClass } from '../../services/class.service';
import { AppUser } from '../../services/user.service';
import { AssignmentService, Assignment, AssignmentSubmission, ClassSubmissionStat, ClassSubmissionSummary } from '../../services/assignment.service';
import { ToastService } from '../../services/toast.service';
import { AuthService } from '../../services/auth.service';
import { InfiniteScrollDirective } from '../../shared/infinite-scroll.directive';
import { ClassPost, ClassPostService } from '../../services/class-post.service';
import { DialogService } from '../../services/dialog.service';

export function assignmentFormError(form: Assignment): string | null {
  if (!form.title.trim()) return 'Nhập tiêu đề bài tập.';
  if (!form.due_at) return 'Chọn hạn nộp bài tập.';
  const maxScore = Number(form.max_score ?? 0);
  if (!Number.isFinite(maxScore) || maxScore <= 0) return 'Điểm tối đa phải lớn hơn 0.';
  if (form.late_until && new Date(form.late_until).getTime() <= new Date(form.due_at).getTime()) {
    return 'Thời điểm nộp muộn phải sau hạn nộp.';
  }
  return null;
}

@Component({ selector: 'app-class-detail', imports: [FormsModule, RouterLink, DatePipe, DecimalPipe, InfiniteScrollDirective], templateUrl: './class-detail.html' })
export class ClassDetail implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute); private classes = inject(ClassService); private assignmentsApi = inject(AssignmentService); private postsApi = inject(ClassPostService); private toast = inject(ToastService); private auth = inject(AuthService); private dialog = inject(DialogService);
  classId = 0; classroom = signal<AppClass | null>(null); assignments = signal<Assignment[]>([]); classStudents = signal<AppUser[]>([]); studentTotal = signal(0); studentPage = 1; studentsLoading = signal(false); matchedStudents = signal<AppUser[]>([]); stats = signal<ClassSubmissionStat[]>([]); statsTotal = signal(0); statsSummary = signal<ClassSubmissionSummary | null>(null); statsPage = 1; statsLoading = signal(false); studentSearch = ''; total = signal(0); page = 1; loading = signal(false); error = signal(''); tab = signal<'stream'|'assignments'|'people'|'grades'>('stream');
  showForm = signal(false); editing = signal<number | null>(null); uploadProgress = signal<number | null>(null); selectedAssignment = signal<Assignment | null>(null); submissions = signal<AssignmentSubmission[]>([]); submissionsTotal = signal(0); submissionsPage = 1; submissionsLoading = signal(false); posts = signal<ClassPost[]>([]); postsTotal = signal(0); postsPage = 1; postsLoading = signal(false); postsInitialized = false; showPostForm = signal(false); editingPost = signal<number | null>(null); postContent = '';
  form: Assignment = this.empty();
  private studentSearchTimer?: ReturnType<typeof setTimeout>;
  get isStudent() { return this.auth.getRole() === 'Student'; }
  ngOnInit() { this.classId = Number(this.route.snapshot.paramMap.get('id')); this.classes.getOne(this.classId).subscribe({ next: item => this.classroom.set(item), error: () => this.error.set('Bạn không có quyền truy cập lớp học này.') }); this.load(); if (!this.isStudent) this.loadStudents(); }
  ngOnDestroy() { if (this.studentSearchTimer) clearTimeout(this.studentSearchTimer); }
  ngDoCheck() { if (this.classId > 0 && !this.postsInitialized) { this.postsInitialized = true; this.loadPosts(); } }
  loadPosts(reset = true) { if (this.postsLoading()) return; const page = reset ? 1 : this.postsPage + 1; this.postsLoading.set(true); this.postsApi.list(this.classId, page).subscribe({ next: result => { this.posts.set(reset ? (result.items ?? []) : [...this.posts(), ...(result.items ?? [])]); this.postsTotal.set(result.total ?? 0); this.postsPage = page; this.postsLoading.set(false); }, error: () => { this.postsLoading.set(false); this.error.set('Khong tai duoc bang tin lop hoc.'); } }); }
  hasMorePosts() { return this.posts().length < this.postsTotal(); }
  createPost() { const content = this.postContent.trim(); if (!content) { this.error.set('Noi dung thong bao khong duoc de trong.'); return; } this.postsApi.create(this.classId, content).subscribe({ next: item => { this.posts.update(posts => [item, ...posts]); this.postsTotal.update(total => total + 1); this.postContent = ''; this.showPostForm.set(false); this.toast.success('Da dang thong bao len bang tin.'); }, error: error => this.error.set(error?.error?.error ?? 'Khong the dang thong bao.') }); }
  openEditPost(post: ClassPost) { if (!post.id) return; this.editingPost.set(post.id); this.postContent = post.content; this.showPostForm.set(true); }
  savePost() { const id = this.editingPost(); if (!id) { this.createPost(); return; } const content = this.postContent.trim(); if (!content) { this.error.set('Noi dung thong bao khong duoc de trong.'); return; } this.postsApi.update(id, content).subscribe({ next: item => { this.posts.update(posts => posts.map(post => post.id === item.id ? { ...post, ...item, author_name: item.author_name || post.author_name } : post)); this.postContent = ''; this.editingPost.set(null); this.showPostForm.set(false); this.toast.success('Da cap nhat thong bao.'); }, error: error => this.error.set(error?.error?.error ?? 'Khong the cap nhat thong bao.') }); }
  removePost(post: ClassPost) { if (!post.id) return; this.dialog.confirm('Xóa thông báo', 'Xóa thông báo này khỏi bảng tin lớp học?').then(confirmed => { if (!confirmed) return; this.postsApi.remove(post.id!).subscribe({ next: () => { this.posts.update(posts => posts.filter(item => item.id !== post.id)); this.postsTotal.update(total => Math.max(0, total - 1)); this.toast.success('Đã xóa thông báo.'); }, error: error => this.error.set(error?.error?.error ?? 'Không thể xóa thông báo.') }); }); }
  empty(): Assignment { return {class_id: this.classId, title:'', description:'', due_at:'', late_until:null, max_score:10, status:'published'}; }
  load(reset = true) { if (reset) { this.page = 1; this.assignments.set([]); } this.loading.set(true); this.assignmentsApi.list(this.classId, this.page).subscribe({next: result => { this.assignments.update(items => reset ? result.items : [...items, ...result.items]); this.total.set(result.total); this.loading.set(false); }, error: () => { this.error.set('Không tải được bài tập.'); this.loading.set(false); }}); }
  hasMore() { return this.assignments().length < this.total(); } loadMore() { if (!this.loading() && this.hasMore()) { this.page++; this.load(false); } }
  openCreate() { this.editing.set(null); this.form = this.empty(); this.showForm.set(true); }
  async copyClassCode() { const code = this.classroom()?.code; if (!code) return; try { await navigator.clipboard.writeText(code); this.toast.success('Đã sao chép mã lớp.'); } catch { const message = 'Không thể sao chép mã lớp. Hãy sao chép thủ công.'; this.error.set(message); this.toast.error(message); } }
  edit(item: Assignment) { this.editing.set(item.id!); this.form = {...item, due_at: this.toInput(item.due_at), late_until: item.late_until ? this.toInput(item.late_until) : null}; this.showForm.set(true); }
  save() { const validationError = assignmentFormError(this.form); if (validationError) { this.error.set(validationError); this.toast.error(validationError); return; } const request = this.editing() ? this.assignmentsApi.update(this.editing()!, this.form) : this.assignmentsApi.create(this.classId, this.form); request.subscribe({next: () => { this.showForm.set(false); this.toast.success('Đã lưu bài tập.'); this.load(); }, error: (e) => { const message = e?.error?.error ?? 'Không lưu được bài tập.'; this.error.set(message); this.toast.error(message); }}); }
  remove(item: Assignment) { if (!item.id) return; this.dialog.confirm('Xóa bài tập', `Xóa bài tập “${item.title}”? Bài nộp liên quan cũng sẽ không còn truy cập được.`).then(confirmed => { if (!confirmed) return; this.assignmentsApi.remove(item.id!).subscribe({ next: () => { this.load(); this.toast.success('Đã xóa bài tập.'); }, error: error => this.error.set(error?.error?.error ?? 'Không thể xóa bài tập.') }); }); }
  openSubmissions(item: Assignment) { this.selectedAssignment.set(item); this.loadSubmissions(true); }
  loadSubmissions(reset = true) { const assignment = this.selectedAssignment(); if (!assignment || this.submissionsLoading()) return; const page = reset ? 1 : this.submissionsPage + 1; this.submissionsLoading.set(true); this.assignmentsApi.submissionsPaged(assignment.id!, page).subscribe({next: result => { this.submissions.set(reset ? (result.items ?? []) : [...this.submissions(), ...(result.items ?? [])]); this.submissionsTotal.set(result.total ?? 0); this.submissionsPage = page; this.submissionsLoading.set(false); }, error: error => { this.error.set(error?.error?.error ?? 'Không tải được bài nộp.'); this.submissionsLoading.set(false); }}); }
  hasMoreSubmissions() { return this.submissions().length < this.submissionsTotal(); }
  grade(submission: AssignmentSubmission, score: string, feedback: string) { const numericScore = Number(score); const maximum = this.selectedAssignment()?.max_score ?? 10; if (!Number.isFinite(numericScore) || numericScore < 0 || numericScore > maximum) { const message = `Điểm phải nằm trong khoảng từ 0 đến ${maximum}.`; this.error.set(message); this.toast.error(message); return; } this.assignmentsApi.grade(submission.id!, numericScore, feedback).subscribe({next: () => { this.toast.success('Đã lưu điểm và nhận xét.'); this.loadSubmissions(true); }, error: e => { const message = e?.error?.error ?? 'Không chấm được bài.'; this.error.set(message); this.toast.error(message); }}); }
  download(submission: AssignmentSubmission) { this.assignmentsApi.download(submission.id!).subscribe({ next: blob => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = submission.original_name; link.click(); URL.revokeObjectURL(url); }, error: error => { const message = error?.error?.error ?? 'Không tải được tệp bài nộp.'; this.error.set(message); this.toast.error(message); } }); }
  loadStudents(reset = true) { if (this.studentsLoading()) return; const page = reset ? 1 : this.studentPage + 1; this.studentsLoading.set(true); this.classes.getStudentsPaged(this.classId, page).subscribe({next: result => { this.classStudents.set(reset ? (result.items ?? []) : [...this.classStudents(), ...(result.items ?? [])]); this.studentTotal.set(result.total ?? 0); this.studentPage = page; this.studentsLoading.set(false); }, error: () => { this.error.set('Không tải được danh sách sinh viên.'); this.studentsLoading.set(false); }}); }
  hasMoreStudents() { return this.classStudents().length < this.studentTotal(); }
  searchStudents() { const keyword = this.studentSearch.trim(); if (this.studentSearchTimer) clearTimeout(this.studentSearchTimer); if (keyword.length < 2) { this.matchedStudents.set([]); return; } this.studentSearchTimer = setTimeout(() => { if (keyword !== this.studentSearch.trim()) return; this.classes.searchStudents(keyword).subscribe({next: students => this.matchedStudents.set(students ?? []), error: () => this.matchedStudents.set([])}); }, 250); }
  studentSuggestions() { const presentIds = new Set(this.classStudents().map(student => student.id)); return this.matchedStudents().filter(student => !presentIds.has(student.id)); }
  addStudent(student: AppUser) { if (!student.id) return; this.classes.addStudent(this.classId, student.id).subscribe({next: () => { this.studentSearch = ''; this.matchedStudents.set([]); this.loadStudents(true); this.toast.success(`Đã thêm ${student.full_name || student.username} vào lớp.`); }, error: error => this.error.set(error?.error?.error ?? 'Không thể thêm sinh viên.')}); }
  removeStudent(student: AppUser) { if (!student.id) return; this.dialog.confirm('Xóa khỏi lớp', `Xóa ${student.full_name || student.username} khỏi lớp học này?`).then(confirmed => { if (!confirmed) return; this.classes.removeStudent(this.classId, student.id!).subscribe({next: () => { this.loadStudents(true); this.toast.success(`Đã xóa ${student.full_name || student.username} khỏi lớp.`); }, error: error => this.error.set(error?.error?.error ?? 'Không thể xóa sinh viên.')}); }); }
  loadStats(reset = true) { if (this.statsLoading()) return; const page = reset ? 1 : this.statsPage + 1; if (reset) { this.stats.set([]); this.statsTotal.set(0); this.statsSummary.set(null); } this.statsLoading.set(true); this.assignmentsApi.classStatsPaged(this.classId, page).subscribe({next: result => { this.stats.set(reset ? (result.items ?? []) : [...this.stats(), ...(result.items ?? [])]); this.statsTotal.set(result.total ?? 0); this.statsSummary.set(result.summary ?? null); this.statsPage = page; this.statsLoading.set(false); }, error: () => { this.error.set('Không tải được thống kê lớp.'); this.statsLoading.set(false); }}); }
  hasMoreStats() { return this.stats().length < this.statsTotal(); }
  upload(item: Assignment, event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; input.value = ''; if (!file) return; this.uploadProgress.set(0); this.assignmentsApi.uploadWithRetry(item.id!, file, value => this.uploadProgress.set(value)).then(() => { this.uploadProgress.set(null); this.toast.success('Đã nộp bài.'); this.load(); }).catch(error => { this.uploadProgress.set(null); const message = error?.error?.error ?? 'Kết nối bị gián đoạn. Hãy chọn lại cùng file để tiếp tục nộp; các phần đã gửi sẽ không bị mất.'; this.error.set(message); this.toast.error(message); }); }
  toInput(value: string) { return value ? value.slice(0, 16) : ''; }
}
