# -*- coding: utf-8 -*-
"""Nhóm Toán - Lý: Toán cao cấp, Đại số tuyến tính, Giải tích, Xác suất thống kê, Vật lý đại cương."""

TOAN_CAO_CAP = [
    ("Đạo hàm của hàm số y = x^3 là gì?", "3x^2", "x^2", "3x", "x^4/4", "A", "easy"),
    ("Đạo hàm của hàm số y = sin(x) là gì?", "cos(x)", "-cos(x)", "sin(x)", "-sin(x)", "A", "easy"),
    ("Đạo hàm của hàm số y = e^x là gì?", "x·e^(x-1)", "e^x", "e^x/x", "ln(x)", "B", "easy"),
    ("Đạo hàm của hàm số y = ln(x) là gì?", "1/x", "ln(x)/x", "x", "e^x", "A", "easy"),
    ("Nguyên hàm của f(x) = 2x là gì?", "x^2 + C", "2 + C", "x^2/2 + C", "2x^2 + C", "A", "easy"),
    ("Tích phân của f(x) = 1/x trên miền x > 0 là gì?", "ln|x| + C", "1/x^2 + C", "-1/x^2 + C", "x + C", "A", "easy"),
    ("Giới hạn của (sin x)/x khi x tiến tới 0 bằng bao nhiêu?", "0", "1", "Vô cùng", "Không tồn tại", "B", "medium"),
    ("Giới hạn của (1 + 1/n)^n khi n tiến tới vô cùng bằng bao nhiêu?", "1", "e", "0", "Vô cùng", "B", "medium"),
    ("Hàm số liên tục tại điểm x0 khi nào?", "Giới hạn tại x0 tồn tại và bằng giá trị hàm số tại x0", "Hàm số có đạo hàm tại x0", "Hàm số xác định tại x0", "Hàm số đơn điệu quanh x0", "A", "medium"),
    ("Nếu hàm số có đạo hàm tại một điểm thì tại đó hàm số có tính chất gì?", "Liên tục", "Đơn điệu tăng", "Đạt cực trị", "Có tiệm cận", "A", "medium"),
    ("Điều kiện cần để hàm số đạt cực trị tại điểm trong là gì?", "Đạo hàm bằng 0 hoặc không tồn tại", "Đạo hàm cấp hai dương", "Hàm số liên tục", "Hàm số bị chặn", "A", "medium"),
    ("Nếu f'(x0) = 0 và f''(x0) > 0 thì tại x0 hàm số đạt gì?", "Cực tiểu", "Cực đại", "Điểm uốn", "Không có kết luận", "A", "medium"),
    ("Đạo hàm của tích u·v được tính theo công thức nào?", "u'v + uv'", "u'v'", "u'v - uv'", "(u'v)/v^2", "A", "easy"),
    ("Đạo hàm của thương u/v được tính theo công thức nào?", "(u'v - uv')/v^2", "(u'v + uv')/v^2", "u'/v'", "(uv' - u'v)/v^2", "A", "medium"),
    ("Quy tắc L'Hospital dùng để tính giới hạn dạng nào?", "Dạng vô định 0/0 hoặc vô cùng trên vô cùng", "Mọi loại giới hạn", "Chỉ giới hạn tại vô cực", "Chỉ giới hạn một phía", "A", "medium"),
    ("Khai triển Taylor của hàm số dùng để làm gì?", "Xấp xỉ hàm số bằng đa thức quanh một điểm", "Tìm nghiệm phương trình", "Tính diện tích hình phẳng", "Giải hệ phương trình", "A", "medium"),
    ("Vi phân của hàm số y = f(x) được ký hiệu và tính như thế nào?", "dy = f'(x)dx", "dy = f(x)dx", "dy = f''(x)dx", "dy = dx/f'(x)", "A", "medium"),
    ("Tích phân xác định từ a đến b của f(x) biểu diễn ý nghĩa hình học gì?", "Diện tích hình thang cong giới hạn bởi đồ thị và trục hoành", "Độ dài đường cong", "Thể tích khối tròn xoay", "Hệ số góc tiếp tuyến", "A", "medium"),
    ("Công thức Newton - Leibniz phát biểu điều gì?", "Tích phân xác định bằng hiệu nguyên hàm tại hai cận", "Đạo hàm của tích phân bằng hàm dưới dấu tích phân", "Tổng Riemann hội tụ", "Tích phân từng phần", "A", "medium"),
    ("Phương pháp tích phân từng phần dựa trên công thức nào?", "∫udv = uv - ∫vdu", "∫udv = uv + ∫vdu", "∫uv = ∫u·∫v", "∫u/v = ∫u/∫v", "A", "medium"),
    ("Hàm số y = x^2 có tính chất gì trên toàn trục số?", "Là hàm chẵn", "Là hàm lẻ", "Không chẵn không lẻ", "Vừa chẵn vừa lẻ", "A", "easy"),
    ("Hàm số y = x^3 có tính chất gì?", "Là hàm chẵn", "Là hàm lẻ", "Tuần hoàn", "Bị chặn", "B", "easy"),
    ("Chuỗi số hội tụ khi nào?", "Khi dãy tổng riêng có giới hạn hữu hạn", "Khi số hạng tổng quát tiến tới 0", "Khi có vô hạn số hạng", "Khi các số hạng đều dương", "A", "hard"),
    ("Chuỗi điều hòa 1 + 1/2 + 1/3 + ... có tính chất gì?", "Phân kỳ", "Hội tụ về 1", "Hội tụ về e", "Hội tụ về 2", "A", "hard"),
    ("Điều kiện cần để chuỗi hội tụ là gì?", "Số hạng tổng quát tiến tới 0", "Các số hạng dương", "Dãy số tăng", "Có hữu hạn số hạng", "A", "medium"),
    ("Đạo hàm riêng của hàm nhiều biến f(x,y) theo x nghĩa là gì?", "Đạo hàm theo x, coi y là hằng số", "Đạo hàm theo cả hai biến", "Tổng các đạo hàm", "Tích các đạo hàm", "A", "medium"),
    ("Gradient của hàm số nhiều biến là gì?", "Vector gồm các đạo hàm riêng", "Đạo hàm cấp hai", "Một số thực", "Ma trận vuông", "A", "medium"),
    ("Phương trình vi phân cấp một có dạng tổng quát nào?", "F(x, y, y') = 0", "F(x, y) = 0", "F(x, y, y'') = 0", "y = f(x)", "A", "medium"),
    ("Nghiệm tổng quát của phương trình vi phân y' = y là gì?", "y = Ce^x", "y = Cx", "y = C + x", "y = C/x", "A", "medium"),
    ("Phương trình vi phân tách biến có dạng nào?", "y' = f(x)·g(y)", "y' + p(x)y = q(x)", "y'' + ay' + by = 0", "y' = y^2 + x^2", "A", "medium"),
    ("Số phức z = a + bi có phần thực và phần ảo lần lượt là gì?", "a và b", "b và a", "a và bi", "i và a", "A", "easy"),
    ("Môđun của số phức z = 3 + 4i bằng bao nhiêu?", "5", "7", "12", "25", "A", "medium"),
    ("Số phức liên hợp của z = a + bi là gì?", "a - bi", "-a + bi", "-a - bi", "b + ai", "A", "easy"),
    ("Đơn vị ảo i có tính chất nào?", "i^2 = -1", "i^2 = 1", "i^2 = 0", "i^2 = i", "A", "easy"),
    ("Cấp số cộng có công thức số hạng tổng quát nào?", "un = u1 + (n-1)d", "un = u1·q^(n-1)", "un = u1 + nd", "un = n·d", "A", "easy"),
    ("Cấp số nhân có công thức số hạng tổng quát nào?", "un = u1·q^(n-1)", "un = u1 + (n-1)q", "un = u1·q^n", "un = q^n", "A", "easy"),
    ("Tổng n số hạng đầu của cấp số cộng được tính bằng công thức nào?", "Sn = n(u1 + un)/2", "Sn = n·u1", "Sn = u1·n^2", "Sn = (u1 + un)/n", "A", "medium"),
    ("Ma trận đơn vị có đặc điểm gì?", "Các phần tử trên đường chéo chính bằng 1, còn lại bằng 0", "Mọi phần tử bằng 1", "Mọi phần tử bằng 0", "Các phần tử đường chéo bằng 0", "A", "easy"),
    ("Hàm số logarit cơ số a xác định khi nào?", "Khi a > 0 và a khác 1", "Khi a bất kỳ", "Khi a < 0", "Khi a = 1", "A", "easy"),
    ("Tính chất log(ab) bằng gì?", "log(a) + log(b)", "log(a)·log(b)", "log(a) - log(b)", "log(a)/log(b)", "A", "easy"),
    ("Tính chất log(a/b) bằng gì?", "log(a) - log(b)", "log(a)/log(b)", "log(a) + log(b)", "log(a·b)", "A", "easy"),
    ("Hàm số y = a^x với a > 1 có tính chất gì?", "Đồng biến trên toàn trục số", "Nghịch biến", "Tuần hoàn", "Bị chặn trên", "A", "medium"),
    ("Tập xác định của hàm số y = ln(x) là gì?", "x > 0", "x >= 0", "Mọi số thực", "x khác 0", "A", "easy"),
    ("Đạo hàm cấp hai dùng để xét tính chất nào của đồ thị?", "Tính lồi lõm và điểm uốn", "Tiệm cận đứng", "Tập xác định", "Tính tuần hoàn", "A", "medium"),
    ("Tiệm cận ngang của đồ thị hàm số được xác định bởi giới hạn nào?", "Giới hạn của hàm số khi x tiến tới vô cực", "Giới hạn tại điểm gián đoạn", "Đạo hàm tại vô cực", "Giá trị lớn nhất", "A", "medium"),
    ("Thể tích khối tròn xoay quanh trục Ox được tính bằng công thức nào?", "V = π∫f(x)^2 dx", "V = ∫f(x) dx", "V = 2π∫f(x) dx", "V = π∫f(x) dx", "A", "hard"),
    ("Độ dài cung của đường cong y = f(x) từ a đến b được tính bằng gì?", "∫√(1 + f'(x)^2) dx", "∫f(x) dx", "∫f'(x) dx", "∫√f(x) dx", "A", "hard"),
    ("Tích phân suy rộng là gì?", "Tích phân có cận vô hạn hoặc hàm không bị chặn", "Tích phân của hàm nhiều biến", "Tích phân đường", "Tích phân bội", "A", "hard"),
    ("Định lý Lagrange (giá trị trung bình) phát biểu điều gì?", "Tồn tại điểm c mà f'(c) bằng hệ số góc dây cung", "Hàm số luôn có cực trị", "Tích phân bằng diện tích", "Đạo hàm luôn tồn tại", "A", "hard"),
    ("Hàm số đơn điệu tăng trên khoảng khi nào?", "Khi đạo hàm không âm trên khoảng đó", "Khi đạo hàm bằng 0", "Khi đạo hàm âm", "Khi hàm số bị chặn", "A", "medium"),
    ("Ý nghĩa hình học của đạo hàm tại một điểm là gì?", "Hệ số góc của tiếp tuyến tại điểm đó", "Diện tích dưới đường cong", "Độ dài cung", "Giá trị cực đại", "A", "easy"),
]

DAI_SO_TUYEN_TINH = [
    ("Ma trận là gì?", "Bảng số hình chữ nhật gồm các phần tử sắp xếp theo hàng và cột", "Một hệ phương trình", "Một vector đặc biệt", "Một hàm số nhiều biến", "A", "easy"),
    ("Ma trận vuông là ma trận có đặc điểm gì?", "Số hàng bằng số cột", "Mọi phần tử bằng nhau", "Định thức bằng 0", "Chỉ có một hàng", "A", "easy"),
    ("Ma trận chuyển vị của A ký hiệu A^T được tạo bằng cách nào?", "Đổi hàng thành cột", "Nhân với -1", "Lấy nghịch đảo", "Nhân với ma trận đơn vị", "A", "easy"),
    ("Điều kiện để nhân được hai ma trận A và B là gì?", "Số cột của A bằng số hàng của B", "A và B cùng cỡ", "A và B đều vuông", "Định thức khác 0", "A", "medium"),
    ("Phép nhân ma trận có tính chất nào?", "Kết hợp nhưng không giao hoán", "Giao hoán", "Không kết hợp", "Luôn cho ma trận đơn vị", "A", "medium"),
    ("Định thức chỉ tính được cho loại ma trận nào?", "Ma trận vuông", "Mọi ma trận", "Ma trận có một hàng", "Ma trận không vuông", "A", "easy"),
    ("Định thức ma trận cấp 2 [[a,b],[c,d]] bằng bao nhiêu?", "ad - bc", "ad + bc", "ab - cd", "ac - bd", "A", "easy"),
    ("Nếu đổi chỗ hai hàng của ma trận thì định thức thay đổi thế nào?", "Đổi dấu", "Không đổi", "Bằng 0", "Nhân đôi", "A", "medium"),
    ("Nếu ma trận có hai hàng giống nhau thì định thức bằng bao nhiêu?", "0", "1", "Không xác định", "Bằng tích các phần tử", "A", "medium"),
    ("Ma trận khả nghịch khi nào?", "Khi định thức khác 0", "Khi định thức bằng 0", "Khi là ma trận không", "Khi có nhiều hàng hơn cột", "A", "medium"),
    ("Ma trận nghịch đảo A^(-1) thỏa mãn điều gì?", "A·A^(-1) = I", "A·A^(-1) = 0", "A + A^(-1) = I", "A^(-1) = A^T", "A", "medium"),
    ("Hạng của ma trận là gì?", "Số hàng độc lập tuyến tính tối đa", "Số phần tử khác 0", "Số hàng của ma trận", "Định thức của ma trận", "A", "medium"),
    ("Hệ phương trình tuyến tính có nghiệm duy nhất khi nào (theo Cramer)?", "Khi định thức ma trận hệ số khác 0", "Khi định thức bằng 0", "Khi số ẩn nhiều hơn số phương trình", "Khi hệ thuần nhất", "A", "medium"),
    ("Hệ phương trình thuần nhất luôn có nghiệm nào?", "Nghiệm tầm thường (tất cả bằng 0)", "Vô nghiệm", "Nghiệm duy nhất khác 0", "Vô số nghiệm luôn luôn", "A", "medium"),
    ("Phương pháp Gauss dùng để làm gì?", "Giải hệ phương trình tuyến tính bằng biến đổi sơ cấp", "Tính đạo hàm", "Tìm giá trị riêng", "Tính tích phân", "A", "easy"),
    ("Phép biến đổi sơ cấp trên hàng gồm những thao tác nào?", "Đổi chỗ hai hàng, nhân hàng với số khác 0, cộng bội của hàng này vào hàng khác", "Chỉ đổi chỗ hai hàng", "Chỉ nhân hàng với số", "Xóa một hàng bất kỳ", "A", "medium"),
    ("Không gian vector là gì?", "Tập hợp có phép cộng và nhân vô hướng thỏa mãn các tiên đề nhất định", "Tập hợp các ma trận vuông", "Tập hợp các số thực", "Tập nghiệm của một phương trình", "A", "medium"),
    ("Hệ vector độc lập tuyến tính khi nào?", "Khi tổ hợp tuyến tính bằng vector không chỉ khi mọi hệ số bằng 0", "Khi các vector vuông góc", "Khi có cùng độ dài", "Khi số vector bằng số chiều", "A", "hard"),
    ("Cơ sở của không gian vector là gì?", "Hệ vector độc lập tuyến tính và sinh ra toàn bộ không gian", "Mọi hệ vector trong không gian", "Vector có độ dài bằng 1", "Vector không", "A", "hard"),
    ("Số chiều của không gian vector bằng gì?", "Số vector trong một cơ sở", "Số vector bất kỳ", "Số phần tử của không gian", "Hạng của ma trận đơn vị", "A", "medium"),
    ("Tích vô hướng của hai vector bằng 0 nghĩa là gì?", "Hai vector vuông góc", "Hai vector cùng phương", "Hai vector bằng nhau", "Một vector bằng không", "A", "easy"),
    ("Độ dài (chuẩn) của vector u = (3, 4) bằng bao nhiêu?", "5", "7", "12", "25", "A", "easy"),
    ("Giá trị riêng của ma trận A là số λ thỏa mãn điều gì?", "Ax = λx với x khác vector không", "Ax = 0", "A = λI", "det(A) = λ", "A", "hard"),
    ("Phương trình đặc trưng của ma trận A là gì?", "det(A - λI) = 0", "det(A) = 0", "A - λI = 0", "Ax = 0", "A", "hard"),
    ("Vector riêng ứng với giá trị riêng λ là gì?", "Nghiệm khác không của hệ (A - λI)x = 0", "Vector không", "Cột của ma trận A", "Hàng của ma trận A", "A", "hard"),
    ("Ma trận đối xứng có đặc điểm gì?", "A = A^T", "A = -A^T", "A·A^T = 0", "det(A) = 1", "A", "medium"),
    ("Ma trận tam giác trên có đặc điểm gì?", "Các phần tử dưới đường chéo chính bằng 0", "Các phần tử trên đường chéo bằng 0", "Mọi phần tử bằng 0", "Là ma trận đơn vị", "A", "easy"),
    ("Định thức của ma trận tam giác bằng gì?", "Tích các phần tử trên đường chéo chính", "Tổng các phần tử đường chéo", "0", "1", "A", "medium"),
    ("Vết (trace) của ma trận vuông là gì?", "Tổng các phần tử trên đường chéo chính", "Tích các phần tử đường chéo", "Định thức của ma trận", "Hạng của ma trận", "A", "medium"),
    ("Hai ma trận bằng nhau khi nào?", "Cùng cỡ và các phần tử tương ứng bằng nhau", "Cùng định thức", "Cùng hạng", "Cùng vết", "A", "easy"),
    ("Ánh xạ tuyến tính f thỏa mãn tính chất nào?", "f(u + v) = f(u) + f(v) và f(ku) = kf(u)", "f(uv) = f(u)f(v)", "f(u) = u^2", "f là hàm hằng", "A", "medium"),
    ("Nhân (kernel) của ánh xạ tuyến tính là gì?", "Tập các vector có ảnh bằng vector không", "Tập ảnh của ánh xạ", "Tập xác định", "Tập các vector riêng", "A", "hard"),
    ("Hệ Cramer áp dụng được khi nào?", "Khi số phương trình bằng số ẩn và định thức khác 0", "Khi hệ vô nghiệm", "Khi hệ có vô số nghiệm", "Với mọi hệ phương trình", "A", "medium"),
    ("Định lý Kronecker - Capelli phát biểu hệ có nghiệm khi nào?", "Khi hạng ma trận hệ số bằng hạng ma trận mở rộng", "Khi định thức khác 0", "Khi số ẩn bằng số phương trình", "Khi hệ thuần nhất", "A", "hard"),
    ("Nếu hạng ma trận hệ số nhỏ hơn số ẩn thì hệ có nghiệm thế nào?", "Vô số nghiệm (nếu hệ tương thích)", "Nghiệm duy nhất", "Vô nghiệm chắc chắn", "Chỉ nghiệm tầm thường", "A", "hard"),
    ("Ma trận nghịch đảo của ma trận cấp 2 [[a,b],[c,d]] được tính bằng công thức nào?", "1/(ad-bc) · [[d,-b],[-c,a]]", "[[a,c],[b,d]]", "[[1/a,1/b],[1/c,1/d]]", "[[d,b],[c,a]]", "A", "hard"),
    ("Tính chất det(AB) bằng gì?", "det(A)·det(B)", "det(A) + det(B)", "det(A)/det(B)", "det(A) - det(B)", "A", "medium"),
    ("Tính chất det(A^T) so với det(A) thế nào?", "Bằng nhau", "Đối nhau", "Nghịch đảo nhau", "Bằng 0", "A", "medium"),
    ("Nếu nhân một hàng của ma trận với số k thì định thức thay đổi ra sao?", "Nhân với k", "Không đổi", "Chia cho k", "Cộng thêm k", "A", "medium"),
    ("Ma trận trực giao có tính chất gì?", "A^T·A = I", "A^2 = I", "det(A) = 0", "A = A^T", "A", "hard"),
    ("Cơ sở trực chuẩn là gì?", "Cơ sở gồm các vector đơn vị và đôi một vuông góc", "Cơ sở gồm các vector cùng phương", "Cơ sở có định thức bằng 1", "Cơ sở bất kỳ", "A", "hard"),
    ("Quá trình Gram - Schmidt dùng để làm gì?", "Trực chuẩn hóa một hệ vector độc lập tuyến tính", "Tính định thức", "Giải hệ phương trình", "Tìm hạng ma trận", "A", "hard"),
    ("Dạng toàn phương là gì?", "Đa thức thuần nhất bậc hai của các biến", "Đa thức bậc nhất", "Hàm số mũ", "Ma trận vuông", "A", "hard"),
    ("Không gian con của không gian vector V là gì?", "Tập con khác rỗng đóng với phép cộng và nhân vô hướng", "Mọi tập con của V", "Tập chỉ có vector không", "Tập các vector đơn vị", "A", "medium"),
    ("Tổ hợp tuyến tính của các vector v1, v2 là gì?", "Biểu thức dạng c1v1 + c2v2 với c1, c2 là số vô hướng", "Tích của v1 và v2", "Thương của v1 và v2", "Độ dài của v1 cộng v2", "A", "easy"),
    ("Hai vector cùng phương khi nào?", "Khi vector này là bội vô hướng của vector kia", "Khi tích vô hướng bằng 0", "Khi có cùng độ dài", "Khi vuông góc nhau", "A", "easy"),
    ("Ứng dụng của đại số tuyến tính trong đồ họa máy tính là gì?", "Biểu diễn phép biến hình bằng ma trận", "Tính tích phân", "Giải phương trình vi phân", "Phân tích chuỗi", "A", "medium"),
    ("Ma trận đường chéo có đặc điểm gì?", "Mọi phần tử ngoài đường chéo chính bằng 0", "Mọi phần tử bằng 1", "Là ma trận không vuông", "Định thức luôn bằng 0", "A", "easy"),
    ("Chéo hóa ma trận nghĩa là gì?", "Tìm ma trận P sao cho P^(-1)AP là ma trận đường chéo", "Tính định thức ma trận", "Chuyển vị ma trận", "Tính hạng ma trận", "A", "hard"),
    ("Hệ phương trình tuyến tính vô nghiệm khi nào?", "Khi hạng ma trận hệ số nhỏ hơn hạng ma trận mở rộng", "Khi định thức khác 0", "Khi hệ thuần nhất", "Khi số ẩn ít hơn số phương trình", "A", "hard"),
]

GIAI_TICH = [
    ("Dãy số hội tụ là dãy có tính chất gì?", "Có giới hạn hữu hạn khi n tiến tới vô cùng", "Luôn tăng", "Bị chặn trên", "Có vô hạn số hạng", "A", "easy"),
    ("Dãy số bị chặn và đơn điệu thì có tính chất gì?", "Hội tụ", "Phân kỳ", "Không xác định", "Tuần hoàn", "A", "medium"),
    ("Giới hạn của dãy 1/n khi n tiến tới vô cùng bằng bao nhiêu?", "0", "1", "Vô cùng", "Không tồn tại", "A", "easy"),
    ("Hàm số f(x) liên tục trên đoạn đóng [a,b] thì có tính chất gì?", "Đạt giá trị lớn nhất và nhỏ nhất trên đoạn đó", "Luôn có đạo hàm", "Luôn đơn điệu", "Luôn khả tích trên mọi khoảng", "A", "medium"),
    ("Định lý giá trị trung gian phát biểu điều gì?", "Hàm liên tục nhận mọi giá trị giữa f(a) và f(b)", "Hàm luôn có cực trị", "Đạo hàm luôn tồn tại", "Tích phân luôn hội tụ", "A", "medium"),
    ("Điểm gián đoạn loại một của hàm số là gì?", "Điểm mà giới hạn trái và phải tồn tại hữu hạn nhưng khác nhau hoặc khác giá trị hàm", "Điểm hàm số không xác định", "Điểm có đạo hàm vô cùng", "Điểm cực trị", "A", "hard"),
    ("Đạo hàm của hàm hợp f(g(x)) được tính bằng công thức nào?", "f'(g(x))·g'(x)", "f'(x)·g'(x)", "f'(g'(x))", "f(g'(x))", "A", "medium"),
    ("Đạo hàm của y = cos(x) là gì?", "sin(x)", "-sin(x)", "cos(x)", "-cos(x)", "B", "easy"),
    ("Đạo hàm của y = tan(x) là gì?", "1/cos^2(x)", "1/sin^2(x)", "-1/cos^2(x)", "cot(x)", "A", "medium"),
    ("Nguyên hàm của cos(x) là gì?", "sin(x) + C", "-sin(x) + C", "cos(x) + C", "-cos(x) + C", "A", "easy"),
    ("Nguyên hàm của e^x là gì?", "e^x + C", "x·e^x + C", "e^x/x + C", "ln(x) + C", "A", "easy"),
    ("Tích phân xác định có tính chất nào sau đây?", "Đổi cận thì đổi dấu", "Luôn dương", "Bằng đạo hàm", "Không phụ thuộc hàm số", "A", "medium"),
    ("Hàm số khả tích Riemann trên đoạn khi nào?", "Khi tổng Riemann hội tụ về một giới hạn khi chia nhỏ đoạn", "Khi hàm số liên tục tại mọi điểm", "Khi hàm số đơn điệu", "Khi hàm số có đạo hàm", "A", "hard"),
    ("Chuỗi hình học có công bội q hội tụ khi nào?", "Khi |q| < 1", "Khi |q| > 1", "Khi q = 1", "Với mọi q", "A", "medium"),
    ("Tổng của chuỗi hình học 1 + q + q^2 + ... với |q| < 1 bằng bao nhiêu?", "1/(1-q)", "1/(1+q)", "q/(1-q)", "1-q", "A", "medium"),
    ("Tiêu chuẩn D'Alembert dùng để xét gì?", "Sự hội tụ của chuỗi số dương qua tỷ số hai số hạng liên tiếp", "Tính liên tục của hàm", "Sự tồn tại đạo hàm", "Giá trị tích phân", "A", "hard"),
    ("Chuỗi đan dấu hội tụ theo tiêu chuẩn Leibniz khi nào?", "Khi dãy trị tuyệt đối giảm và tiến tới 0", "Khi các số hạng đều dương", "Khi tổng riêng bị chặn", "Khi có hữu hạn số hạng", "A", "hard"),
    ("Chuỗi lũy thừa có bán kính hội tụ R nghĩa là gì?", "Chuỗi hội tụ khi |x| < R và phân kỳ khi |x| > R", "Chuỗi luôn hội tụ", "Chuỗi hội tụ tại mọi điểm", "Chuỗi chỉ hội tụ tại x = R", "A", "hard"),
    ("Khai triển Maclaurin là trường hợp riêng của khai triển Taylor tại điểm nào?", "x = 0", "x = 1", "x = -1", "x tiến tới vô cùng", "A", "medium"),
    ("Khai triển Maclaurin của e^x có dạng nào?", "1 + x + x^2/2! + x^3/3! + ...", "1 - x + x^2 - x^3 + ...", "x - x^3/3! + x^5/5! - ...", "1 + x + x^2 + x^3 + ...", "A", "hard"),
    ("Hàm số nhiều biến f(x,y) liên tục tại điểm khi nào?", "Khi giới hạn tại điểm đó tồn tại và bằng giá trị hàm", "Khi có đạo hàm riêng", "Khi bị chặn", "Khi đơn điệu theo x", "A", "medium"),
    ("Vi phân toàn phần của hàm z = f(x,y) là gì?", "dz = (∂f/∂x)dx + (∂f/∂y)dy", "dz = f'(x)dx", "dz = (∂f/∂x)(∂f/∂y)", "dz = dx + dy", "A", "hard"),
    ("Cực trị của hàm hai biến được tìm bằng cách nào?", "Giải hệ đạo hàm riêng bằng 0 rồi xét ma trận Hess", "Chỉ giải đạo hàm riêng theo x", "Tính tích phân kép", "Tìm hạng ma trận", "A", "hard"),
    ("Tích phân kép dùng để tính đại lượng nào?", "Thể tích khối trụ cong hoặc diện tích miền phẳng", "Độ dài đường cong", "Đạo hàm riêng", "Giá trị riêng", "A", "medium"),
    ("Tích phân đường loại một dùng để tính gì?", "Độ dài cung hoặc khối lượng dây cong", "Công của lực", "Thông lượng qua mặt", "Thể tích khối", "A", "hard"),
    ("Công thức Green liên hệ giữa loại tích phân nào?", "Tích phân đường trên đường cong kín và tích phân kép trên miền phẳng", "Tích phân đơn và tích phân kép", "Tích phân mặt và tích phân bội ba", "Đạo hàm và tích phân", "A", "hard"),
    ("Phương trình vi phân tuyến tính cấp một có dạng nào?", "y' + p(x)y = q(x)", "y' = f(x)g(y)", "y'' + ay' + by = 0", "y' = y^2", "A", "medium"),
    ("Phương trình vi phân tuyến tính thuần nhất cấp hai hệ số hằng có phương trình đặc trưng dạng nào?", "k^2 + ak + b = 0", "k + a = 0", "k^3 + a = 0", "ak + b = 0", "A", "hard"),
    ("Nếu phương trình đặc trưng có hai nghiệm thực phân biệt k1, k2 thì nghiệm tổng quát là gì?", "y = C1·e^(k1x) + C2·e^(k2x)", "y = (C1 + C2x)e^(kx)", "y = C1·sin(kx) + C2·cos(kx)", "y = C1x + C2", "A", "hard"),
    ("Giới hạn một phía của hàm số là gì?", "Giới hạn khi x tiến tới điểm chỉ từ bên trái hoặc bên phải", "Giới hạn tại vô cực", "Giới hạn của dãy số", "Giá trị của hàm tại điểm", "A", "medium"),
    ("Hàm số có tiệm cận đứng tại x = a khi nào?", "Khi giới hạn của hàm tại a bằng vô cùng", "Khi hàm liên tục tại a", "Khi f(a) = 0", "Khi đạo hàm tại a bằng 0", "A", "medium"),
    ("Vô cùng bé tương đương sin(x) ~ x đúng khi nào?", "Khi x tiến tới 0", "Khi x tiến tới vô cùng", "Với mọi x", "Khi x tiến tới 1", "A", "medium"),
    ("Giới hạn của (e^x - 1)/x khi x tiến tới 0 bằng bao nhiêu?", "0", "1", "e", "Vô cùng", "B", "medium"),
    ("Giới hạn của ln(1+x)/x khi x tiến tới 0 bằng bao nhiêu?", "0", "1", "e", "Không tồn tại", "B", "medium"),
    ("Định lý Rolle phát biểu điều gì?", "Nếu f(a) = f(b) thì tồn tại c trong (a,b) mà f'(c) = 0", "Hàm liên tục luôn khả vi", "Tích phân bằng diện tích", "Đạo hàm luôn dương", "A", "hard"),
    ("Điểm uốn của đồ thị hàm số là gì?", "Điểm mà đồ thị đổi chiều lồi lõm", "Điểm cực đại", "Điểm cực tiểu", "Điểm gián đoạn", "A", "medium"),
    ("Hàm số lồi trên khoảng khi nào?", "Khi đạo hàm cấp hai không âm trên khoảng đó", "Khi đạo hàm cấp một dương", "Khi hàm tăng", "Khi hàm bị chặn", "A", "hard"),
    ("Tích phân bất định khác tích phân xác định ở điểm nào?", "Kết quả là họ nguyên hàm có hằng số C, không phải một số cụ thể", "Không tính được", "Chỉ dùng cho hàm liên tục", "Luôn bằng 0", "A", "easy"),
    ("Phương pháp đổi biến trong tích phân nhằm mục đích gì?", "Đưa tích phân về dạng đơn giản hơn để tính", "Tăng bậc của hàm", "Đổi cận thành vô cực", "Loại bỏ hằng số C", "A", "easy"),
    ("Chuỗi Fourier dùng để biểu diễn hàm số dưới dạng gì?", "Tổng các hàm lượng giác sin và cos", "Tổng các đa thức", "Tích các hàm mũ", "Chuỗi lũy thừa", "A", "hard"),
    ("Hàm tuần hoàn có chu kỳ T thỏa mãn điều gì?", "f(x + T) = f(x) với mọi x", "f(x) = 0 tại x = T", "f'(T) = 0", "f(T) = T", "A", "easy"),
    ("Chu kỳ của hàm số y = sin(x) là bao nhiêu?", "π", "2π", "π/2", "4π", "B", "easy"),
    ("Hàm số y = |x| có đạo hàm tại x = 0 không?", "Không, vì đạo hàm trái và phải khác nhau", "Có, bằng 0", "Có, bằng 1", "Có, bằng vô cùng", "A", "medium"),
    ("Tập xác định của hàm số y = √x là gì?", "x >= 0", "x > 0", "Mọi số thực", "x khác 0", "A", "easy"),
    ("Đạo hàm của y = √x là gì?", "1/(2√x)", "2√x", "1/√x", "√x/2", "A", "medium"),
    ("Vi phân được ứng dụng để làm gì trong tính toán gần đúng?", "Xấp xỉ độ biến thiên của hàm số khi biến số thay đổi nhỏ", "Tính diện tích chính xác", "Tìm nghiệm phương trình", "Xác định tập xác định", "A", "medium"),
    ("Tích phân suy rộng loại một có đặc điểm gì?", "Có ít nhất một cận là vô cực", "Hàm số không bị chặn", "Cận trên bằng cận dưới", "Hàm số gián đoạn", "A", "hard"),
    ("Ứng dụng của tích phân trong vật lý là gì?", "Tính quãng đường, công của lực, khối lượng vật thể", "Chỉ tính diện tích", "Chỉ tính vận tốc", "Không có ứng dụng", "A", "easy"),
    ("Hàm ẩn được xác định bởi phương trình F(x,y) = 0 có đạo hàm y' tính thế nào?", "y' = -(∂F/∂x)/(∂F/∂y)", "y' = (∂F/∂x)·(∂F/∂y)", "y' = ∂F/∂x", "y' = 1/(∂F/∂y)", "A", "hard"),
    ("Cực trị có điều kiện được tìm bằng phương pháp nào?", "Phương pháp nhân tử Lagrange", "Phương pháp Gauss", "Phương pháp Newton", "Phương pháp Cramer", "A", "hard"),
]

XAC_SUAT_THONG_KE = [
    ("Xác suất của một biến cố luôn nằm trong khoảng nào?", "Từ 0 đến 1", "Từ -1 đến 1", "Từ 0 đến 100", "Từ 1 đến vô cùng", "A", "easy"),
    ("Xác suất của biến cố chắc chắn bằng bao nhiêu?", "0", "0,5", "1", "Vô cùng", "C", "easy"),
    ("Xác suất của biến cố không thể bằng bao nhiêu?", "0", "0,5", "1", "-1", "A", "easy"),
    ("Gieo một con xúc xắc cân đối, xác suất xuất hiện mặt 6 chấm là bao nhiêu?", "1/6", "1/2", "1/3", "1/12", "A", "easy"),
    ("Gieo một đồng xu cân đối, xác suất xuất hiện mặt ngửa là bao nhiêu?", "1/2", "1/3", "1/4", "1", "A", "easy"),
    ("Hai biến cố xung khắc là hai biến cố như thế nào?", "Không thể cùng xảy ra", "Luôn cùng xảy ra", "Độc lập với nhau", "Có xác suất bằng nhau", "A", "easy"),
    ("Công thức cộng xác suất cho hai biến cố xung khắc A, B là gì?", "P(A hoặc B) = P(A) + P(B)", "P(A hoặc B) = P(A)·P(B)", "P(A hoặc B) = P(A) - P(B)", "P(A hoặc B) = P(A)/P(B)", "A", "easy"),
    ("Hai biến cố độc lập thỏa mãn công thức nào?", "P(A và B) = P(A)·P(B)", "P(A và B) = P(A) + P(B)", "P(A và B) = 0", "P(A và B) = 1", "A", "medium"),
    ("Xác suất có điều kiện P(A|B) được tính bằng công thức nào?", "P(A và B)/P(B)", "P(A)·P(B)", "P(A) + P(B)", "P(B)/P(A)", "A", "medium"),
    ("Công thức Bayes dùng để làm gì?", "Tính xác suất hậu nghiệm khi biết thông tin mới", "Tính kỳ vọng", "Tính phương sai", "Ước lượng khoảng tin cậy", "A", "hard"),
    ("Biến ngẫu nhiên rời rạc là gì?", "Biến nhận hữu hạn hoặc đếm được các giá trị", "Biến nhận mọi giá trị trong một khoảng", "Biến luôn dương", "Biến không đổi", "A", "medium"),
    ("Kỳ vọng của biến ngẫu nhiên biểu thị điều gì?", "Giá trị trung bình theo xác suất", "Độ phân tán", "Giá trị lớn nhất", "Xác suất lớn nhất", "A", "easy"),
    ("Phương sai đo lường điều gì?", "Mức độ phân tán của biến ngẫu nhiên quanh kỳ vọng", "Giá trị trung bình", "Giá trị lớn nhất", "Xác suất xảy ra", "A", "easy"),
    ("Độ lệch chuẩn có quan hệ gì với phương sai?", "Là căn bậc hai của phương sai", "Là bình phương phương sai", "Bằng phương sai", "Là nghịch đảo phương sai", "A", "easy"),
    ("Phân phối nhị thức mô tả tình huống nào?", "Số lần thành công trong n phép thử độc lập với xác suất p không đổi", "Số lần thất bại liên tiếp", "Thời gian chờ đợi", "Biến liên tục đối xứng", "A", "medium"),
    ("Kỳ vọng của phân phối nhị thức B(n,p) bằng bao nhiêu?", "np", "np(1-p)", "n/p", "p/n", "A", "medium"),
    ("Phương sai của phân phối nhị thức B(n,p) bằng bao nhiêu?", "np", "np(1-p)", "n^2p", "p(1-p)", "B", "medium"),
    ("Phân phối chuẩn có đồ thị hàm mật độ hình dạng nào?", "Hình chuông đối xứng", "Đường thẳng", "Hình chữ nhật", "Hình tam giác", "A", "easy"),
    ("Phân phối chuẩn tắc có kỳ vọng và phương sai bằng bao nhiêu?", "0 và 1", "1 và 0", "1 và 1", "0 và 0", "A", "medium"),
    ("Quy tắc 3-sigma cho biết điều gì?", "Khoảng 99,7% giá trị nằm trong khoảng trung bình cộng trừ 3 độ lệch chuẩn", "Toàn bộ giá trị nằm trong 3 đơn vị", "Xác suất bằng 3 lần độ lệch", "Trung bình bằng 3 lần phương sai", "A", "medium"),
    ("Phân phối Poisson mô tả điều gì?", "Số lần xảy ra biến cố hiếm trong khoảng thời gian hoặc không gian nhất định", "Số lần thành công trong n phép thử", "Thời gian sống của thiết bị", "Biến ngẫu nhiên liên tục đối xứng", "A", "medium"),
    ("Tổng thể trong thống kê là gì?", "Tập hợp toàn bộ các phần tử cần nghiên cứu", "Một phần được chọn ra để khảo sát", "Giá trị trung bình", "Số liệu thu thập được", "A", "easy"),
    ("Mẫu trong thống kê là gì?", "Tập con được chọn từ tổng thể để nghiên cứu", "Toàn bộ tổng thể", "Kết quả tính toán", "Sai số đo lường", "A", "easy"),
    ("Trung bình mẫu được dùng để làm gì?", "Ước lượng trung bình tổng thể", "Tính phương sai tổng thể", "Xác định phân phối", "Kiểm định giả thuyết duy nhất", "A", "easy"),
    ("Trung vị là giá trị nào?", "Giá trị chia dãy số liệu đã sắp xếp thành hai phần bằng nhau", "Giá trị xuất hiện nhiều nhất", "Giá trị trung bình cộng", "Giá trị lớn nhất", "A", "easy"),
    ("Mốt (Mode) là gì?", "Giá trị xuất hiện với tần số lớn nhất", "Giá trị ở giữa dãy", "Trung bình cộng", "Hiệu giữa max và min", "A", "easy"),
    ("Khi dữ liệu có giá trị ngoại lai lớn, nên dùng đại lượng nào để đại diện?", "Trung vị", "Trung bình cộng", "Phương sai", "Tổng", "A", "medium"),
    ("Ước lượng điểm là gì?", "Dùng một giá trị duy nhất để ước lượng tham số tổng thể", "Dùng một khoảng giá trị", "Kiểm định giả thuyết", "Vẽ biểu đồ phân phối", "A", "medium"),
    ("Khoảng tin cậy 95% có ý nghĩa gì?", "Với độ tin cậy 95%, tham số tổng thể nằm trong khoảng đó", "95% dữ liệu nằm trong khoảng", "Sai số là 95%", "Xác suất sai bằng 95%", "A", "medium"),
    ("Khi tăng độ tin cậy thì độ rộng khoảng tin cậy thay đổi thế nào?", "Rộng ra", "Hẹp lại", "Không đổi", "Bằng 0", "A", "hard"),
    ("Khi tăng cỡ mẫu thì độ rộng khoảng tin cậy thay đổi thế nào?", "Hẹp lại", "Rộng ra", "Không đổi", "Tăng gấp đôi", "A", "medium"),
    ("Giả thuyết không (H0) trong kiểm định là gì?", "Giả thuyết được đưa ra để kiểm định, thường mang tính không có sự khác biệt", "Giả thuyết luôn đúng", "Giả thuyết đối lập cần chứng minh", "Kết luận cuối cùng", "A", "medium"),
    ("Sai lầm loại một trong kiểm định giả thuyết là gì?", "Bác bỏ H0 khi H0 đúng", "Chấp nhận H0 khi H0 sai", "Tính sai giá trị trung bình", "Chọn sai cỡ mẫu", "A", "hard"),
    ("Sai lầm loại hai trong kiểm định giả thuyết là gì?", "Chấp nhận H0 khi H0 sai", "Bác bỏ H0 khi H0 đúng", "Sai sót khi thu thập số liệu", "Sai sót trong tính toán", "A", "hard"),
    ("Mức ý nghĩa alpha thường được chọn là bao nhiêu?", "0,05 hoặc 0,01", "0,5", "0,95", "1", "A", "easy"),
    ("Giá trị p-value nhỏ hơn mức ý nghĩa thì kết luận gì?", "Bác bỏ giả thuyết H0", "Chấp nhận H0", "Không có kết luận", "Tăng cỡ mẫu", "A", "medium"),
    ("Hệ số tương quan r nhận giá trị trong khoảng nào?", "Từ -1 đến 1", "Từ 0 đến 1", "Từ 0 đến vô cùng", "Từ -∞ đến +∞", "A", "medium"),
    ("Hệ số tương quan r = 0 nghĩa là gì?", "Không có mối liên hệ tuyến tính giữa hai biến", "Hai biến độc lập hoàn toàn", "Hai biến bằng nhau", "Có quan hệ hàm số", "A", "medium"),
    ("Hồi quy tuyến tính đơn mô tả quan hệ giữa mấy biến?", "Một biến phụ thuộc và một biến độc lập", "Hai biến phụ thuộc", "Nhiều biến độc lập", "Không có biến nào", "A", "easy"),
    ("Phương pháp bình phương tối thiểu dùng để làm gì?", "Tìm đường hồi quy sao cho tổng bình phương sai số nhỏ nhất", "Tính phương sai", "Kiểm định giả thuyết", "Chọn mẫu ngẫu nhiên", "A", "medium"),
    ("Chọn mẫu ngẫu nhiên đơn giản có đặc điểm gì?", "Mọi phần tử của tổng thể có cơ hội được chọn như nhau", "Chọn theo thứ tự danh sách", "Chọn theo nhóm", "Chọn theo ý người nghiên cứu", "A", "easy"),
    ("Tần suất tương đối được tính bằng gì?", "Tần số chia tổng số quan sát", "Tần số nhân tổng số", "Tổng các tần số", "Hiệu giữa các tần số", "A", "easy"),
    ("Biểu đồ histogram dùng để biểu diễn gì?", "Phân bố tần số của dữ liệu liên tục", "Tỷ lệ phần trăm các thành phần", "Xu hướng theo thời gian", "Mối quan hệ hai biến", "A", "easy"),
    ("Biểu đồ hình tròn (pie chart) phù hợp để biểu diễn gì?", "Tỷ trọng các thành phần trong tổng thể", "Xu hướng thay đổi", "Phân bố liên tục", "Tương quan hai biến", "A", "easy"),
    ("Quy tắc nhân xác suất áp dụng cho trường hợp nào?", "Tính xác suất đồng thời xảy ra của các biến cố", "Tính xác suất một trong các biến cố xảy ra", "Tính kỳ vọng", "Tính phương sai", "A", "medium"),
    ("Số hoán vị của n phần tử khác nhau bằng bao nhiêu?", "n!", "n^2", "2^n", "n(n-1)/2", "A", "medium"),
    ("Số tổ hợp chập k của n phần tử được tính bằng công thức nào?", "n!/(k!(n-k)!)", "n!/(n-k)!", "n!·k!", "n^k", "A", "medium"),
    ("Số chỉnh hợp chập k của n phần tử bằng bao nhiêu?", "n!/(n-k)!", "n!/(k!(n-k)!)", "n!·k", "k^n", "A", "hard"),
    ("Định lý giới hạn trung tâm phát biểu điều gì?", "Trung bình mẫu có phân phối xấp xỉ chuẩn khi cỡ mẫu đủ lớn", "Mọi biến ngẫu nhiên đều phân phối chuẩn", "Phương sai luôn giảm", "Xác suất luôn hội tụ về 1", "A", "hard"),
    ("Ứng dụng của thống kê trong nghiên cứu khoa học là gì?", "Thu thập, phân tích dữ liệu và rút ra kết luận có căn cứ", "Chỉ để vẽ biểu đồ", "Chỉ để tính trung bình", "Không có ứng dụng thực tế", "A", "easy"),
]

VAT_LY_DAI_CUONG = [
    ("Đơn vị đo lực trong hệ SI là gì?", "Newton (N)", "Jun (J)", "Watt (W)", "Pascal (Pa)", "A", "easy"),
    ("Định luật I Newton phát biểu điều gì?", "Vật giữ nguyên trạng thái đứng yên hoặc chuyển động thẳng đều nếu không có lực tác dụng", "Gia tốc tỷ lệ với lực", "Lực và phản lực bằng nhau", "Năng lượng được bảo toàn", "A", "easy"),
    ("Định luật II Newton có biểu thức nào?", "F = ma", "F = mv", "F = mgh", "F = 1/2mv^2", "A", "easy"),
    ("Định luật III Newton phát biểu điều gì?", "Lực và phản lực có độ lớn bằng nhau, ngược chiều", "Vật luôn chuyển động thẳng đều", "Gia tốc tỷ lệ nghịch với khối lượng", "Động lượng luôn tăng", "A", "easy"),
    ("Công thức tính động năng là gì?", "1/2mv^2", "mgh", "mv", "F·s", "A", "easy"),
    ("Công thức tính thế năng trọng trường là gì?", "mgh", "1/2mv^2", "mv", "F·s", "A", "easy"),
    ("Đơn vị đo công và năng lượng trong hệ SI là gì?", "Jun (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)", "A", "easy"),
    ("Công suất được tính bằng công thức nào?", "P = A/t", "P = F·m", "P = mgh", "P = mv", "A", "easy"),
    ("Đơn vị đo công suất trong hệ SI là gì?", "Watt (W)", "Jun (J)", "Newton (N)", "Ampe (A)", "A", "easy"),
    ("Động lượng của vật được tính bằng công thức nào?", "p = mv", "p = ma", "p = 1/2mv^2", "p = mgh", "A", "easy"),
    ("Định luật bảo toàn động lượng áp dụng cho hệ nào?", "Hệ kín (không có ngoại lực hoặc ngoại lực cân bằng)", "Mọi hệ vật", "Chỉ hệ có ma sát", "Chỉ vật rơi tự do", "A", "medium"),
    ("Gia tốc rơi tự do trên Trái Đất xấp xỉ bao nhiêu?", "9,8 m/s^2", "10 m/s", "9,8 m/s", "1,6 m/s^2", "A", "easy"),
    ("Chuyển động thẳng đều có đặc điểm gì?", "Vận tốc không đổi theo thời gian", "Gia tốc không đổi khác 0", "Quãng đường tỷ lệ bình phương thời gian", "Vận tốc tăng dần", "A", "easy"),
    ("Trong chuyển động thẳng biến đổi đều, công thức nào đúng?", "v = v0 + at", "v = v0·t", "v = at^2", "v = v0/t", "A", "medium"),
    ("Lực ma sát trượt phụ thuộc vào yếu tố nào?", "Áp lực và hệ số ma sát", "Diện tích tiếp xúc", "Vận tốc chuyển động", "Khối lượng riêng", "A", "medium"),
    ("Định luật vạn vật hấp dẫn phát biểu lực hấp dẫn tỷ lệ thế nào?", "Tỷ lệ thuận với tích hai khối lượng và nghịch với bình phương khoảng cách", "Tỷ lệ thuận với khoảng cách", "Tỷ lệ nghịch với khối lượng", "Không phụ thuộc khoảng cách", "A", "medium"),
    ("Chuyển động tròn đều có gia tốc gì?", "Gia tốc hướng tâm", "Gia tốc bằng 0", "Gia tốc tiếp tuyến khác 0", "Gia tốc rơi tự do", "A", "medium"),
    ("Công thức tính gia tốc hướng tâm là gì?", "a = v^2/r", "a = v/r", "a = vr", "a = r/v^2", "A", "medium"),
    ("Momen lực được tính bằng công thức nào?", "M = F·d", "M = F/d", "M = F + d", "M = F·v", "A", "medium"),
    ("Điều kiện cân bằng của vật rắn có trục quay cố định là gì?", "Tổng momen lực theo chiều kim đồng hồ bằng tổng momen ngược chiều", "Tổng lực bằng 0", "Vận tốc bằng 0", "Khối lượng phân bố đều", "A", "medium"),
    ("Áp suất chất lỏng ở độ sâu h được tính bằng công thức nào?", "p = ρgh", "p = mgh", "p = F/m", "p = ρg/h", "A", "medium"),
    ("Định luật Ác-si-mét phát biểu điều gì?", "Vật nhúng trong chất lỏng chịu lực đẩy bằng trọng lượng phần chất lỏng bị chiếm chỗ", "Áp suất truyền đi nguyên vẹn", "Chất lỏng chảy nhanh thì áp suất giảm", "Nhiệt lượng được bảo toàn", "A", "easy"),
    ("Định luật Pascal phát biểu điều gì?", "Áp suất tác dụng lên chất lỏng được truyền nguyên vẹn theo mọi hướng", "Vật nổi khi khối lượng riêng nhỏ hơn", "Lưu lượng không đổi", "Nhiệt truyền từ nóng sang lạnh", "A", "medium"),
    ("Nguyên lý I nhiệt động lực học phát biểu điều gì?", "Độ biến thiên nội năng bằng tổng nhiệt lượng và công nhận được", "Nhiệt không tự truyền từ lạnh sang nóng", "Entropy luôn tăng", "Năng lượng luôn giảm", "A", "medium"),
    ("Nguyên lý II nhiệt động lực học phát biểu điều gì?", "Nhiệt không thể tự truyền từ vật lạnh sang vật nóng hơn", "Năng lượng được bảo toàn", "Công bằng nhiệt lượng", "Nội năng không đổi", "A", "medium"),
    ("Quá trình đẳng nhiệt có đặc điểm gì?", "Nhiệt độ không đổi", "Áp suất không đổi", "Thể tích không đổi", "Không trao đổi nhiệt", "A", "easy"),
    ("Quá trình đẳng tích có đặc điểm gì?", "Thể tích không đổi", "Nhiệt độ không đổi", "Áp suất không đổi", "Nội năng không đổi", "A", "easy"),
    ("Định luật Bôi-lơ Ma-ri-ốt áp dụng cho quá trình nào?", "Đẳng nhiệt", "Đẳng tích", "Đẳng áp", "Đoạn nhiệt", "A", "medium"),
    ("Phương trình trạng thái khí lý tưởng có dạng nào?", "pV = nRT", "pV = mgh", "p = ρgh", "pV = 1/2mv^2", "A", "medium"),
    ("Điện tích cùng dấu thì tương tác thế nào?", "Đẩy nhau", "Hút nhau", "Không tương tác", "Trung hòa nhau", "A", "easy"),
    ("Định luật Coulomb mô tả lực tương tác giữa hai điện tích tỷ lệ thế nào?", "Thuận với tích độ lớn điện tích, nghịch với bình phương khoảng cách", "Thuận với khoảng cách", "Nghịch với điện tích", "Không đổi", "A", "medium"),
    ("Cường độ dòng điện được đo bằng đơn vị nào?", "Ampe (A)", "Vôn (V)", "Ôm (Ω)", "Watt (W)", "A", "easy"),
    ("Định luật Ôm cho đoạn mạch có biểu thức nào?", "I = U/R", "I = UR", "U = IR^2", "R = UI", "A", "easy"),
    ("Điện trở của dây dẫn phụ thuộc vào yếu tố nào?", "Điện trở suất, chiều dài và tiết diện dây", "Cường độ dòng điện", "Hiệu điện thế", "Công suất tiêu thụ", "A", "medium"),
    ("Công thức tính công suất điện là gì?", "P = UI", "P = U/I", "P = I/U", "P = U + I", "A", "easy"),
    ("Trong mạch nối tiếp, cường độ dòng điện qua các điện trở như thế nào?", "Bằng nhau", "Khác nhau", "Tỷ lệ với điện trở", "Bằng 0", "A", "easy"),
    ("Trong mạch song song, hiệu điện thế giữa các nhánh như thế nào?", "Bằng nhau", "Khác nhau", "Tỷ lệ nghịch với điện trở", "Bằng 0", "A", "easy"),
    ("Từ trường được sinh ra bởi cái gì?", "Dòng điện hoặc nam châm", "Điện tích đứng yên", "Vật nóng", "Ánh sáng", "A", "easy"),
    ("Lực Lorentz tác dụng lên điện tích chuyển động trong từ trường có phương thế nào?", "Vuông góc với cả vận tốc và cảm ứng từ", "Cùng phương vận tốc", "Cùng phương cảm ứng từ", "Ngược chiều vận tốc", "A", "hard"),
    ("Hiện tượng cảm ứng điện từ do ai phát hiện?", "Faraday", "Newton", "Ohm", "Coulomb", "A", "easy"),
    ("Định luật Lenz xác định điều gì?", "Chiều dòng điện cảm ứng chống lại nguyên nhân sinh ra nó", "Độ lớn suất điện động", "Cường độ từ trường", "Điện trở của mạch", "A", "medium"),
    ("Sóng cơ học truyền được trong môi trường nào?", "Rắn, lỏng, khí", "Chân không", "Chỉ trong chất rắn", "Chỉ trong không khí", "A", "easy"),
    ("Bước sóng, tần số và tốc độ truyền sóng liên hệ theo công thức nào?", "v = λf", "v = λ/f", "λ = vf", "f = vλ", "A", "medium"),
    ("Hiện tượng giao thoa ánh sáng chứng tỏ điều gì?", "Ánh sáng có tính chất sóng", "Ánh sáng có tính chất hạt", "Ánh sáng truyền thẳng", "Ánh sáng bị hấp thụ", "A", "medium"),
    ("Hiện tượng quang điện chứng tỏ điều gì về ánh sáng?", "Ánh sáng có tính chất hạt (photon)", "Ánh sáng chỉ là sóng", "Ánh sáng không mang năng lượng", "Ánh sáng có khối lượng nghỉ", "A", "medium"),
    ("Năng lượng của một photon được tính bằng công thức nào?", "E = hf", "E = mc", "E = 1/2mv^2", "E = mgh", "A", "medium"),
    ("Hiện tượng khúc xạ ánh sáng xảy ra khi nào?", "Khi ánh sáng truyền qua mặt phân cách hai môi trường trong suốt khác nhau", "Khi ánh sáng gặp gương phẳng", "Khi ánh sáng truyền trong chân không", "Khi ánh sáng bị hấp thụ", "A", "easy"),
    ("Thấu kính hội tụ có đặc điểm gì?", "Phần rìa mỏng hơn phần giữa, làm hội tụ chùm tia song song", "Phần giữa mỏng hơn rìa", "Không làm đổi hướng tia sáng", "Chỉ phản xạ ánh sáng", "A", "easy"),
    ("Thuyết tương đối hẹp của Einstein dựa trên tiên đề nào?", "Tốc độ ánh sáng trong chân không là hằng số với mọi hệ quy chiếu quán tính", "Thời gian là tuyệt đối", "Khối lượng không đổi", "Không gian phẳng tuyệt đối", "A", "hard"),
    ("Hệ thức Einstein giữa khối lượng và năng lượng là gì?", "E = mc^2", "E = mv^2", "E = mgh", "E = hf", "A", "easy"),
]

DATA = {
    'Toán cao cấp': TOAN_CAO_CAP,
    'Đại số tuyến tính': DAI_SO_TUYEN_TINH,
    'Giải tích': GIAI_TICH,
    'Xác suất thống kê': XAC_SUAT_THONG_KE,
    'Vật lý đại cương': VAT_LY_DAI_CUONG,
}
