# -*- coding: utf-8 -*-
"""Nhóm Kinh tế - Quản trị."""

KINH_TE_VI_MO = [
    ("Kinh tế vi mô nghiên cứu đối tượng nào?", "Hành vi của từng cá nhân, hộ gia đình và doanh nghiệp", "Toàn bộ nền kinh tế quốc dân", "Chính sách tiền tệ quốc gia", "Thương mại quốc tế", "A", "easy"),
    ("Ba vấn đề kinh tế cơ bản của mọi nền kinh tế là gì?", "Sản xuất cái gì, sản xuất như thế nào, sản xuất cho ai", "Mua gì, bán gì, lãi bao nhiêu", "Vốn, lao động, công nghệ", "Cung, cầu, giá cả", "A", "easy"),
    ("Chi phí cơ hội là gì?", "Giá trị của phương án tốt nhất bị bỏ qua khi lựa chọn", "Tổng chi phí sản xuất", "Chi phí cố định", "Khoản lỗ của doanh nghiệp", "A", "medium"),
    ("Quy luật cầu phát biểu điều gì?", "Giá tăng thì lượng cầu giảm, các yếu tố khác không đổi", "Giá tăng thì lượng cầu tăng", "Cầu không phụ thuộc giá", "Cầu luôn bằng cung", "A", "easy"),
    ("Quy luật cung phát biểu điều gì?", "Giá tăng thì lượng cung tăng, các yếu tố khác không đổi", "Giá tăng thì lượng cung giảm", "Cung không đổi theo giá", "Cung luôn lớn hơn cầu", "A", "easy"),
    ("Điểm cân bằng thị trường là điểm nào?", "Nơi lượng cung bằng lượng cầu", "Nơi giá cao nhất", "Nơi lợi nhuận lớn nhất", "Nơi chi phí thấp nhất", "A", "easy"),
    ("Khi giá cao hơn giá cân bằng thì thị trường xảy ra hiện tượng gì?", "Dư thừa hàng hóa", "Thiếu hụt hàng hóa", "Cân bằng mới ngay lập tức", "Cầu tăng đột biến", "A", "medium"),
    ("Khi giá thấp hơn giá cân bằng thì xảy ra hiện tượng gì?", "Thiếu hụt hàng hóa", "Dư thừa hàng hóa", "Không có gì thay đổi", "Cung tăng mạnh", "A", "medium"),
    ("Yếu tố nào làm dịch chuyển đường cầu (không phải di chuyển dọc đường cầu)?", "Thu nhập người tiêu dùng thay đổi", "Giá của chính hàng hóa đó thay đổi", "Lượng cầu thay đổi", "Doanh thu thay đổi", "A", "hard"),
    ("Hàng hóa thông thường có đặc điểm gì?", "Thu nhập tăng thì cầu tăng", "Thu nhập tăng thì cầu giảm", "Cầu không đổi theo thu nhập", "Chỉ người giàu mua", "A", "medium"),
    ("Hàng hóa thứ cấp có đặc điểm gì?", "Thu nhập tăng thì cầu giảm", "Thu nhập tăng thì cầu tăng", "Giá luôn rẻ", "Chất lượng kém", "A", "medium"),
    ("Hai hàng hóa thay thế nhau có quan hệ thế nào?", "Giá hàng này tăng thì cầu hàng kia tăng", "Giá hàng này tăng thì cầu hàng kia giảm", "Không liên quan nhau", "Luôn mua cùng nhau", "A", "medium"),
    ("Hai hàng hóa bổ sung nhau có quan hệ thế nào?", "Giá hàng này tăng thì cầu hàng kia giảm", "Giá hàng này tăng thì cầu hàng kia tăng", "Không ảnh hưởng nhau", "Thay thế được cho nhau", "A", "medium"),
    ("Độ co giãn của cầu theo giá đo lường điều gì?", "Mức độ phản ứng của lượng cầu khi giá thay đổi", "Tổng doanh thu", "Chi phí sản xuất", "Lợi nhuận doanh nghiệp", "A", "medium"),
    ("Cầu co giãn khi hệ số co giãn có giá trị thế nào?", "Lớn hơn 1 về trị tuyệt đối", "Nhỏ hơn 1", "Bằng 0", "Bằng 1", "A", "medium"),
    ("Khi cầu co giãn, doanh nghiệp giảm giá thì tổng doanh thu thay đổi ra sao?", "Tăng lên", "Giảm xuống", "Không đổi", "Bằng 0", "A", "hard"),
    ("Hàng hóa thiết yếu thường có cầu như thế nào?", "Ít co giãn theo giá", "Rất co giãn theo giá", "Co giãn hoàn toàn", "Không có cầu", "A", "medium"),
    ("Lợi ích cận biên là gì?", "Lợi ích tăng thêm khi tiêu dùng thêm một đơn vị hàng hóa", "Tổng lợi ích tiêu dùng", "Chi phí tăng thêm", "Doanh thu tăng thêm", "A", "medium"),
    ("Quy luật lợi ích cận biên giảm dần phát biểu điều gì?", "Càng tiêu dùng nhiều thì lợi ích tăng thêm càng giảm", "Lợi ích luôn tăng đều", "Lợi ích không đổi", "Lợi ích luôn âm", "A", "medium"),
    ("Đường bàng quan biểu diễn điều gì?", "Các kết hợp hàng hóa mang lại cùng mức thỏa dụng", "Các mức giá khác nhau", "Chi phí sản xuất", "Lợi nhuận doanh nghiệp", "A", "hard"),
    ("Đường ngân sách biểu diễn điều gì?", "Các kết hợp hàng hóa mua được với thu nhập và giá cho trước", "Mức thỏa dụng như nhau", "Chi phí sản xuất tối thiểu", "Sản lượng tối đa", "A", "hard"),
    ("Chi phí cố định là gì?", "Chi phí không thay đổi theo sản lượng trong ngắn hạn", "Chi phí thay đổi theo sản lượng", "Chi phí nguyên vật liệu", "Chi phí nhân công theo giờ", "A", "easy"),
    ("Chi phí biến đổi là gì?", "Chi phí thay đổi theo mức sản lượng", "Chi phí thuê nhà xưởng", "Khấu hao máy móc", "Lãi vay ngân hàng cố định", "A", "easy"),
    ("Chi phí cận biên (MC) là gì?", "Chi phí tăng thêm khi sản xuất thêm một đơn vị sản phẩm", "Tổng chi phí chia sản lượng", "Chi phí cố định trung bình", "Chi phí lớn nhất", "A", "medium"),
    ("Doanh nghiệp tối đa hóa lợi nhuận khi nào?", "Khi doanh thu cận biên bằng chi phí cận biên", "Khi doanh thu lớn nhất", "Khi chi phí nhỏ nhất", "Khi sản lượng lớn nhất", "A", "hard"),
    ("Thị trường cạnh tranh hoàn hảo có đặc điểm gì?", "Nhiều người mua bán, sản phẩm đồng nhất, tự do gia nhập rút lui", "Một người bán duy nhất", "Sản phẩm khác biệt hóa cao", "Rào cản gia nhập lớn", "A", "medium"),
    ("Doanh nghiệp trong thị trường cạnh tranh hoàn hảo là gì?", "Người chấp nhận giá", "Người định giá", "Người độc quyền", "Người điều tiết thị trường", "A", "medium"),
    ("Độc quyền bán (Monopoly) có đặc điểm gì?", "Một người bán duy nhất, không có hàng thay thế gần gũi", "Nhiều người bán", "Sản phẩm đồng nhất", "Tự do gia nhập ngành", "A", "easy"),
    ("Doanh nghiệp độc quyền định giá như thế nào so với cạnh tranh hoàn hảo?", "Cao hơn và sản lượng thấp hơn", "Thấp hơn và sản lượng cao hơn", "Bằng nhau", "Không định được giá", "A", "medium"),
    ("Thị trường cạnh tranh độc quyền có đặc điểm gì?", "Nhiều doanh nghiệp bán sản phẩm khác biệt hóa", "Chỉ một doanh nghiệp", "Sản phẩm hoàn toàn giống nhau", "Không có cạnh tranh", "A", "medium"),
    ("Độc quyền nhóm (Oligopoly) có đặc điểm gì?", "Một số ít doanh nghiệp lớn chi phối thị trường", "Rất nhiều doanh nghiệp nhỏ", "Một doanh nghiệp duy nhất", "Không có rào cản gia nhập", "A", "medium"),
    ("Ngoại ứng tiêu cực là gì?", "Hoạt động gây thiệt hại cho bên thứ ba mà không phải trả chi phí", "Lợi ích lan tỏa cho xã hội", "Chi phí nội bộ doanh nghiệp", "Thuế nhà nước thu", "A", "medium"),
    ("Ví dụ điển hình của ngoại ứng tiêu cực là gì?", "Nhà máy xả thải gây ô nhiễm", "Tiêm vắc xin phòng bệnh", "Trồng cây xanh", "Giáo dục phổ cập", "A", "easy"),
    ("Hàng hóa công cộng có đặc điểm gì?", "Không cạnh tranh và không loại trừ trong tiêu dùng", "Chỉ người trả tiền mới dùng được", "Càng nhiều người dùng càng ít đi", "Do doanh nghiệp tư nhân cung cấp là chủ yếu", "A", "hard"),
    ("Thất bại thị trường là gì?", "Tình trạng thị trường phân bổ nguồn lực không hiệu quả", "Doanh nghiệp bị phá sản", "Giá cả giảm mạnh", "Cung vượt cầu tạm thời", "A", "medium"),
    ("Chính phủ can thiệp thị trường bằng công cụ nào?", "Thuế, trợ cấp, giá trần, giá sàn và quy định pháp luật", "Chỉ bằng tuyên truyền", "Chỉ bằng lãi suất", "Không can thiệp được", "A", "easy"),
    ("Giá trần (price ceiling) là gì?", "Mức giá tối đa được phép bán, thường gây thiếu hụt", "Mức giá tối thiểu", "Giá cân bằng thị trường", "Giá trung bình ngành", "A", "medium"),
    ("Giá sàn (price floor) thường gây hậu quả gì?", "Dư thừa hàng hóa", "Thiếu hụt hàng hóa", "Cân bằng thị trường", "Giá giảm mạnh", "A", "medium"),
    ("Thặng dư tiêu dùng là gì?", "Chênh lệch giữa mức sẵn lòng trả và giá thực tế phải trả", "Lợi nhuận doanh nghiệp", "Thuế nhà nước thu", "Chi phí sản xuất tiết kiệm được", "A", "hard"),
    ("Thặng dư sản xuất là gì?", "Chênh lệch giữa giá bán và chi phí tối thiểu người bán chấp nhận", "Tổng doanh thu", "Lợi ích người tiêu dùng", "Thuế phải nộp", "A", "hard"),
    ("Năng suất cận biên giảm dần xảy ra khi nào?", "Khi tăng thêm yếu tố đầu vào biến đổi trong điều kiện các yếu tố khác cố định", "Khi công nghệ tiến bộ", "Khi tăng mọi đầu vào cùng tỷ lệ", "Khi giá đầu vào giảm", "A", "hard"),
    ("Hiệu suất kinh tế theo quy mô tăng nghĩa là gì?", "Tăng đầu vào theo tỷ lệ làm sản lượng tăng nhiều hơn tỷ lệ đó", "Sản lượng tăng ít hơn", "Sản lượng không đổi", "Chi phí tăng gấp đôi", "A", "hard"),
    ("Điểm hòa vốn là điểm mà tại đó doanh nghiệp có kết quả gì?", "Tổng doanh thu bằng tổng chi phí", "Lợi nhuận lớn nhất", "Chi phí nhỏ nhất", "Sản lượng lớn nhất", "A", "medium"),
    ("Trong ngắn hạn, doanh nghiệp nên tiếp tục sản xuất khi nào dù lỗ?", "Khi giá bán còn cao hơn chi phí biến đổi trung bình", "Khi lỗ ít hơn năm trước", "Khi có nhiều khách hàng", "Luôn phải đóng cửa khi lỗ", "A", "hard"),
    ("Lợi nhuận kinh tế khác lợi nhuận kế toán ở điểm nào?", "Lợi nhuận kinh tế trừ cả chi phí cơ hội", "Hai khái niệm giống nhau", "Lợi nhuận kế toán luôn nhỏ hơn", "Lợi nhuận kinh tế không tính chi phí", "A", "hard"),
    ("Thị trường lao động cạnh tranh xác định tiền lương dựa vào đâu?", "Cung và cầu lao động", "Quyết định của chính phủ", "Ý muốn người lao động", "Lợi nhuận doanh nghiệp", "A", "medium"),
    ("Đường giới hạn khả năng sản xuất (PPF) biểu diễn điều gì?", "Các kết hợp sản lượng tối đa với nguồn lực có hạn", "Mức giá cân bằng", "Đường cầu thị trường", "Chi phí trung bình", "A", "medium"),
    ("Điểm nằm trong đường PPF thể hiện điều gì?", "Nguồn lực chưa được sử dụng hết", "Sản xuất hiệu quả tối đa", "Không thể đạt được", "Cân bằng thị trường", "A", "hard"),
    ("Kinh tế học thực chứng khác chuẩn tắc ở điểm nào?", "Thực chứng mô tả sự việc là gì, chuẩn tắc đưa ra đánh giá nên như thế nào", "Không có khác biệt", "Chuẩn tắc chính xác hơn", "Thực chứng dựa trên quan điểm cá nhân", "A", "medium"),
    ("Cạnh tranh có vai trò gì trong nền kinh tế thị trường?", "Thúc đẩy đổi mới, nâng cao chất lượng và giảm giá thành", "Làm tăng giá hàng hóa", "Giảm lựa chọn cho người tiêu dùng", "Không có tác dụng gì", "A", "easy"),
]

KINH_TE_VI_MO_2 = [
    ("Kinh tế vĩ mô nghiên cứu đối tượng nào?", "Nền kinh tế như một tổng thể", "Hành vi của từng doanh nghiệp", "Quyết định của người tiêu dùng cá nhân", "Cách định giá một sản phẩm", "A", "easy"),
    ("GDP là gì?", "Tổng giá trị hàng hóa dịch vụ cuối cùng được sản xuất trong lãnh thổ một nước trong một thời kỳ", "Tổng thu nhập của người dân một nước ở mọi nơi", "Tổng tài sản quốc gia", "Tổng ngân sách nhà nước", "A", "easy"),
    ("GNP khác GDP ở điểm nào?", "GNP tính theo quyền sở hữu công dân, GDP tính theo lãnh thổ", "GNP luôn lớn hơn GDP", "Hai chỉ tiêu giống nhau", "GDP tính cả nước ngoài", "A", "medium"),
    ("GDP danh nghĩa khác GDP thực tế ở điểm nào?", "GDP thực tế đã loại trừ ảnh hưởng của biến động giá", "GDP danh nghĩa chính xác hơn", "Hai chỉ tiêu bằng nhau", "GDP thực tế tính theo giá hiện hành", "A", "medium"),
    ("GDP bình quân đầu người phản ánh điều gì?", "Mức sống trung bình của dân cư một nước", "Tổng sản lượng quốc gia", "Tỷ lệ thất nghiệp", "Mức lạm phát", "A", "easy"),
    ("Phương pháp tính GDP theo chi tiêu gồm những thành phần nào?", "Tiêu dùng, đầu tư, chi tiêu chính phủ và xuất khẩu ròng", "Lương, lãi, tiền thuê, lợi nhuận", "Nông nghiệp, công nghiệp, dịch vụ", "Thuế và trợ cấp", "A", "medium"),
    ("Xuất khẩu ròng được tính như thế nào?", "Xuất khẩu trừ nhập khẩu", "Xuất khẩu cộng nhập khẩu", "Nhập khẩu trừ xuất khẩu", "Tổng kim ngạch thương mại", "A", "easy"),
    ("Lạm phát là gì?", "Sự tăng lên của mức giá chung trong nền kinh tế", "Sự tăng giá của một mặt hàng", "Sự giảm sản lượng", "Sự tăng thất nghiệp", "A", "easy"),
    ("Chỉ số nào thường dùng để đo lạm phát?", "Chỉ số giá tiêu dùng CPI", "GDP thực tế", "Tỷ lệ thất nghiệp", "Cán cân thương mại", "A", "easy"),
    ("Lạm phát do cầu kéo xảy ra khi nào?", "Khi tổng cầu tăng vượt khả năng cung ứng của nền kinh tế", "Khi chi phí sản xuất tăng", "Khi sản lượng giảm", "Khi tiền lương giảm", "A", "medium"),
    ("Lạm phát do chi phí đẩy xảy ra khi nào?", "Khi chi phí đầu vào như nguyên liệu, tiền lương tăng", "Khi tổng cầu tăng mạnh", "Khi cung tiền giảm", "Khi xuất khẩu tăng", "A", "medium"),
    ("Tác hại của lạm phát cao là gì?", "Làm giảm sức mua đồng tiền, méo mó phân bổ nguồn lực", "Tăng thu nhập thực tế", "Khuyến khích tiết kiệm", "Ổn định kinh tế", "A", "easy"),
    ("Giảm phát (deflation) là hiện tượng gì?", "Mức giá chung giảm liên tục", "Lạm phát giảm tốc", "Sản lượng tăng", "Thất nghiệp giảm", "A", "medium"),
    ("Thất nghiệp được định nghĩa là gì?", "Người trong độ tuổi lao động, có khả năng và mong muốn làm việc nhưng chưa có việc làm", "Người không đi làm", "Người đã nghỉ hưu", "Học sinh sinh viên", "A", "easy"),
    ("Thất nghiệp tự nhiên bao gồm loại nào?", "Thất nghiệp tạm thời và thất nghiệp cơ cấu", "Thất nghiệp chu kỳ", "Thất nghiệp do khủng hoảng", "Thất nghiệp toàn phần", "A", "hard"),
    ("Thất nghiệp chu kỳ xảy ra do nguyên nhân gì?", "Suy thoái kinh tế làm tổng cầu giảm", "Người lao động chuyển việc", "Thay đổi cơ cấu ngành", "Công nghệ mới", "A", "medium"),
    ("Đường Phillips mô tả mối quan hệ giữa hai yếu tố nào?", "Lạm phát và thất nghiệp", "GDP và dân số", "Lãi suất và tỷ giá", "Thuế và chi tiêu", "A", "hard"),
    ("Chính sách tài khóa do cơ quan nào thực hiện?", "Chính phủ", "Ngân hàng trung ương", "Doanh nghiệp nhà nước", "Tổ chức quốc tế", "A", "easy"),
    ("Công cụ của chính sách tài khóa là gì?", "Thuế và chi tiêu công", "Lãi suất và cung tiền", "Tỷ giá hối đoái", "Hạn ngạch xuất nhập khẩu", "A", "easy"),
    ("Chính sách tài khóa mở rộng gồm biện pháp nào?", "Tăng chi tiêu công hoặc giảm thuế", "Giảm chi tiêu và tăng thuế", "Tăng lãi suất", "Giảm cung tiền", "A", "medium"),
    ("Chính sách tài khóa mở rộng được áp dụng khi nào?", "Khi nền kinh tế suy thoái, thất nghiệp cao", "Khi lạm phát quá cao", "Khi kinh tế tăng trưởng nóng", "Khi ngân sách bội thu lớn", "A", "medium"),
    ("Chính sách tiền tệ do cơ quan nào thực hiện?", "Ngân hàng trung ương", "Quốc hội", "Bộ Tài chính", "Doanh nghiệp", "A", "easy"),
    ("Công cụ của chính sách tiền tệ gồm những gì?", "Lãi suất, tỷ lệ dự trữ bắt buộc và nghiệp vụ thị trường mở", "Thuế và chi tiêu công", "Hạn ngạch nhập khẩu", "Trợ cấp doanh nghiệp", "A", "medium"),
    ("Chính sách tiền tệ thắt chặt có tác dụng gì?", "Giảm cung tiền, kiềm chế lạm phát", "Tăng cung tiền kích thích kinh tế", "Giảm thuế cho doanh nghiệp", "Tăng chi tiêu chính phủ", "A", "medium"),
    ("Khi ngân hàng trung ương tăng lãi suất thì điều gì thường xảy ra?", "Đầu tư và tiêu dùng giảm, lạm phát hạ nhiệt", "Đầu tư tăng mạnh", "Lạm phát tăng", "Cung tiền tăng", "A", "medium"),
    ("Tỷ lệ dự trữ bắt buộc tăng có tác dụng gì?", "Giảm khả năng cho vay của ngân hàng thương mại", "Tăng cung tiền", "Giảm lãi suất", "Tăng lạm phát", "A", "hard"),
    ("Cung tiền M1 bao gồm những thành phần nào?", "Tiền mặt lưu thông và tiền gửi không kỳ hạn", "Chỉ tiền mặt", "Toàn bộ tiền gửi tiết kiệm", "Trái phiếu chính phủ", "A", "hard"),
    ("Tổng cầu (AD) của nền kinh tế gồm những thành phần nào?", "Tiêu dùng, đầu tư, chi tiêu chính phủ và xuất khẩu ròng", "Chỉ tiêu dùng hộ gia đình", "Sản lượng doanh nghiệp", "Cung tiền và lãi suất", "A", "medium"),
    ("Đường tổng cầu có độ dốc như thế nào?", "Dốc xuống từ trái sang phải", "Dốc lên", "Nằm ngang", "Thẳng đứng", "A", "medium"),
    ("Cán cân thương mại thặng dư nghĩa là gì?", "Xuất khẩu lớn hơn nhập khẩu", "Nhập khẩu lớn hơn xuất khẩu", "Ngân sách bội thu", "Dự trữ ngoại hối giảm", "A", "easy"),
    ("Tỷ giá hối đoái là gì?", "Giá của một đồng tiền tính bằng đồng tiền khác", "Lãi suất ngân hàng", "Giá vàng trong nước", "Chỉ số giá tiêu dùng", "A", "easy"),
    ("Khi đồng nội tệ mất giá thì tác động gì tới xuất khẩu?", "Xuất khẩu trở nên rẻ hơn với người nước ngoài, thường tăng", "Xuất khẩu giảm mạnh", "Không ảnh hưởng", "Nhập khẩu rẻ hơn", "A", "medium"),
    ("Chu kỳ kinh tế gồm những giai đoạn nào?", "Mở rộng, đỉnh, suy thoái và đáy", "Tăng và giảm", "Lạm phát và giảm phát", "Cung và cầu", "A", "medium"),
    ("Suy thoái kinh tế thường được định nghĩa là gì?", "GDP thực tế giảm liên tiếp trong hai quý", "Lạm phát tăng cao", "Thất nghiệp dưới 5%", "Xuất khẩu giảm", "A", "medium"),
    ("Nợ công là gì?", "Tổng các khoản nợ của chính phủ", "Nợ của doanh nghiệp", "Nợ của hộ gia đình", "Nợ ngân hàng thương mại", "A", "easy"),
    ("Bội chi ngân sách xảy ra khi nào?", "Chi ngân sách lớn hơn thu ngân sách", "Thu lớn hơn chi", "Thu bằng chi", "Không có thuế", "A", "easy"),
    ("Số nhân chi tiêu phản ánh điều gì?", "Mức tăng sản lượng khi chi tiêu tự định tăng một đơn vị", "Tỷ lệ lạm phát", "Tốc độ quay vòng tiền", "Tỷ lệ thất nghiệp", "A", "hard"),
    ("Đầu tư trong kinh tế vĩ mô bao gồm gì?", "Chi mua tư liệu sản xuất, xây dựng và thay đổi hàng tồn kho", "Mua cổ phiếu trên sàn", "Gửi tiết kiệm ngân hàng", "Mua vàng tích trữ", "A", "hard"),
    ("Tiết kiệm quốc gia có quan hệ thế nào với đầu tư trong nền kinh tế đóng?", "Tiết kiệm bằng đầu tư", "Tiết kiệm luôn lớn hơn", "Không liên quan", "Đầu tư luôn gấp đôi", "A", "hard"),
    ("Tăng trưởng kinh tế được đo bằng chỉ tiêu nào?", "Tốc độ tăng GDP thực tế", "Mức tăng dân số", "Tỷ lệ lạm phát", "Số doanh nghiệp mới", "A", "easy"),
    ("Yếu tố nào quyết định tăng trưởng kinh tế dài hạn?", "Năng suất lao động và tiến bộ công nghệ", "Chi tiêu chính phủ ngắn hạn", "Tỷ giá hối đoái", "Lãi suất tiền gửi", "A", "medium"),
    ("Chỉ số phát triển con người HDI đo lường những yếu tố nào?", "Tuổi thọ, giáo dục và thu nhập", "Chỉ thu nhập bình quân", "Tỷ lệ thất nghiệp", "Mức lạm phát", "A", "medium"),
    ("Hệ số Gini dùng để đo lường điều gì?", "Mức độ bất bình đẳng trong phân phối thu nhập", "Tốc độ tăng trưởng", "Tỷ lệ lạm phát", "Nợ công quốc gia", "A", "medium"),
    ("Ngân hàng trung ương có chức năng nào sau đây?", "Phát hành tiền và điều hành chính sách tiền tệ", "Cho vay tiêu dùng cá nhân", "Kinh doanh bất động sản", "Thu thuế", "A", "easy"),
    ("Nghiệp vụ thị trường mở là gì?", "Ngân hàng trung ương mua bán giấy tờ có giá để điều tiết cung tiền", "Cho vay trực tiếp doanh nghiệp", "Ấn định tỷ giá cố định", "Thu thuế thu nhập", "A", "hard"),
    ("Toàn cầu hóa kinh tế mang lại lợi ích gì?", "Mở rộng thị trường, thu hút đầu tư và chuyển giao công nghệ", "Giảm cạnh tranh", "Tăng rào cản thương mại", "Đóng cửa nền kinh tế", "A", "easy"),
    ("Đầu tư trực tiếp nước ngoài FDI có đặc điểm gì?", "Nhà đầu tư nước ngoài trực tiếp tham gia quản lý hoạt động sản xuất kinh doanh", "Chỉ mua cổ phiếu ngắn hạn", "Là khoản viện trợ không hoàn lại", "Là khoản vay ODA", "A", "medium"),
    ("Lợi thế so sánh trong thương mại quốc tế nghĩa là gì?", "Quốc gia nên chuyên môn hóa sản xuất hàng có chi phí cơ hội thấp hơn", "Sản xuất mọi thứ rẻ hơn nước khác", "Xuất khẩu nhiều hơn nhập khẩu", "Có tài nguyên phong phú nhất", "A", "hard"),
    ("Hàng rào thuế quan có tác dụng gì?", "Hạn chế nhập khẩu, bảo hộ sản xuất trong nước", "Khuyến khích nhập khẩu", "Giảm giá hàng nhập", "Tăng xuất khẩu trực tiếp", "A", "medium"),
    ("Mục tiêu chính của kinh tế vĩ mô là gì?", "Tăng trưởng ổn định, kiểm soát lạm phát và giảm thất nghiệp", "Tối đa lợi nhuận doanh nghiệp", "Tăng giá cổ phiếu", "Giảm dân số", "A", "easy"),
]

KE_TOAN = [
    ("Kế toán là gì?", "Việc thu thập, xử lý và cung cấp thông tin kinh tế tài chính của đơn vị", "Hoạt động bán hàng", "Quản lý nhân sự", "Nghiên cứu thị trường", "A", "easy"),
    ("Phương trình kế toán cơ bản là gì?", "Tài sản = Nợ phải trả + Vốn chủ sở hữu", "Tài sản = Doanh thu - Chi phí", "Vốn = Tài sản + Nợ", "Doanh thu = Chi phí + Lợi nhuận", "A", "easy"),
    ("Tài sản trong kế toán là gì?", "Nguồn lực doanh nghiệp kiểm soát và mang lại lợi ích kinh tế tương lai", "Số tiền doanh nghiệp nợ", "Vốn góp của chủ sở hữu", "Doanh thu bán hàng", "A", "easy"),
    ("Tài sản ngắn hạn bao gồm những khoản nào?", "Tiền, các khoản phải thu, hàng tồn kho", "Nhà xưởng, máy móc", "Bằng phát minh sáng chế", "Đầu tư dài hạn", "A", "easy"),
    ("Tài sản dài hạn gồm những khoản nào?", "Tài sản cố định hữu hình, vô hình và đầu tư dài hạn", "Tiền mặt tại quỹ", "Hàng tồn kho", "Phải thu khách hàng", "A", "easy"),
    ("Nợ phải trả là gì?", "Nghĩa vụ hiện tại doanh nghiệp phải thanh toán", "Tài sản của doanh nghiệp", "Vốn góp của cổ đông", "Lợi nhuận giữ lại", "A", "easy"),
    ("Vốn chủ sở hữu được xác định thế nào?", "Tài sản trừ nợ phải trả", "Tài sản cộng nợ phải trả", "Doanh thu trừ chi phí", "Tổng tài sản", "A", "medium"),
    ("Nguyên tắc ghi sổ kép nghĩa là gì?", "Mỗi nghiệp vụ được ghi ít nhất vào hai tài khoản, tổng Nợ bằng tổng Có", "Ghi hai lần vào cùng một tài khoản", "Ghi sổ hai lần trong tháng", "Có hai kế toán cùng ghi", "A", "medium"),
    ("Tài khoản tài sản tăng thì ghi vào bên nào?", "Bên Nợ", "Bên Có", "Cả hai bên", "Không ghi", "A", "medium"),
    ("Tài khoản nợ phải trả tăng thì ghi vào bên nào?", "Bên Có", "Bên Nợ", "Cả hai bên", "Không ghi", "A", "medium"),
    ("Tài khoản doanh thu tăng thì ghi vào bên nào?", "Bên Có", "Bên Nợ", "Tùy trường hợp", "Không ghi sổ", "A", "medium"),
    ("Tài khoản chi phí tăng thì ghi vào bên nào?", "Bên Nợ", "Bên Có", "Cả hai bên", "Không ghi", "A", "medium"),
    ("Định khoản kế toán là gì?", "Xác định tài khoản ghi Nợ, tài khoản ghi Có và số tiền cho một nghiệp vụ", "Kiểm kê hàng hóa", "Lập báo cáo tài chính", "Tính giá thành", "A", "easy"),
    ("Báo cáo tài chính cơ bản gồm những báo cáo nào?", "Bảng cân đối kế toán, báo cáo kết quả kinh doanh, báo cáo lưu chuyển tiền tệ và thuyết minh", "Chỉ bảng cân đối kế toán", "Chỉ báo cáo doanh thu", "Sổ cái và sổ nhật ký", "A", "medium"),
    ("Bảng cân đối kế toán phản ánh điều gì?", "Tình hình tài sản và nguồn vốn tại một thời điểm", "Kết quả kinh doanh trong kỳ", "Dòng tiền vào ra", "Kế hoạch kinh doanh", "A", "medium"),
    ("Báo cáo kết quả hoạt động kinh doanh phản ánh điều gì?", "Doanh thu, chi phí và lợi nhuận trong một kỳ", "Tài sản tại thời điểm", "Số dư tiền mặt", "Danh sách khách hàng", "A", "medium"),
    ("Nguyên tắc cơ sở dồn tích nghĩa là gì?", "Ghi nhận doanh thu chi phí khi phát sinh, không phụ thuộc thời điểm thu chi tiền", "Chỉ ghi khi thu được tiền", "Ghi vào cuối năm", "Ghi theo giá thị trường", "A", "hard"),
    ("Nguyên tắc thận trọng trong kế toán yêu cầu gì?", "Không đánh giá cao hơn giá trị tài sản và thu nhập, không thấp hơn nợ phải trả và chi phí", "Ghi nhận mọi khoản lãi dự kiến", "Bỏ qua các khoản lỗ nhỏ", "Luôn ghi giá trị cao nhất", "A", "hard"),
    ("Nguyên tắc phù hợp trong kế toán nghĩa là gì?", "Chi phí phải được ghi nhận phù hợp với doanh thu tạo ra trong cùng kỳ", "Số liệu phải khớp với ngân hàng", "Tài sản phải bằng nguồn vốn", "Doanh thu bằng chi phí", "A", "hard"),
    ("Khấu hao tài sản cố định là gì?", "Phân bổ dần giá trị tài sản cố định vào chi phí trong thời gian sử dụng", "Bán tài sản cố định", "Sửa chữa tài sản", "Mua mới tài sản", "A", "medium"),
    ("Phương pháp khấu hao đường thẳng có đặc điểm gì?", "Mức khấu hao bằng nhau qua các năm sử dụng", "Khấu hao nhanh những năm đầu", "Khấu hao theo sản lượng", "Không khấu hao", "A", "medium"),
    ("Hàng tồn kho bao gồm những gì?", "Nguyên vật liệu, sản phẩm dở dang và thành phẩm", "Tiền gửi ngân hàng", "Tài sản cố định", "Nợ phải thu", "A", "easy"),
    ("Phương pháp tính giá xuất kho FIFO nghĩa là gì?", "Hàng nhập trước xuất trước", "Hàng nhập sau xuất trước", "Tính theo giá bình quân", "Tính theo giá thị trường", "A", "medium"),
    ("Doanh thu được ghi nhận khi nào?", "Khi chuyển giao phần lớn rủi ro và lợi ích, xác định được giá trị", "Khi ký hợp đồng", "Khi nhận đơn hàng", "Khi sản xuất xong", "A", "hard"),
    ("Lợi nhuận gộp được tính như thế nào?", "Doanh thu thuần trừ giá vốn hàng bán", "Doanh thu trừ toàn bộ chi phí", "Lợi nhuận sau thuế", "Doanh thu cộng thu nhập khác", "A", "medium"),
    ("Lợi nhuận sau thuế là gì?", "Lợi nhuận trước thuế trừ thuế thu nhập doanh nghiệp", "Doanh thu trừ giá vốn", "Lợi nhuận gộp", "Tổng doanh thu", "A", "easy"),
    ("Giá vốn hàng bán phản ánh điều gì?", "Chi phí trực tiếp tạo ra sản phẩm đã bán", "Chi phí bán hàng và quản lý", "Chi phí lãi vay", "Thuế phải nộp", "A", "medium"),
    ("Chi phí bán hàng gồm những khoản nào?", "Chi phí quảng cáo, vận chuyển, lương nhân viên bán hàng", "Chi phí nguyên vật liệu trực tiếp", "Lương công nhân sản xuất", "Khấu hao nhà xưởng sản xuất", "A", "medium"),
    ("Sổ nhật ký chung dùng để làm gì?", "Ghi chép các nghiệp vụ kinh tế phát sinh theo trình tự thời gian", "Tổng hợp số dư cuối kỳ", "Lập báo cáo tài chính", "Theo dõi khách hàng", "A", "medium"),
    ("Sổ cái dùng để làm gì?", "Ghi chép và tổng hợp theo từng tài khoản kế toán", "Ghi theo thứ tự thời gian", "Lưu hóa đơn chứng từ", "Theo dõi tồn kho chi tiết", "A", "medium"),
    ("Chứng từ kế toán có vai trò gì?", "Là bằng chứng chứng minh nghiệp vụ kinh tế đã phát sinh", "Là báo cáo gửi cơ quan thuế", "Là kế hoạch kinh doanh", "Là hợp đồng lao động", "A", "easy"),
    ("Kiểm kê tài sản nhằm mục đích gì?", "Đối chiếu số liệu sổ sách với thực tế", "Tăng giá trị tài sản", "Bán bớt tài sản", "Tính thuế", "A", "easy"),
    ("Bảng cân đối kế toán luôn thỏa mãn điều kiện gì?", "Tổng tài sản bằng tổng nguồn vốn", "Doanh thu bằng chi phí", "Tiền mặt bằng tiền gửi", "Nợ bằng vốn chủ sở hữu", "A", "easy"),
    ("Kỳ kế toán năm ở Việt Nam thường là khoảng thời gian nào?", "Từ 01/01 đến 31/12", "Từ 01/04 đến 31/03", "Từ 01/07 đến 30/06", "Tùy doanh nghiệp chọn tự do", "A", "easy"),
    ("Thuế giá trị gia tăng (GTGT) được tính trên cơ sở nào?", "Phần giá trị tăng thêm của hàng hóa dịch vụ", "Toàn bộ doanh thu", "Lợi nhuận trước thuế", "Tổng tài sản", "A", "medium"),
    ("Thuế GTGT đầu vào được khấu trừ khi nào?", "Khi có hóa đơn hợp lệ và phục vụ hoạt động chịu thuế", "Khi doanh nghiệp có lãi", "Khi thanh toán bằng tiền mặt", "Trong mọi trường hợp", "A", "hard"),
    ("Báo cáo lưu chuyển tiền tệ chia thành mấy hoạt động?", "Ba hoạt động: kinh doanh, đầu tư và tài chính", "Hai hoạt động", "Bốn hoạt động", "Một hoạt động duy nhất", "A", "medium"),
    ("Dòng tiền từ hoạt động kinh doanh phản ánh điều gì?", "Tiền thu chi từ hoạt động sản xuất kinh doanh chính", "Tiền mua bán tài sản cố định", "Tiền vay và trả nợ", "Tiền góp vốn của cổ đông", "A", "medium"),
    ("Hệ số thanh toán hiện hành được tính thế nào?", "Tài sản ngắn hạn chia nợ ngắn hạn", "Tổng tài sản chia tổng nợ", "Lợi nhuận chia doanh thu", "Doanh thu chia tài sản", "A", "hard"),
    ("Tỷ suất lợi nhuận trên doanh thu (ROS) phản ánh điều gì?", "Một đồng doanh thu tạo ra bao nhiêu đồng lợi nhuận", "Hiệu quả sử dụng tài sản", "Khả năng thanh toán", "Cơ cấu vốn", "A", "medium"),
    ("Tỷ suất sinh lời trên tài sản (ROA) được tính thế nào?", "Lợi nhuận sau thuế chia tổng tài sản bình quân", "Lợi nhuận chia doanh thu", "Doanh thu chia tài sản", "Nợ chia vốn chủ", "A", "hard"),
    ("Kế toán tài chính khác kế toán quản trị ở điểm nào?", "Kế toán tài chính phục vụ đối tượng bên ngoài, kế toán quản trị phục vụ nội bộ", "Không có khác biệt", "Kế toán quản trị bắt buộc theo luật", "Kế toán tài chính chỉ dùng nội bộ", "A", "medium"),
    ("Điểm hòa vốn trong kế toán quản trị là gì?", "Mức sản lượng mà doanh thu vừa đủ bù đắp tổng chi phí", "Mức lợi nhuận cao nhất", "Mức chi phí thấp nhất", "Mức doanh thu tối đa", "A", "medium"),
    ("Chi phí trực tiếp là gì?", "Chi phí liên quan trực tiếp và tính thẳng vào sản phẩm", "Chi phí quản lý chung", "Chi phí không xác định được", "Chi phí bán hàng", "A", "medium"),
    ("Chi phí gián tiếp cần được xử lý thế nào?", "Phân bổ cho các đối tượng theo tiêu thức hợp lý", "Bỏ qua không tính", "Tính hết vào một sản phẩm", "Ghi giảm doanh thu", "A", "medium"),
    ("Giá thành sản phẩm bao gồm những khoản mục nào?", "Chi phí nguyên vật liệu trực tiếp, nhân công trực tiếp và sản xuất chung", "Chi phí bán hàng và quản lý", "Chi phí tài chính", "Thuế thu nhập doanh nghiệp", "A", "medium"),
    ("Kiểm toán độc lập có mục đích gì?", "Đưa ra ý kiến về tính trung thực hợp lý của báo cáo tài chính", "Lập báo cáo tài chính cho doanh nghiệp", "Tính thuế phải nộp", "Quản lý quỹ tiền mặt", "A", "medium"),
    ("Gian lận trong kế toán thường biểu hiện thế nào?", "Cố ý ghi sai số liệu nhằm che giấu tình hình thực tế", "Nhầm lẫn khi tính toán", "Ghi chép chậm trễ", "Thiếu chứng từ do thất lạc", "A", "easy"),
    ("Chuẩn mực kế toán có vai trò gì?", "Quy định nguyên tắc và phương pháp kế toán thống nhất", "Quy định mức lương kế toán", "Xác định thuế suất", "Cấp phép kinh doanh", "A", "easy"),
    ("Đạo đức nghề nghiệp kế toán đòi hỏi phẩm chất nào?", "Trung thực, khách quan, độc lập và bảo mật", "Linh hoạt theo yêu cầu lãnh đạo", "Ưu tiên lợi ích doanh nghiệp", "Chỉ cần đúng hạn", "A", "easy"),
]

MARKETING = [
    ("Marketing là gì?", "Hoạt động tạo ra, truyền thông và cung cấp giá trị cho khách hàng", "Chỉ là quảng cáo sản phẩm", "Hoạt động bán hàng trực tiếp", "Nghiên cứu sản xuất", "A", "easy"),
    ("Marketing mix 4P gồm những yếu tố nào?", "Product, Price, Place, Promotion", "People, Process, Physical, Product", "Plan, Post, Price, Place", "Product, Profit, People, Place", "A", "easy"),
    ("Chữ P đầu tiên trong 4P là gì?", "Sản phẩm", "Giá cả", "Phân phối", "Xúc tiến", "A", "easy"),
    ("Mô hình 7P bổ sung thêm những yếu tố nào so với 4P?", "People, Process, Physical Evidence", "Profit, Plan, Position", "Promotion, Place, Price", "Product, People, Profit", "A", "medium"),
    ("Nhu cầu (needs) khác mong muốn (wants) ở điểm nào?", "Nhu cầu là đòi hỏi cơ bản, mong muốn là hình thức cụ thể của nhu cầu", "Hai khái niệm giống nhau", "Mong muốn cơ bản hơn nhu cầu", "Nhu cầu do quảng cáo tạo ra", "A", "medium"),
    ("Phân khúc thị trường là gì?", "Chia thị trường thành các nhóm khách hàng có đặc điểm tương đồng", "Chia sản phẩm thành nhiều loại", "Phân chia lãnh thổ bán hàng", "Chia nhỏ giá bán", "A", "easy"),
    ("Tiêu thức nào thường dùng để phân khúc thị trường?", "Địa lý, nhân khẩu học, tâm lý và hành vi", "Chỉ theo độ tuổi", "Chỉ theo thu nhập", "Chỉ theo khu vực", "A", "medium"),
    ("Thị trường mục tiêu là gì?", "Nhóm khách hàng doanh nghiệp quyết định tập trung phục vụ", "Toàn bộ dân số", "Đối thủ cạnh tranh chính", "Nhà cung cấp nguyên liệu", "A", "easy"),
    ("Định vị sản phẩm nghĩa là gì?", "Tạo hình ảnh khác biệt về sản phẩm trong tâm trí khách hàng", "Đặt sản phẩm ở vị trí đẹp trên kệ", "Xác định địa điểm bán hàng", "Định giá sản phẩm", "A", "medium"),
    ("Chu kỳ sống của sản phẩm gồm mấy giai đoạn?", "Bốn giai đoạn: giới thiệu, tăng trưởng, bão hòa, suy thoái", "Hai giai đoạn", "Ba giai đoạn", "Năm giai đoạn", "A", "medium"),
    ("Ở giai đoạn giới thiệu, doanh nghiệp thường gặp tình trạng gì?", "Doanh thu thấp, chi phí marketing cao, lợi nhuận âm hoặc thấp", "Lợi nhuận cao nhất", "Doanh thu bão hòa", "Cạnh tranh gay gắt nhất", "A", "medium"),
    ("Giai đoạn bão hòa có đặc điểm gì?", "Doanh thu tăng chậm hoặc ổn định, cạnh tranh gay gắt", "Doanh thu tăng vọt", "Ít đối thủ cạnh tranh", "Chi phí marketing thấp nhất", "A", "medium"),
    ("Chiến lược giá hớt váng (skimming) áp dụng khi nào?", "Định giá cao khi mới tung sản phẩm độc đáo ra thị trường", "Định giá thấp để chiếm thị phần", "Giá bằng đối thủ", "Bán dưới giá vốn", "A", "hard"),
    ("Chiến lược giá thâm nhập (penetration) nhằm mục đích gì?", "Định giá thấp để nhanh chóng chiếm lĩnh thị phần", "Tối đa lợi nhuận ngay lập tức", "Tạo hình ảnh cao cấp", "Giảm sản lượng", "A", "hard"),
    ("Kênh phân phối trực tiếp có đặc điểm gì?", "Doanh nghiệp bán thẳng cho người tiêu dùng không qua trung gian", "Qua nhiều cấp trung gian", "Chỉ bán sỉ", "Chỉ xuất khẩu", "A", "easy"),
    ("Vai trò của trung gian phân phối là gì?", "Giảm số lần giao dịch, đưa hàng tới người tiêu dùng hiệu quả hơn", "Làm tăng giá sản phẩm vô ích", "Chỉ để lưu kho", "Không có vai trò gì", "A", "medium"),
    ("Xúc tiến hỗn hợp bao gồm những công cụ nào?", "Quảng cáo, khuyến mại, quan hệ công chúng, bán hàng cá nhân, marketing trực tiếp", "Chỉ quảng cáo", "Chỉ khuyến mại", "Chỉ bán hàng cá nhân", "A", "medium"),
    ("Quảng cáo khác quan hệ công chúng ở điểm nào?", "Quảng cáo phải trả tiền và kiểm soát nội dung, PR thường không trả tiền trực tiếp", "PR đắt hơn quảng cáo", "Hai hoạt động giống nhau", "Quảng cáo không tốn chi phí", "A", "medium"),
    ("Nghiên cứu thị trường nhằm mục đích gì?", "Thu thập thông tin để ra quyết định marketing chính xác", "Tăng doanh số ngay lập tức", "Giảm chi phí sản xuất", "Tuyển dụng nhân sự", "A", "easy"),
    ("Dữ liệu sơ cấp trong nghiên cứu thị trường là gì?", "Dữ liệu tự thu thập lần đầu cho mục đích nghiên cứu cụ thể", "Dữ liệu có sẵn từ nguồn khác", "Dữ liệu thống kê của nhà nước", "Báo cáo ngành đã công bố", "A", "medium"),
    ("Dữ liệu thứ cấp có ưu điểm gì?", "Chi phí thấp và thu thập nhanh", "Luôn chính xác tuyệt đối", "Phù hợp hoàn hảo mọi mục tiêu", "Không ai khác có được", "A", "medium"),
    ("Hành vi mua của người tiêu dùng chịu ảnh hưởng bởi yếu tố nào?", "Văn hóa, xã hội, cá nhân và tâm lý", "Chỉ giá cả sản phẩm", "Chỉ quảng cáo", "Chỉ thu nhập", "A", "medium"),
    ("Quá trình ra quyết định mua gồm mấy bước?", "Năm bước từ nhận biết nhu cầu đến hành vi sau mua", "Hai bước", "Ba bước", "Bảy bước", "A", "medium"),
    ("Thương hiệu (brand) là gì?", "Tập hợp dấu hiệu và cảm nhận giúp phân biệt sản phẩm với đối thủ", "Chỉ là logo công ty", "Tên đăng ký kinh doanh", "Bằng sáng chế", "A", "easy"),
    ("Giá trị thương hiệu mang lại lợi ích gì?", "Tạo lòng trung thành, cho phép định giá cao hơn", "Giảm chi phí sản xuất", "Tăng số lượng nhân viên", "Giảm thuế phải nộp", "A", "medium"),
    ("SWOT phân tích những yếu tố nào?", "Điểm mạnh, điểm yếu, cơ hội và thách thức", "Sản phẩm, giá, phân phối, xúc tiến", "Doanh thu, chi phí, lợi nhuận, thuế", "Khách hàng, đối thủ, nhà cung cấp, nhân viên", "A", "easy"),
    ("Trong SWOT, điểm mạnh và điểm yếu thuộc yếu tố nào?", "Bên trong doanh nghiệp", "Bên ngoài môi trường", "Của đối thủ cạnh tranh", "Của khách hàng", "A", "medium"),
    ("Cơ hội và thách thức trong SWOT thuộc yếu tố nào?", "Môi trường bên ngoài", "Nội bộ doanh nghiệp", "Chỉ liên quan tài chính", "Do nhân viên tạo ra", "A", "medium"),
    ("Marketing số (digital marketing) bao gồm hoạt động nào?", "SEO, quảng cáo trực tuyến, mạng xã hội, email marketing", "Chỉ phát tờ rơi", "Chỉ quảng cáo truyền hình", "Chỉ trưng bày cửa hàng", "A", "easy"),
    ("SEO là gì?", "Tối ưu hóa website để tăng thứ hạng trên công cụ tìm kiếm", "Quảng cáo trả tiền theo click", "Gửi email hàng loạt", "Bán hàng qua điện thoại", "A", "easy"),
    ("Content marketing tập trung vào điều gì?", "Tạo nội dung giá trị để thu hút và giữ chân khách hàng", "Giảm giá liên tục", "Quảng cáo trực tiếp sản phẩm", "Gọi điện chào hàng", "A", "easy"),
    ("Tỷ lệ chuyển đổi (conversion rate) đo lường điều gì?", "Tỷ lệ khách truy cập thực hiện hành động mong muốn", "Số lượt xem trang", "Chi phí quảng cáo", "Số nhân viên bán hàng", "A", "medium"),
    ("CRM là gì?", "Hệ thống quản trị quan hệ khách hàng", "Phần mềm kế toán", "Hệ thống quản lý kho", "Công cụ thiết kế đồ họa", "A", "easy"),
    ("Chi phí giữ chân khách hàng cũ so với tìm khách hàng mới thế nào?", "Thường thấp hơn nhiều", "Cao hơn nhiều", "Bằng nhau", "Không thể so sánh", "A", "medium"),
    ("Marketing B2B khác B2C ở điểm nào?", "B2B bán cho tổ chức, quyết định mua phức tạp và lý trí hơn", "B2B bán cho cá nhân", "B2C có giá trị đơn hàng lớn hơn", "Không có khác biệt", "A", "medium"),
    ("Chiến lược khác biệt hóa nhằm mục đích gì?", "Tạo sản phẩm độc đáo mà đối thủ khó sao chép", "Bán giá rẻ nhất thị trường", "Sao chép sản phẩm dẫn đầu", "Giảm chất lượng để hạ giá", "A", "medium"),
    ("Chiến lược dẫn đầu về chi phí có đặc điểm gì?", "Đạt chi phí thấp nhất ngành để cạnh tranh về giá", "Tạo sản phẩm cao cấp nhất", "Tập trung một phân khúc hẹp", "Đa dạng hóa sản phẩm", "A", "medium"),
    ("Mô hình 5 áp lực cạnh tranh của Porter gồm những yếu tố nào?", "Đối thủ hiện tại, đối thủ tiềm năng, sản phẩm thay thế, quyền lực nhà cung cấp và khách hàng", "Sản phẩm, giá, phân phối, xúc tiến, con người", "Điểm mạnh, yếu, cơ hội, thách thức, rủi ro", "Kinh tế, chính trị, xã hội, công nghệ, môi trường", "A", "hard"),
    ("Mô hình PEST phân tích môi trường vĩ mô gồm yếu tố nào?", "Chính trị, kinh tế, xã hội và công nghệ", "Sản phẩm, giá, phân phối, xúc tiến", "Điểm mạnh và điểm yếu", "Nhà cung cấp và khách hàng", "A", "medium"),
    ("Khuyến mại có tác dụng chủ yếu gì?", "Kích thích mua hàng trong ngắn hạn", "Xây dựng thương hiệu dài hạn", "Giảm chi phí sản xuất", "Tăng chất lượng sản phẩm", "A", "easy"),
    ("Lạm dụng khuyến mại có thể gây hậu quả gì?", "Làm giảm giá trị thương hiệu, khách hàng chỉ mua khi giảm giá", "Tăng lợi nhuận bền vững", "Nâng cao hình ảnh cao cấp", "Giảm cạnh tranh", "A", "hard"),
    ("Truyền miệng (word of mouth) có ưu điểm gì?", "Độ tin cậy cao và chi phí thấp", "Kiểm soát nội dung dễ dàng", "Luôn tích cực", "Tốn kém nhất", "A", "medium"),
    ("Marketing đạo đức đòi hỏi doanh nghiệp làm gì?", "Trung thực trong quảng cáo, tôn trọng quyền lợi người tiêu dùng", "Tối đa lợi nhuận bằng mọi giá", "Phóng đại công dụng sản phẩm", "Che giấu khuyết điểm sản phẩm", "A", "easy"),
    ("Sản phẩm cốt lõi trong ba cấp độ sản phẩm là gì?", "Lợi ích cơ bản mà khách hàng thực sự tìm kiếm", "Bao bì và nhãn hiệu", "Dịch vụ bảo hành", "Giá bán sản phẩm", "A", "hard"),
    ("Bao bì sản phẩm có chức năng nào?", "Bảo vệ, thông tin và thu hút khách hàng", "Chỉ để bảo vệ hàng hóa", "Chỉ để tăng giá bán", "Không có chức năng marketing", "A", "easy"),
    ("Sự hài lòng của khách hàng phụ thuộc vào điều gì?", "So sánh giữa kỳ vọng và cảm nhận thực tế về sản phẩm", "Chỉ giá bán", "Chỉ quảng cáo", "Chỉ thương hiệu", "A", "medium"),
    ("Khách hàng trung thành mang lại lợi ích gì?", "Mua lặp lại, giới thiệu người khác và ít nhạy cảm về giá", "Luôn đòi giảm giá", "Chi phí phục vụ cao hơn", "Không có lợi ích rõ ràng", "A", "easy"),
    ("Nghiên cứu định tính trong marketing thường dùng phương pháp nào?", "Phỏng vấn sâu và thảo luận nhóm", "Khảo sát bảng hỏi số lượng lớn", "Phân tích thống kê hồi quy", "Đo lường doanh số", "A", "medium"),
    ("Mục tiêu marketing nên được đặt theo nguyên tắc nào?", "SMART - cụ thể, đo lường được, khả thi, phù hợp, có thời hạn", "Càng cao càng tốt", "Do cảm tính lãnh đạo", "Sao chép đối thủ", "A", "easy"),
    ("Kế hoạch marketing thường bao gồm nội dung nào?", "Phân tích tình hình, mục tiêu, chiến lược, chương trình hành động và ngân sách", "Chỉ danh sách quảng cáo", "Chỉ bảng giá sản phẩm", "Chỉ sơ đồ tổ chức", "A", "medium"),
]

QUAN_TRI_HOC = [
    ("Quản trị là gì?", "Quá trình hoạch định, tổ chức, lãnh đạo và kiểm soát để đạt mục tiêu", "Việc ra lệnh cho nhân viên", "Hoạt động kế toán tài chính", "Công việc bán hàng", "A", "easy"),
    ("Bốn chức năng cơ bản của quản trị là gì?", "Hoạch định, tổ chức, lãnh đạo và kiểm soát", "Mua, bán, sản xuất, phân phối", "Tuyển dụng, đào tạo, đánh giá, sa thải", "Lập kế hoạch, thực hiện, báo cáo, tổng kết", "A", "easy"),
    ("Hoạch định là chức năng gì?", "Xác định mục tiêu và cách thức đạt được mục tiêu", "Phân công công việc", "Động viên nhân viên", "Đo lường kết quả", "A", "easy"),
    ("Chức năng tổ chức trong quản trị nghĩa là gì?", "Phân công công việc, sắp xếp nguồn lực và thiết lập cơ cấu", "Đặt ra mục tiêu", "Kiểm tra kết quả", "Tuyển dụng nhân sự", "A", "easy"),
    ("Chức năng kiểm soát nhằm mục đích gì?", "Đo lường kết quả và điều chỉnh sai lệch so với kế hoạch", "Phân công nhiệm vụ", "Xác định mục tiêu", "Tuyển thêm nhân viên", "A", "easy"),
    ("Nhà quản trị cấp cao thường tập trung vào công việc gì?", "Xây dựng chiến lược và định hướng dài hạn", "Giám sát công nhân trực tiếp", "Xử lý công việc hàng ngày", "Ghi chép sổ sách", "A", "easy"),
    ("Nhà quản trị cấp cơ sở có nhiệm vụ chính là gì?", "Trực tiếp giám sát và điều hành người thực hiện công việc", "Hoạch định chiến lược công ty", "Đàm phán với đối tác lớn", "Quyết định cơ cấu tổ chức", "A", "medium"),
    ("Kỹ năng nào quan trọng nhất với nhà quản trị cấp cao?", "Kỹ năng tư duy chiến lược", "Kỹ năng kỹ thuật chuyên môn", "Kỹ năng vận hành máy móc", "Kỹ năng ghi chép", "A", "medium"),
    ("Kỹ năng nhân sự quan trọng với cấp quản trị nào?", "Mọi cấp quản trị", "Chỉ cấp cao", "Chỉ cấp cơ sở", "Không cấp nào", "A", "medium"),
    ("Thuyết quản trị khoa học gắn với tên tuổi ai?", "Frederick Taylor", "Henri Fayol", "Max Weber", "Elton Mayo", "A", "medium"),
    ("Thuyết quản trị khoa học của Taylor nhấn mạnh điều gì?", "Chuẩn hóa thao tác và tăng năng suất lao động", "Quan hệ con người trong tổ chức", "Cơ cấu hành chính quan liêu", "Trách nhiệm xã hội", "A", "medium"),
    ("Henri Fayol đóng góp gì cho quản trị học?", "Đưa ra các chức năng và nguyên tắc quản trị tổng quát", "Nghiên cứu thao tác lao động", "Thí nghiệm Hawthorne", "Lý thuyết nhu cầu", "A", "medium"),
    ("Thuyết quan hệ con người ra đời từ nghiên cứu nào?", "Thí nghiệm Hawthorne của Elton Mayo", "Nghiên cứu thời gian thao tác của Taylor", "Mô hình quan liêu của Weber", "Lý thuyết hệ thống", "A", "hard"),
    ("Tháp nhu cầu Maslow có mấy bậc?", "Năm bậc", "Ba bậc", "Bốn bậc", "Bảy bậc", "A", "easy"),
    ("Nhu cầu ở đáy tháp Maslow là gì?", "Nhu cầu sinh lý cơ bản", "Nhu cầu an toàn", "Nhu cầu được tôn trọng", "Nhu cầu tự thể hiện", "A", "easy"),
    ("Nhu cầu ở đỉnh tháp Maslow là gì?", "Nhu cầu tự thể hiện bản thân", "Nhu cầu xã hội", "Nhu cầu an toàn", "Nhu cầu sinh lý", "A", "easy"),
    ("Thuyết hai yếu tố của Herzberg phân biệt điều gì?", "Yếu tố duy trì và yếu tố động viên", "Nhu cầu vật chất và tinh thần", "Lãnh đạo và quản lý", "Mục tiêu ngắn hạn và dài hạn", "A", "hard"),
    ("Theo Herzberg, tiền lương thuộc nhóm yếu tố nào?", "Yếu tố duy trì", "Yếu tố động viên", "Yếu tố lãnh đạo", "Yếu tố tổ chức", "A", "hard"),
    ("Thuyết X và thuyết Y của McGregor nói về điều gì?", "Hai quan niệm trái ngược về bản chất người lao động", "Hai mô hình cơ cấu tổ chức", "Hai phương pháp kiểm soát", "Hai chiến lược cạnh tranh", "A", "medium"),
    ("Theo thuyết Y, người lao động được nhìn nhận thế nào?", "Chủ động, sáng tạo và sẵn sàng nhận trách nhiệm", "Lười biếng, cần bị giám sát chặt", "Chỉ quan tâm tiền lương", "Không có tham vọng", "A", "medium"),
    ("Cơ cấu tổ chức trực tuyến có ưu điểm gì?", "Đơn giản, quyền hạn trách nhiệm rõ ràng", "Tận dụng chuyên gia tối đa", "Linh hoạt cao nhất", "Phù hợp doanh nghiệp rất lớn", "A", "medium"),
    ("Cơ cấu tổ chức chức năng có đặc điểm gì?", "Nhóm theo chuyên môn, tận dụng chuyên gia nhưng dễ thiếu phối hợp", "Mỗi người một cấp trên duy nhất", "Không có phòng ban", "Phù hợp mọi quy mô", "A", "medium"),
    ("Cơ cấu ma trận có nhược điểm gì?", "Nhân viên chịu sự chỉ đạo của nhiều cấp trên gây xung đột", "Quá đơn giản", "Không tận dụng được chuyên gia", "Chi phí thấp nhất", "A", "hard"),
    ("Tầm hạn quản trị là gì?", "Số lượng cấp dưới mà một nhà quản trị có thể giám sát hiệu quả", "Phạm vi địa lý hoạt động", "Thời gian làm việc", "Ngân sách được cấp", "A", "medium"),
    ("Tầm hạn quản trị rộng dẫn tới điều gì?", "Ít cấp quản lý, tổ chức phẳng hơn", "Nhiều cấp quản lý", "Tổ chức cao và hẹp", "Chi phí quản lý tăng", "A", "hard"),
    ("Ủy quyền trong quản trị là gì?", "Giao quyền hạn và trách nhiệm cho cấp dưới thực hiện công việc", "Từ bỏ hoàn toàn trách nhiệm", "Chuyển việc khó cho người khác", "Tăng cường kiểm soát", "A", "medium"),
    ("Nguyên tắc thống nhất chỉ huy nghĩa là gì?", "Mỗi cấp dưới chỉ nhận lệnh từ một cấp trên trực tiếp", "Mọi quyết định do một người ban hành", "Nhân viên tự quyết định", "Chỉ huy theo nhóm", "A", "medium"),
    ("Ra quyết định trong điều kiện rủi ro nghĩa là gì?", "Biết được xác suất xảy ra của các kết quả", "Biết chắc chắn kết quả", "Hoàn toàn không có thông tin", "Không cần cân nhắc", "A", "hard"),
    ("Quá trình ra quyết định hợp lý bắt đầu bằng bước nào?", "Xác định vấn đề cần giải quyết", "Chọn phương án", "Thực hiện quyết định", "Đánh giá kết quả", "A", "medium"),
    ("Lãnh đạo khác quản lý ở điểm nào?", "Lãnh đạo tạo tầm nhìn và truyền cảm hứng, quản lý tổ chức thực hiện", "Hai khái niệm hoàn toàn giống nhau", "Quản lý quan trọng hơn", "Lãnh đạo chỉ có ở cấp cao", "A", "medium"),
    ("Phong cách lãnh đạo độc đoán có đặc điểm gì?", "Nhà lãnh đạo tự ra quyết định, ít tham khảo cấp dưới", "Để cấp dưới tự quyết hoàn toàn", "Luôn biểu quyết tập thể", "Không đưa ra quyết định", "A", "easy"),
    ("Phong cách lãnh đạo dân chủ có ưu điểm gì?", "Khuyến khích tham gia, tăng cam kết của nhân viên", "Ra quyết định nhanh nhất", "Không cần trao đổi", "Phù hợp tình huống khẩn cấp", "A", "medium"),
    ("Phong cách lãnh đạo tự do phù hợp với đối tượng nào?", "Nhân viên có năng lực cao và tự chủ", "Nhân viên mới chưa có kinh nghiệm", "Tình huống khủng hoảng", "Công việc lặp lại đơn giản", "A", "hard"),
    ("Động viên nhân viên hiệu quả cần dựa trên điều gì?", "Hiểu nhu cầu và mong muốn cá nhân của họ", "Chỉ tăng lương", "Chỉ khen thưởng công khai", "Áp dụng chung một cách cho mọi người", "A", "medium"),
    ("Xung đột trong tổ chức nên được xử lý thế nào?", "Nhận diện nguyên nhân và giải quyết theo hướng xây dựng", "Luôn né tránh", "Luôn dùng quyền lực áp đặt", "Bỏ mặc tự giải quyết", "A", "medium"),
    ("Văn hóa tổ chức là gì?", "Hệ thống giá trị, niềm tin và chuẩn mực chung được các thành viên chia sẻ", "Các hoạt động văn nghệ", "Quy định về trang phục", "Sơ đồ tổ chức", "A", "medium"),
    ("Truyền thông trong tổ chức có vai trò gì?", "Kết nối các bộ phận, bảo đảm thông tin thông suốt", "Chỉ để báo cáo lên cấp trên", "Chỉ dùng khi có sự cố", "Không quan trọng", "A", "easy"),
    ("Kiểm soát trước (feedforward control) diễn ra khi nào?", "Trước khi hoạt động bắt đầu, nhằm ngăn ngừa sai sót", "Trong khi hoạt động diễn ra", "Sau khi hoàn thành", "Chỉ khi có sự cố", "A", "hard"),
    ("Kiểm soát phản hồi (feedback control) có đặc điểm gì?", "Diễn ra sau khi hoạt động kết thúc để rút kinh nghiệm", "Ngăn chặn lỗi trước khi xảy ra", "Diễn ra đồng thời với hoạt động", "Không cần thông tin", "A", "medium"),
    ("Quản trị theo mục tiêu (MBO) nhấn mạnh điều gì?", "Cấp trên và cấp dưới cùng thống nhất mục tiêu và đánh giá theo kết quả", "Chỉ cấp trên đặt mục tiêu", "Không cần đo lường", "Chỉ quan tâm quá trình", "A", "hard"),
    ("KPI là gì?", "Chỉ số đo lường hiệu quả công việc chủ chốt", "Kế hoạch kinh doanh", "Quy trình sản xuất", "Cơ cấu tổ chức", "A", "easy"),
    ("Quản trị sự thay đổi đòi hỏi nhà quản trị làm gì?", "Chuẩn bị, truyền thông và xử lý sức ì phản kháng của nhân viên", "Áp đặt thay đổi ngay lập tức", "Tránh mọi thay đổi", "Chỉ thông báo khi đã xong", "A", "medium"),
    ("Nguyên nhân chính khiến nhân viên phản kháng thay đổi là gì?", "Lo sợ mất lợi ích, thói quen cũ và thiếu thông tin", "Do lười biếng", "Do lương thấp", "Do tuổi tác", "A", "medium"),
    ("Trách nhiệm xã hội của doanh nghiệp (CSR) bao gồm điều gì?", "Trách nhiệm với người lao động, cộng đồng và môi trường", "Chỉ tối đa lợi nhuận cho cổ đông", "Chỉ nộp thuế đầy đủ", "Chỉ làm từ thiện", "A", "easy"),
    ("Đạo đức kinh doanh đòi hỏi điều gì?", "Trung thực, tôn trọng pháp luật và các bên liên quan", "Lợi nhuận bằng mọi giá", "Cạnh tranh không lành mạnh", "Che giấu thông tin bất lợi", "A", "easy"),
    ("Quản trị nguồn nhân lực gồm hoạt động nào?", "Tuyển dụng, đào tạo, đánh giá và đãi ngộ", "Chỉ tuyển dụng", "Chỉ tính lương", "Chỉ kỷ luật nhân viên", "A", "easy"),
    ("Mục đích của đánh giá thành tích nhân viên là gì?", "Ghi nhận kết quả, làm cơ sở khen thưởng và phát triển năng lực", "Tìm lý do sa thải", "Giảm chi phí lương", "Tăng áp lực công việc", "A", "easy"),
    ("Làm việc nhóm hiệu quả cần yếu tố nào?", "Mục tiêu chung rõ ràng, phân vai hợp lý và tin cậy lẫn nhau", "Mỗi người làm riêng", "Một người quyết tất cả", "Tránh trao đổi để đỡ mất thời gian", "A", "easy"),
    ("Ra quyết định nhóm có ưu điểm gì so với cá nhân?", "Nhiều thông tin, nhiều góc nhìn và tăng cam kết thực hiện", "Nhanh hơn luôn luôn", "Ít tốn nguồn lực hơn", "Không bao giờ sai", "A", "medium"),
    ("Hiện tượng tư duy nhóm (groupthink) gây hậu quả gì?", "Nhóm đồng thuận mù quáng, bỏ qua phương án tốt hơn", "Tăng chất lượng quyết định", "Khuyến khích tranh luận", "Giảm thời gian họp", "A", "hard"),
]

DATA = {
    'Kinh tế vi mô': KINH_TE_VI_MO,
    'Kinh tế vĩ mô': KINH_TE_VI_MO_2,
    'Nguyên lý kế toán': KE_TOAN,
    'Marketing căn bản': MARKETING,
    'Quản trị học': QUAN_TRI_HOC,
}
