# -*- coding: utf-8 -*-
"""Nhóm Công nghệ thông tin."""

LAP_TRINH_C = [
    ("Hàm nào là điểm bắt đầu thực thi của chương trình C?", "main()", "start()", "begin()", "init()", "A", "easy"),
    ("Câu lệnh nào dùng để in ra màn hình trong C?", "printf()", "print()", "cout", "echo", "A", "easy"),
    ("Kiểu dữ liệu int trong C thường chiếm bao nhiêu byte?", "2 byte", "4 byte", "8 byte", "1 byte", "B", "easy"),
    ("Ký tự kết thúc câu lệnh trong C là gì?", "Dấu chấm phẩy", "Dấu phẩy", "Dấu chấm", "Dấu hai chấm", "A", "easy"),
    ("Toán tử nào dùng để so sánh bằng trong C?", "==", "=", "equals", "===", "A", "easy"),
    ("Toán tử % trong C có ý nghĩa gì?", "Lấy phần dư của phép chia", "Tính phần trăm", "Chia lấy nguyên", "Lũy thừa", "A", "easy"),
    ("Vòng lặp nào luôn thực hiện ít nhất một lần?", "do-while", "while", "for", "if", "A", "medium"),
    ("Từ khóa nào dùng để thoát khỏi vòng lặp?", "break", "continue", "return", "exit", "A", "easy"),
    ("Từ khóa continue có tác dụng gì?", "Bỏ qua phần còn lại của lần lặp hiện tại", "Thoát khỏi vòng lặp", "Kết thúc chương trình", "Quay lại đầu hàm", "A", "medium"),
    ("Mảng trong C có chỉ số bắt đầu từ đâu?", "0", "1", "-1", "Tùy khai báo", "A", "easy"),
    ("Con trỏ trong C lưu trữ cái gì?", "Địa chỉ của biến khác", "Giá trị của biến", "Tên biến", "Kiểu dữ liệu", "A", "medium"),
    ("Toán tử & trước tên biến có ý nghĩa gì?", "Lấy địa chỉ của biến", "Lấy giá trị của biến", "Phép AND logic", "Khai báo con trỏ", "A", "medium"),
    ("Toán tử * trước tên con trỏ có ý nghĩa gì?", "Lấy giá trị tại địa chỉ con trỏ trỏ tới", "Lấy địa chỉ", "Phép nhân", "Khai báo mảng", "A", "medium"),
    ("Hàm malloc() trong C dùng để làm gì?", "Cấp phát bộ nhớ động", "Giải phóng bộ nhớ", "Sao chép chuỗi", "So sánh chuỗi", "A", "medium"),
    ("Hàm free() dùng để làm gì?", "Giải phóng vùng nhớ đã cấp phát động", "Cấp phát bộ nhớ", "Xóa biến", "Đóng tệp", "A", "medium"),
    ("Chuỗi trong C kết thúc bằng ký tự nào?", "Ký tự null \\0", "Ký tự xuống dòng", "Dấu cách", "Dấu chấm phẩy", "A", "medium"),
    ("Hàm strlen() trả về giá trị gì?", "Độ dài chuỗi không tính ký tự kết thúc", "Kích thước bộ nhớ chuỗi", "Số từ trong chuỗi", "Ký tự đầu tiên", "A", "medium"),
    ("Hàm strcpy() dùng để làm gì?", "Sao chép chuỗi", "So sánh chuỗi", "Nối chuỗi", "Tìm ký tự", "A", "easy"),
    ("Struct trong C dùng để làm gì?", "Nhóm nhiều biến khác kiểu thành một kiểu dữ liệu mới", "Định nghĩa hàm", "Khai báo mảng", "Tạo vòng lặp", "A", "medium"),
    ("Sự khác nhau cơ bản giữa struct và union là gì?", "Union dùng chung một vùng nhớ cho mọi thành viên", "Struct không lưu được số", "Union không khai báo được", "Không có khác biệt", "A", "hard"),
    ("Biến cục bộ có phạm vi hoạt động ở đâu?", "Trong khối lệnh hoặc hàm khai báo nó", "Toàn bộ chương trình", "Chỉ trong hàm main", "Trong tệp header", "A", "easy"),
    ("Từ khóa static khi khai báo biến cục bộ có tác dụng gì?", "Biến giữ giá trị giữa các lần gọi hàm", "Biến bị xóa sau mỗi lần gọi", "Biến trở thành hằng số", "Biến chuyển thành con trỏ", "A", "hard"),
    ("Từ khóa const có ý nghĩa gì?", "Khai báo hằng số không thay đổi giá trị", "Khai báo biến toàn cục", "Cấp phát động", "Khai báo hàm", "A", "easy"),
    ("Truyền tham số theo tham chiếu trong C được thực hiện bằng cách nào?", "Truyền địa chỉ qua con trỏ", "Truyền trực tiếp giá trị", "Dùng từ khóa ref", "Không thực hiện được", "A", "medium"),
    ("Đệ quy là gì?", "Hàm tự gọi lại chính nó", "Vòng lặp vô hạn", "Gọi hàm từ hàm khác", "Khai báo hàm nhiều lần", "A", "easy"),
    ("Điều kiện bắt buộc để đệ quy không bị lặp vô hạn là gì?", "Phải có điều kiện dừng", "Phải dùng vòng lặp", "Phải khai báo static", "Phải có con trỏ", "A", "medium"),
    ("Thư viện nào cần include để dùng printf và scanf?", "stdio.h", "stdlib.h", "string.h", "math.h", "A", "easy"),
    ("Thư viện math.h cung cấp hàm nào?", "sqrt, pow, sin, cos", "printf, scanf", "malloc, free", "strlen, strcpy", "A", "easy"),
    ("Trong C++, từ khóa nào dùng để khai báo lớp?", "class", "struct only", "object", "define", "A", "easy"),
    ("Tính đóng gói (encapsulation) trong OOP nghĩa là gì?", "Che giấu dữ liệu bên trong và chỉ cho truy cập qua phương thức công khai", "Kế thừa từ lớp cha", "Một hàm nhiều dạng", "Tạo nhiều đối tượng", "A", "medium"),
    ("Tính kế thừa (inheritance) cho phép điều gì?", "Lớp con sử dụng lại thuộc tính và phương thức của lớp cha", "Che giấu dữ liệu", "Một hàm có nhiều dạng", "Tạo đối tượng động", "A", "easy"),
    ("Tính đa hình (polymorphism) nghĩa là gì?", "Cùng một phương thức có thể có nhiều cách thực hiện khác nhau", "Che giấu thuộc tính", "Kế thừa nhiều lớp", "Cấp phát bộ nhớ", "A", "medium"),
    ("Hàm tạo (constructor) được gọi khi nào?", "Khi đối tượng được tạo ra", "Khi đối tượng bị hủy", "Khi gọi phương thức", "Khi kết thúc chương trình", "A", "easy"),
    ("Hàm hủy (destructor) có nhiệm vụ gì?", "Giải phóng tài nguyên khi đối tượng bị hủy", "Khởi tạo giá trị", "Sao chép đối tượng", "So sánh đối tượng", "A", "medium"),
    ("Từ khóa private trong C++ có nghĩa gì?", "Chỉ truy cập được từ bên trong lớp", "Truy cập từ mọi nơi", "Chỉ lớp con truy cập được", "Chỉ hàm main truy cập được", "A", "easy"),
    ("Từ khóa protected khác private ở điểm nào?", "Lớp con có thể truy cập được", "Không có khác biệt", "Truy cập từ mọi nơi", "Chỉ dùng cho hàm", "A", "medium"),
    ("Trong C++, toán tử new dùng để làm gì?", "Cấp phát bộ nhớ động cho đối tượng", "Khai báo lớp", "Xóa đối tượng", "Sao chép đối tượng", "A", "medium"),
    ("Hàm ảo (virtual function) dùng để làm gì?", "Cho phép lớp con định nghĩa lại phương thức, hỗ trợ đa hình", "Che giấu dữ liệu", "Tăng tốc chương trình", "Khai báo hằng số", "A", "hard"),
    ("Lỗi tràn bộ đệm (buffer overflow) xảy ra khi nào?", "Khi ghi dữ liệu vượt quá kích thước vùng nhớ được cấp", "Khi chia cho 0", "Khi biến chưa khởi tạo", "Khi thiếu dấu chấm phẩy", "A", "medium"),
    ("Lỗi rò rỉ bộ nhớ (memory leak) xảy ra khi nào?", "Cấp phát động nhưng không giải phóng", "Khai báo quá nhiều biến", "Dùng vòng lặp lồng nhau", "Gọi hàm đệ quy", "A", "medium"),
    ("Kết quả của biểu thức 7/2 trong C với hai số nguyên là gì?", "3", "3.5", "4", "Lỗi biên dịch", "A", "medium"),
    ("Kết quả của biểu thức 7%3 là gì?", "1", "2", "3", "0", "A", "easy"),
    ("Toán tử ++i khác i++ ở điểm nào?", "++i tăng trước rồi trả giá trị, i++ trả giá trị rồi mới tăng", "Không có khác biệt", "++i chỉ dùng cho con trỏ", "i++ nhanh hơn", "A", "medium"),
    ("Câu lệnh switch dùng để làm gì?", "Rẽ nhánh theo nhiều giá trị của một biểu thức", "Lặp lại khối lệnh", "Khai báo hàm", "Cấp phát bộ nhớ", "A", "easy"),
    ("Nếu thiếu break trong case của switch thì điều gì xảy ra?", "Chương trình chạy tiếp các case phía sau", "Báo lỗi biên dịch", "Thoát khỏi switch", "Bỏ qua case đó", "A", "medium"),
    ("Mảng hai chiều a[3][4] có bao nhiêu phần tử?", "12", "7", "34", "9", "A", "easy"),
    ("Tệp header trong C có phần mở rộng gì?", ".h", ".c", ".cpp", ".obj", "A", "easy"),
    ("Chỉ thị #define dùng để làm gì?", "Định nghĩa hằng số hoặc macro", "Khai báo biến", "Gọi hàm", "Mở tệp", "A", "easy"),
    ("Quá trình biên dịch chương trình C gồm những giai đoạn chính nào?", "Tiền xử lý, biên dịch, hợp dịch và liên kết", "Chỉ biên dịch", "Chỉ liên kết", "Soạn thảo và chạy", "A", "hard"),
    ("Giá trị trả về của hàm main thường là gì khi chương trình chạy thành công?", "0", "1", "-1", "Không trả về", "A", "easy"),
]

CTDL_GT = [
    ("Cấu trúc dữ liệu là gì?", "Cách tổ chức và lưu trữ dữ liệu để sử dụng hiệu quả", "Một ngôn ngữ lập trình", "Một loại phần cứng", "Một hệ điều hành", "A", "easy"),
    ("Độ phức tạp thời gian của thuật toán tìm kiếm tuyến tính là bao nhiêu?", "O(n)", "O(log n)", "O(1)", "O(n^2)", "A", "easy"),
    ("Độ phức tạp thời gian của tìm kiếm nhị phân là bao nhiêu?", "O(log n)", "O(n)", "O(n log n)", "O(1)", "A", "medium"),
    ("Điều kiện để áp dụng tìm kiếm nhị phân là gì?", "Dãy phải được sắp xếp", "Dãy phải có số chẵn phần tử", "Dãy phải là số nguyên", "Không có điều kiện", "A", "easy"),
    ("Ngăn xếp (Stack) hoạt động theo nguyên tắc nào?", "Vào sau ra trước (LIFO)", "Vào trước ra trước (FIFO)", "Ưu tiên cao ra trước", "Ngẫu nhiên", "A", "easy"),
    ("Hàng đợi (Queue) hoạt động theo nguyên tắc nào?", "Vào trước ra trước (FIFO)", "Vào sau ra trước (LIFO)", "Theo độ ưu tiên", "Ngẫu nhiên", "A", "easy"),
    ("Thao tác thêm phần tử vào Stack gọi là gì?", "Push", "Pop", "Enqueue", "Insert", "A", "easy"),
    ("Thao tác lấy phần tử ra khỏi Stack gọi là gì?", "Pop", "Push", "Dequeue", "Delete", "A", "easy"),
    ("Danh sách liên kết đơn có đặc điểm gì?", "Mỗi nút chứa dữ liệu và con trỏ tới nút kế tiếp", "Mỗi nút có hai con trỏ", "Các phần tử liên tiếp trong bộ nhớ", "Kích thước cố định", "A", "medium"),
    ("Ưu điểm của danh sách liên kết so với mảng là gì?", "Thêm xóa phần tử linh hoạt, không cần dịch chuyển", "Truy cập ngẫu nhiên nhanh hơn", "Tốn ít bộ nhớ hơn", "Dễ sắp xếp hơn", "A", "medium"),
    ("Nhược điểm của danh sách liên kết là gì?", "Không truy cập trực tiếp theo chỉ số, phải duyệt tuần tự", "Không thêm được phần tử", "Kích thước cố định", "Không lưu được số", "A", "medium"),
    ("Cây nhị phân là cây mà mỗi nút có tối đa bao nhiêu con?", "2", "1", "3", "Không giới hạn", "A", "easy"),
    ("Cây nhị phân tìm kiếm (BST) có tính chất gì?", "Nút trái nhỏ hơn nút gốc, nút phải lớn hơn nút gốc", "Mọi nút đều bằng nhau", "Chỉ có nút trái", "Các nút sắp xếp ngẫu nhiên", "A", "medium"),
    ("Độ phức tạp tìm kiếm trung bình trên cây nhị phân tìm kiếm cân bằng là bao nhiêu?", "O(log n)", "O(n)", "O(n^2)", "O(1)", "A", "medium"),
    ("Duyệt cây theo thứ tự giữa (inorder) trên BST cho kết quả gì?", "Dãy các giá trị tăng dần", "Dãy giảm dần", "Dãy ngẫu nhiên", "Chỉ nút gốc", "A", "hard"),
    ("Duyệt cây theo thứ tự trước (preorder) đi theo trình tự nào?", "Gốc - trái - phải", "Trái - gốc - phải", "Trái - phải - gốc", "Phải - gốc - trái", "A", "medium"),
    ("Duyệt cây theo thứ tự sau (postorder) đi theo trình tự nào?", "Trái - phải - gốc", "Gốc - trái - phải", "Trái - gốc - phải", "Phải - trái - gốc", "A", "medium"),
    ("Đồ thị gồm những thành phần cơ bản nào?", "Đỉnh và cạnh", "Nút và lá", "Hàng và cột", "Khóa và giá trị", "A", "easy"),
    ("Thuật toán duyệt đồ thị theo chiều rộng gọi là gì?", "BFS", "DFS", "Dijkstra", "Kruskal", "A", "easy"),
    ("Thuật toán BFS sử dụng cấu trúc dữ liệu nào?", "Hàng đợi", "Ngăn xếp", "Cây nhị phân", "Bảng băm", "A", "medium"),
    ("Thuật toán DFS thường sử dụng cấu trúc dữ liệu nào?", "Ngăn xếp hoặc đệ quy", "Hàng đợi", "Danh sách liên kết đôi", "Bảng băm", "A", "medium"),
    ("Thuật toán Dijkstra dùng để giải bài toán gì?", "Tìm đường đi ngắn nhất từ một đỉnh tới các đỉnh khác", "Sắp xếp mảng", "Tìm cây khung nhỏ nhất", "Duyệt đồ thị", "A", "medium"),
    ("Thuật toán Kruskal dùng để làm gì?", "Tìm cây khung nhỏ nhất của đồ thị", "Tìm đường đi ngắn nhất", "Sắp xếp dữ liệu", "Tìm kiếm nhị phân", "A", "hard"),
    ("Độ phức tạp trung bình của thuật toán sắp xếp nhanh (QuickSort) là bao nhiêu?", "O(n log n)", "O(n^2)", "O(n)", "O(log n)", "A", "medium"),
    ("Độ phức tạp xấu nhất của QuickSort là bao nhiêu?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "A", "hard"),
    ("Thuật toán sắp xếp nổi bọt (Bubble Sort) có độ phức tạp bao nhiêu?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "A", "easy"),
    ("Thuật toán sắp xếp trộn (Merge Sort) có độ phức tạp là gì?", "O(n log n) trong mọi trường hợp", "O(n^2)", "O(n)", "O(log n)", "A", "medium"),
    ("Thuật toán sắp xếp nào ổn định (stable)?", "Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort", "A", "hard"),
    ("Bảng băm (Hash Table) cho phép tìm kiếm với độ phức tạp trung bình bao nhiêu?", "O(1)", "O(n)", "O(log n)", "O(n log n)", "A", "medium"),
    ("Xung đột (collision) trong bảng băm là gì?", "Hai khóa khác nhau cho cùng một giá trị băm", "Bảng băm bị đầy", "Khóa bị trùng lặp", "Hàm băm bị lỗi", "A", "medium"),
    ("Phương pháp giải quyết xung đột bằng danh sách liên kết gọi là gì?", "Chaining", "Open addressing", "Linear probing", "Rehashing", "A", "hard"),
    ("Heap là cấu trúc dữ liệu gì?", "Cây nhị phân gần hoàn chỉnh thỏa mãn tính chất heap", "Danh sách liên kết vòng", "Bảng băm mở rộng", "Đồ thị có hướng", "A", "medium"),
    ("Trong Max Heap, nút gốc có đặc điểm gì?", "Là phần tử lớn nhất", "Là phần tử nhỏ nhất", "Là phần tử trung bình", "Là phần tử cuối cùng", "A", "medium"),
    ("Hàng đợi ưu tiên thường được cài đặt bằng cấu trúc nào?", "Heap", "Mảng thường", "Danh sách liên kết đơn", "Bảng băm", "A", "medium"),
    ("Ký hiệu O lớn (Big-O) dùng để mô tả điều gì?", "Cận trên của độ phức tạp thuật toán", "Cận dưới chính xác", "Thời gian chạy thực tế", "Dung lượng bộ nhớ tối thiểu", "A", "easy"),
    ("Độ phức tạp O(1) nghĩa là gì?", "Thời gian chạy không phụ thuộc kích thước đầu vào", "Chạy trong 1 giây", "Cần 1 phép toán", "Chỉ có 1 vòng lặp", "A", "easy"),
    ("Thuật toán tham lam (Greedy) có đặc điểm gì?", "Chọn phương án tốt nhất tại mỗi bước với hy vọng đạt tối ưu toàn cục", "Duyệt hết mọi khả năng", "Chia bài toán thành bài toán con", "Lưu kết quả trung gian", "A", "medium"),
    ("Quy hoạch động (Dynamic Programming) dựa trên nguyên tắc nào?", "Chia thành bài toán con và lưu lại kết quả để tránh tính lặp", "Chọn tối ưu cục bộ", "Duyệt vét cạn", "Sắp xếp trước khi xử lý", "A", "medium"),
    ("Bài toán dãy Fibonacci giải bằng đệ quy thuần túy có nhược điểm gì?", "Tính lặp lại nhiều lần, độ phức tạp lớn", "Không cho kết quả đúng", "Không thể cài đặt", "Tốn ít bộ nhớ", "A", "medium"),
    ("Kỹ thuật chia để trị (Divide and Conquer) gồm mấy bước chính?", "Chia, trị và kết hợp", "Chỉ chia nhỏ", "Chỉ sắp xếp", "Duyệt và chọn", "A", "medium"),
    ("Thuật toán nào áp dụng kỹ thuật chia để trị?", "Merge Sort", "Bubble Sort", "Selection Sort", "Insertion Sort", "A", "medium"),
    ("Danh sách liên kết đôi khác đơn ở điểm nào?", "Mỗi nút có con trỏ tới cả nút trước và nút sau", "Chỉ lưu được số nguyên", "Không có nút đầu", "Kích thước cố định", "A", "easy"),
    ("Đồ thị có hướng khác đồ thị vô hướng ở điểm nào?", "Các cạnh có chiều xác định", "Không có đỉnh", "Không có chu trình", "Chỉ có một đỉnh", "A", "easy"),
    ("Ma trận kề dùng để biểu diễn gì?", "Quan hệ giữa các đỉnh trong đồ thị", "Thứ tự sắp xếp", "Cây nhị phân", "Bảng băm", "A", "medium"),
    ("Ưu điểm của danh sách kề so với ma trận kề là gì?", "Tiết kiệm bộ nhớ với đồ thị thưa", "Kiểm tra cạnh nhanh hơn", "Dễ cài đặt hơn", "Luôn nhanh hơn", "A", "hard"),
    ("Chu trình Euler trong đồ thị là gì?", "Chu trình đi qua mỗi cạnh đúng một lần", "Chu trình qua mỗi đỉnh một lần", "Đường đi ngắn nhất", "Cây khung nhỏ nhất", "A", "hard"),
    ("Chu trình Hamilton là gì?", "Chu trình đi qua mỗi đỉnh đúng một lần", "Chu trình qua mỗi cạnh một lần", "Đường đi có trọng số nhỏ nhất", "Cây khung", "A", "hard"),
    ("Cây AVL là gì?", "Cây nhị phân tìm kiếm tự cân bằng", "Cây có nhiều nhánh", "Cây biểu thức", "Cây quyết định", "A", "hard"),
    ("Mục đích của việc cân bằng cây tìm kiếm là gì?", "Giữ chiều cao cây ở mức O(log n) để thao tác hiệu quả", "Giảm số nút", "Tăng số lá", "Sắp xếp lại giá trị", "A", "hard"),
    ("Đệ quy đuôi (tail recursion) có ưu điểm gì?", "Có thể được tối ưu thành vòng lặp, tiết kiệm ngăn xếp", "Chạy nhanh hơn mọi thuật toán", "Không cần điều kiện dừng", "Dùng ít biến hơn", "A", "hard"),
]

CO_SO_DU_LIEU = [
    ("Cơ sở dữ liệu là gì?", "Tập hợp dữ liệu có tổ chức, lưu trữ và truy xuất theo yêu cầu", "Một phần mềm soạn thảo", "Một loại phần cứng", "Một ngôn ngữ lập trình", "A", "easy"),
    ("Hệ quản trị cơ sở dữ liệu (DBMS) có chức năng gì?", "Quản lý việc lưu trữ, truy xuất và bảo mật dữ liệu", "Thiết kế giao diện", "Biên dịch chương trình", "Kết nối mạng", "A", "easy"),
    ("Mô hình dữ liệu phổ biến nhất hiện nay là gì?", "Mô hình quan hệ", "Mô hình phân cấp", "Mô hình mạng", "Mô hình đối tượng", "A", "easy"),
    ("Trong mô hình quan hệ, bảng còn được gọi là gì?", "Quan hệ", "Thực thể", "Thuộc tính", "Miền giá trị", "A", "medium"),
    ("Khóa chính (Primary Key) có đặc điểm gì?", "Xác định duy nhất mỗi bản ghi và không được rỗng", "Có thể trùng lặp", "Luôn là kiểu số", "Có thể để trống", "A", "easy"),
    ("Khóa ngoại (Foreign Key) dùng để làm gì?", "Liên kết dữ liệu giữa hai bảng", "Xác định duy nhất bản ghi", "Tăng tốc truy vấn", "Mã hóa dữ liệu", "A", "easy"),
    ("Câu lệnh SQL nào dùng để truy vấn dữ liệu?", "SELECT", "INSERT", "UPDATE", "DELETE", "A", "easy"),
    ("Câu lệnh nào dùng để thêm bản ghi mới?", "INSERT INTO", "SELECT", "UPDATE", "ALTER", "A", "easy"),
    ("Câu lệnh nào dùng để sửa dữ liệu đã có?", "UPDATE", "INSERT", "SELECT", "CREATE", "A", "easy"),
    ("Mệnh đề WHERE trong SQL dùng để làm gì?", "Lọc bản ghi theo điều kiện", "Sắp xếp kết quả", "Nhóm dữ liệu", "Nối bảng", "A", "easy"),
    ("Mệnh đề ORDER BY dùng để làm gì?", "Sắp xếp kết quả truy vấn", "Lọc dữ liệu", "Nhóm dữ liệu", "Đếm bản ghi", "A", "easy"),
    ("Mệnh đề GROUP BY dùng để làm gì?", "Nhóm các bản ghi có cùng giá trị để tính toán tổng hợp", "Sắp xếp dữ liệu", "Lọc bản ghi", "Xóa dữ liệu trùng", "A", "medium"),
    ("Mệnh đề HAVING khác WHERE ở điểm nào?", "HAVING lọc sau khi nhóm, WHERE lọc trước khi nhóm", "Không có khác biệt", "HAVING nhanh hơn", "WHERE chỉ dùng với GROUP BY", "A", "hard"),
    ("Hàm COUNT() trong SQL trả về gì?", "Số lượng bản ghi", "Tổng giá trị", "Giá trị lớn nhất", "Giá trị trung bình", "A", "easy"),
    ("Hàm SUM() dùng để làm gì?", "Tính tổng các giá trị số", "Đếm bản ghi", "Tìm giá trị lớn nhất", "Nối chuỗi", "A", "easy"),
    ("INNER JOIN trả về kết quả gì?", "Các bản ghi khớp ở cả hai bảng", "Tất cả bản ghi của bảng trái", "Tất cả bản ghi của bảng phải", "Toàn bộ bản ghi hai bảng", "A", "medium"),
    ("LEFT JOIN trả về kết quả gì?", "Toàn bộ bản ghi bảng trái và bản ghi khớp ở bảng phải", "Chỉ bản ghi khớp", "Toàn bộ bảng phải", "Bản ghi không khớp", "A", "medium"),
    ("Từ khóa DISTINCT dùng để làm gì?", "Loại bỏ giá trị trùng lặp trong kết quả", "Sắp xếp dữ liệu", "Đếm bản ghi", "Nhóm dữ liệu", "A", "easy"),
    ("Chuẩn hóa cơ sở dữ liệu nhằm mục đích gì?", "Giảm dư thừa dữ liệu và tránh bất thường khi cập nhật", "Tăng tốc độ truy vấn tuyệt đối", "Giảm số bảng", "Tăng dung lượng lưu trữ", "A", "medium"),
    ("Dạng chuẩn 1NF yêu cầu điều gì?", "Mỗi thuộc tính chỉ chứa giá trị nguyên tố, không lặp nhóm", "Không có phụ thuộc bắc cầu", "Không có phụ thuộc hàm bộ phận", "Mọi thuộc tính đều là khóa", "A", "medium"),
    ("Dạng chuẩn 2NF yêu cầu điều gì?", "Đạt 1NF và loại bỏ phụ thuộc hàm bộ phận vào khóa chính", "Loại bỏ phụ thuộc bắc cầu", "Chỉ có một bảng", "Không có khóa ngoại", "A", "hard"),
    ("Dạng chuẩn 3NF yêu cầu điều gì?", "Đạt 2NF và loại bỏ phụ thuộc bắc cầu", "Loại bỏ phụ thuộc bộ phận", "Mọi thuộc tính là nguyên tố", "Không có khóa chính", "A", "hard"),
    ("Giao dịch (Transaction) trong CSDL là gì?", "Chuỗi thao tác được thực hiện như một đơn vị không thể chia cắt", "Một câu truy vấn đơn lẻ", "Việc sao lưu dữ liệu", "Kết nối tới máy chủ", "A", "medium"),
    ("Tính chất ACID gồm những gì?", "Nguyên tử, nhất quán, cô lập và bền vững", "Nhanh, chính xác, an toàn, đơn giản", "Thêm, sửa, xóa, đọc", "Khóa chính, ngoại, duy nhất, tổng hợp", "A", "medium"),
    ("Tính nguyên tử (Atomicity) của giao dịch nghĩa là gì?", "Hoặc thực hiện toàn bộ, hoặc không thực hiện gì cả", "Dữ liệu luôn đúng ràng buộc", "Các giao dịch không ảnh hưởng nhau", "Kết quả được lưu vĩnh viễn", "A", "medium"),
    ("Lệnh COMMIT có tác dụng gì?", "Xác nhận và lưu vĩnh viễn các thay đổi của giao dịch", "Hủy bỏ thay đổi", "Tạo bảng mới", "Sao lưu dữ liệu", "A", "medium"),
    ("Lệnh ROLLBACK có tác dụng gì?", "Hủy bỏ các thay đổi, đưa dữ liệu về trạng thái trước giao dịch", "Lưu thay đổi", "Xóa bảng", "Tạo chỉ mục", "A", "medium"),
    ("Chỉ mục (Index) trong CSDL có tác dụng gì?", "Tăng tốc độ truy vấn tìm kiếm", "Giảm dung lượng lưu trữ", "Mã hóa dữ liệu", "Tạo quan hệ giữa bảng", "A", "medium"),
    ("Nhược điểm của việc tạo quá nhiều chỉ mục là gì?", "Làm chậm thao tác thêm sửa xóa và tốn dung lượng", "Truy vấn chậm hơn", "Không lưu được dữ liệu", "Mất khóa chính", "A", "hard"),
    ("View trong CSDL là gì?", "Bảng ảo được tạo từ kết quả truy vấn", "Bảng vật lý lưu trên đĩa", "Một loại chỉ mục", "Một thủ tục lưu trữ", "A", "medium"),
    ("Stored Procedure là gì?", "Tập hợp câu lệnh SQL được lưu và thực thi trên máy chủ CSDL", "Một bảng dữ liệu", "Một loại khóa", "Một công cụ sao lưu", "A", "medium"),
    ("Trigger trong CSDL hoạt động khi nào?", "Tự động chạy khi có sự kiện thêm, sửa hoặc xóa dữ liệu", "Khi người dùng gọi trực tiếp", "Khi khởi động máy chủ", "Khi sao lưu dữ liệu", "A", "medium"),
    ("Ràng buộc NOT NULL có ý nghĩa gì?", "Cột không được để trống giá trị", "Cột phải là duy nhất", "Cột là khóa chính", "Cột tự tăng", "A", "easy"),
    ("Ràng buộc UNIQUE có ý nghĩa gì?", "Giá trị trong cột không được trùng lặp", "Giá trị không được rỗng", "Cột là khóa ngoại", "Cột có giá trị mặc định", "A", "easy"),
    ("Toàn vẹn tham chiếu đảm bảo điều gì?", "Giá trị khóa ngoại phải tồn tại trong bảng được tham chiếu", "Dữ liệu không bị trùng", "Cột không rỗng", "Truy vấn nhanh hơn", "A", "medium"),
    ("Ngôn ngữ định nghĩa dữ liệu (DDL) gồm những lệnh nào?", "CREATE, ALTER, DROP", "SELECT, INSERT, UPDATE", "COMMIT, ROLLBACK", "GRANT, REVOKE", "A", "medium"),
    ("Ngôn ngữ thao tác dữ liệu (DML) gồm những lệnh nào?", "SELECT, INSERT, UPDATE, DELETE", "CREATE, DROP", "GRANT, REVOKE", "COMMIT, ROLLBACK", "A", "medium"),
    ("Lệnh GRANT dùng để làm gì?", "Cấp quyền truy cập cho người dùng", "Tạo bảng mới", "Xóa dữ liệu", "Sao lưu CSDL", "A", "medium"),
    ("Tấn công SQL Injection là gì?", "Chèn mã SQL độc hại qua dữ liệu đầu vào để truy cập trái phép", "Làm quá tải máy chủ CSDL", "Đánh cắp mật khẩu qua email", "Phá hủy ổ cứng", "A", "medium"),
    ("Cách phòng chống SQL Injection hiệu quả nhất là gì?", "Dùng câu lệnh tham số hóa và kiểm tra dữ liệu đầu vào", "Đổi mật khẩu thường xuyên", "Tắt máy chủ khi không dùng", "Dùng bảng ít cột", "A", "medium"),
    ("Sao lưu (backup) CSDL nhằm mục đích gì?", "Phục hồi dữ liệu khi có sự cố", "Tăng tốc truy vấn", "Giảm dung lượng", "Mã hóa dữ liệu", "A", "easy"),
    ("CSDL NoSQL khác CSDL quan hệ ở điểm nào?", "Không dùng bảng quan hệ cố định, linh hoạt về cấu trúc dữ liệu", "Không lưu được dữ liệu", "Chỉ dùng cho ứng dụng nhỏ", "Không hỗ trợ truy vấn", "A", "medium"),
    ("Quan hệ một - nhiều được cài đặt như thế nào?", "Đặt khóa ngoại ở bảng phía nhiều", "Tạo bảng trung gian", "Đặt khóa ngoại ở bảng phía một", "Không cần khóa ngoại", "A", "hard"),
    ("Quan hệ nhiều - nhiều được cài đặt như thế nào?", "Tạo bảng trung gian chứa khóa ngoại của cả hai bảng", "Đặt khóa ngoại ở một bảng", "Gộp hai bảng làm một", "Dùng chỉ mục", "A", "hard"),
    ("Mô hình thực thể - liên kết (ERD) dùng để làm gì?", "Mô hình hóa cấu trúc dữ liệu ở mức khái niệm", "Viết mã chương trình", "Thiết kế giao diện", "Kiểm thử phần mềm", "A", "easy"),
    ("Thuộc tính đa trị trong ERD là gì?", "Thuộc tính có thể nhận nhiều giá trị cho một thực thể", "Thuộc tính khóa chính", "Thuộc tính tính toán được", "Thuộc tính bắt buộc", "A", "hard"),
    ("Deadlock trong CSDL là gì?", "Hai giao dịch chờ nhau giải phóng tài nguyên nên không giao dịch nào tiếp tục được", "Máy chủ bị treo", "Dữ liệu bị mất", "Truy vấn chạy chậm", "A", "hard"),
    ("Mức cô lập (isolation level) của giao dịch ảnh hưởng đến điều gì?", "Mức độ giao dịch này nhìn thấy thay đổi của giao dịch khác", "Tốc độ ghi đĩa", "Dung lượng lưu trữ", "Số lượng người dùng", "A", "hard"),
    ("Data Warehouse khác CSDL tác nghiệp ở điểm nào?", "Lưu dữ liệu lịch sử phục vụ phân tích thay vì xử lý giao dịch hàng ngày", "Nhỏ hơn nhiều", "Không lưu được dữ liệu cũ", "Chỉ dùng NoSQL", "A", "medium"),
    ("Mục đích của việc phi chuẩn hóa (denormalization) là gì?", "Tăng tốc truy vấn bằng cách chấp nhận dư thừa dữ liệu có kiểm soát", "Giảm dung lượng lưu trữ", "Loại bỏ khóa ngoại", "Đảm bảo toàn vẹn dữ liệu", "A", "hard"),
]

MANG_MAY_TINH = [
    ("Mô hình OSI có bao nhiêu tầng?", "5 tầng", "6 tầng", "7 tầng", "4 tầng", "C", "easy"),
    ("Tầng nào trong mô hình OSI chịu trách nhiệm định tuyến?", "Tầng mạng (Network)", "Tầng vật lý", "Tầng phiên", "Tầng ứng dụng", "A", "medium"),
    ("Giao thức TCP hoạt động ở tầng nào?", "Tầng giao vận (Transport)", "Tầng mạng", "Tầng liên kết dữ liệu", "Tầng ứng dụng", "A", "medium"),
    ("Sự khác nhau cơ bản giữa TCP và UDP là gì?", "TCP có kết nối và đảm bảo tin cậy, UDP không kết nối và nhanh hơn", "UDP tin cậy hơn TCP", "TCP nhanh hơn UDP", "Không có khác biệt", "A", "medium"),
    ("Địa chỉ MAC là gì?", "Địa chỉ vật lý của card mạng", "Địa chỉ logic của máy tính", "Tên miền của trang web", "Cổng dịch vụ mạng", "A", "easy"),
    ("Địa chỉ IPv4 có bao nhiêu bit?", "32 bit", "64 bit", "128 bit", "16 bit", "A", "easy"),
    ("Địa chỉ IPv6 có bao nhiêu bit?", "32 bit", "64 bit", "128 bit", "256 bit", "C", "easy"),
    ("Giao thức DHCP có chức năng gì?", "Cấp phát địa chỉ IP tự động cho thiết bị trong mạng", "Phân giải tên miền", "Truyền tệp tin", "Gửi thư điện tử", "A", "easy"),
    ("Giao thức DNS có chức năng gì?", "Phân giải tên miền thành địa chỉ IP", "Cấp phát IP động", "Mã hóa dữ liệu", "Định tuyến gói tin", "A", "easy"),
    ("Cổng mặc định của giao thức HTTP là gì?", "80", "443", "21", "25", "A", "easy"),
    ("Cổng mặc định của giao thức HTTPS là gì?", "443", "80", "22", "110", "A", "easy"),
    ("Giao thức FTP dùng để làm gì?", "Truyền tệp tin giữa các máy tính", "Gửi email", "Duyệt web", "Điều khiển từ xa", "A", "easy"),
    ("Giao thức SMTP dùng để làm gì?", "Gửi thư điện tử", "Nhận thư điện tử", "Truyền tệp", "Phân giải tên miền", "A", "easy"),
    ("Thiết bị nào hoạt động ở tầng mạng và thực hiện định tuyến?", "Router", "Switch", "Hub", "Repeater", "A", "medium"),
    ("Switch hoạt động chủ yếu ở tầng nào của mô hình OSI?", "Tầng liên kết dữ liệu", "Tầng mạng", "Tầng vật lý", "Tầng giao vận", "A", "medium"),
    ("Hub khác Switch ở điểm nào?", "Hub phát tín hiệu ra mọi cổng, Switch gửi đúng cổng đích", "Hub nhanh hơn Switch", "Switch không có cổng", "Không có khác biệt", "A", "medium"),
    ("Subnet mask dùng để làm gì?", "Xác định phần địa chỉ mạng và phần địa chỉ host", "Mã hóa dữ liệu truyền", "Chặn truy cập trái phép", "Tăng tốc độ mạng", "A", "medium"),
    ("Địa chỉ IP 192.168.1.1 thuộc lớp nào?", "Lớp C", "Lớp A", "Lớp B", "Lớp D", "A", "medium"),
    ("Dải địa chỉ IP riêng (private) thường dùng trong mạng nội bộ là gì?", "192.168.x.x, 10.x.x.x, 172.16-31.x.x", "8.8.8.8", "1.1.1.1", "203.x.x.x", "A", "medium"),
    ("NAT có chức năng gì?", "Chuyển đổi địa chỉ IP riêng thành IP công cộng", "Phân giải tên miền", "Cấp phát IP tự động", "Mã hóa gói tin", "A", "medium"),
    ("Mô hình TCP/IP có bao nhiêu tầng?", "4 tầng", "5 tầng", "7 tầng", "3 tầng", "A", "medium"),
    ("Gói tin (packet) là gì?", "Đơn vị dữ liệu được truyền trên mạng ở tầng mạng", "Một tệp tin hoàn chỉnh", "Một thiết bị mạng", "Một giao thức truyền thông", "A", "easy"),
    ("Băng thông mạng là gì?", "Lượng dữ liệu tối đa truyền được trong một đơn vị thời gian", "Khoảng cách truyền tín hiệu", "Số thiết bị kết nối", "Độ trễ của mạng", "A", "easy"),
    ("Độ trễ (latency) trong mạng là gì?", "Thời gian gói tin đi từ nguồn tới đích", "Lượng dữ liệu truyền được", "Số gói tin bị mất", "Tốc độ xử lý của router", "A", "easy"),
    ("Mạng LAN có phạm vi như thế nào?", "Trong một khu vực nhỏ như tòa nhà, văn phòng", "Toàn cầu", "Giữa các thành phố", "Giữa các quốc gia", "A", "easy"),
    ("Mạng WAN là gì?", "Mạng diện rộng kết nối các vùng địa lý xa nhau", "Mạng nội bộ trong tòa nhà", "Mạng không dây cá nhân", "Mạng trong một phòng", "A", "easy"),
    ("Topology hình sao (Star) có đặc điểm gì?", "Các thiết bị nối vào một thiết bị trung tâm", "Các thiết bị nối thành vòng khép kín", "Các thiết bị nối trên một đường trục chung", "Mỗi thiết bị nối với mọi thiết bị khác", "A", "medium"),
    ("Nhược điểm của topology hình sao là gì?", "Hỏng thiết bị trung tâm thì toàn mạng ngừng hoạt động", "Khó mở rộng", "Tốn nhiều cáp nhất", "Khó phát hiện lỗi", "A", "medium"),
    ("Giao thức HTTPS bảo mật nhờ công nghệ nào?", "SSL/TLS", "FTP", "DNS", "DHCP", "A", "easy"),
    ("Tường lửa (Firewall) hoạt động dựa trên nguyên tắc nào?", "Lọc gói tin theo tập luật đã cấu hình", "Diệt virus trong tệp", "Tăng tốc độ mạng", "Cấp phát địa chỉ IP", "A", "medium"),
    ("VPN có tác dụng gì?", "Tạo kết nối riêng ảo an toàn qua mạng công cộng", "Tăng băng thông", "Cấp IP tĩnh", "Chặn quảng cáo", "A", "medium"),
    ("Tấn công DDoS là gì?", "Làm quá tải hệ thống bằng lượng lớn yêu cầu từ nhiều nguồn", "Đánh cắp mật khẩu", "Chèn mã độc vào CSDL", "Nghe lén dữ liệu", "A", "medium"),
    ("Giao thức ARP dùng để làm gì?", "Phân giải địa chỉ IP thành địa chỉ MAC", "Phân giải tên miền", "Định tuyến gói tin", "Truyền tệp tin", "A", "hard"),
    ("Giao thức ICMP được sử dụng bởi lệnh nào?", "ping", "ftp", "telnet", "ssh", "A", "medium"),
    ("Lệnh ping dùng để làm gì?", "Kiểm tra kết nối và độ trễ tới một máy khác", "Truyền tệp tin", "Đăng nhập từ xa", "Quét cổng", "A", "easy"),
    ("Lệnh tracert (traceroute) dùng để làm gì?", "Xác định đường đi của gói tin qua các router", "Kiểm tra tốc độ mạng", "Cấu hình IP", "Quét virus", "A", "medium"),
    ("Mô hình client - server hoạt động thế nào?", "Máy khách gửi yêu cầu, máy chủ xử lý và phản hồi", "Các máy ngang hàng nhau", "Chỉ có một máy hoạt động", "Không cần kết nối mạng", "A", "easy"),
    ("Mô hình peer-to-peer có đặc điểm gì?", "Các máy vừa là máy khách vừa là máy chủ", "Có máy chủ trung tâm điều khiển", "Chỉ truyền một chiều", "Cần router chuyên dụng", "A", "medium"),
    ("Wifi chuẩn 802.11 thuộc loại mạng nào?", "Mạng cục bộ không dây", "Mạng diện rộng có dây", "Mạng cáp quang", "Mạng vệ tinh", "A", "easy"),
    ("Cáp quang có ưu điểm gì so với cáp đồng?", "Tốc độ cao, truyền xa và ít nhiễu", "Giá rẻ hơn", "Dễ lắp đặt hơn", "Bền hơn khi uốn cong", "A", "easy"),
    ("Giao thức SSH dùng để làm gì?", "Đăng nhập và điều khiển máy từ xa một cách bảo mật", "Truyền tệp không mã hóa", "Gửi email", "Duyệt web", "A", "medium"),
    ("Cổng mặc định của SSH là gì?", "22", "23", "21", "80", "A", "medium"),
    ("Địa chỉ 127.0.0.1 có ý nghĩa gì?", "Địa chỉ loopback trỏ về chính máy đó", "Địa chỉ quảng bá", "Địa chỉ mạng công cộng", "Địa chỉ router mặc định", "A", "medium"),
    ("Định tuyến tĩnh khác định tuyến động ở điểm nào?", "Định tuyến tĩnh do người quản trị cấu hình thủ công", "Định tuyến tĩnh tự động cập nhật", "Định tuyến động không cần router", "Không có khác biệt", "A", "medium"),
    ("Giao thức định tuyến OSPF thuộc loại nào?", "Link-state", "Distance-vector", "Path-vector", "Static", "A", "hard"),
    ("Bảng định tuyến (routing table) chứa thông tin gì?", "Đường đi tới các mạng đích", "Danh sách người dùng", "Mật khẩu truy cập", "Nội dung gói tin", "A", "medium"),
    ("Chức năng chính của tầng vật lý trong mô hình OSI là gì?", "Truyền tín hiệu bit trên đường truyền vật lý", "Định tuyến gói tin", "Mã hóa dữ liệu ứng dụng", "Quản lý phiên làm việc", "A", "medium"),
    ("Sự khác nhau giữa half-duplex và full-duplex là gì?", "Full-duplex cho phép truyền và nhận đồng thời", "Half-duplex nhanh hơn", "Full-duplex chỉ truyền một chiều", "Không có khác biệt", "A", "medium"),
    ("Mạng 5G có ưu điểm nổi bật nào?", "Tốc độ cao và độ trễ rất thấp", "Chỉ dùng cho điện thoại cố định", "Không cần trạm phát", "Chỉ truyền được văn bản", "A", "easy"),
    ("Điện toán biên (Edge Computing) có mục đích gì?", "Xử lý dữ liệu gần nguồn phát sinh để giảm độ trễ", "Tập trung mọi xử lý về trung tâm", "Thay thế hoàn toàn đám mây", "Giảm chi phí phần cứng", "A", "medium"),
]

HE_DIEU_HANH = [
    ("Hệ điều hành có chức năng chính nào?", "Quản lý tài nguyên và cung cấp môi trường cho ứng dụng chạy", "Soạn thảo văn bản", "Thiết kế đồ họa", "Biên dịch mã nguồn", "A", "easy"),
    ("Tiến trình (process) là gì?", "Chương trình đang được thực thi", "Tệp chương trình trên đĩa", "Một dòng lệnh", "Một vùng nhớ trống", "A", "easy"),
    ("Luồng (thread) khác tiến trình ở điểm nào?", "Các luồng trong cùng tiến trình chia sẻ không gian địa chỉ", "Luồng chậm hơn tiến trình", "Luồng không thực thi được", "Không có khác biệt", "A", "medium"),
    ("Trạng thái nào không phải trạng thái của tiến trình?", "Đã biên dịch", "Sẵn sàng (Ready)", "Đang chạy (Running)", "Chờ (Waiting)", "A", "medium"),
    ("Bộ lập lịch CPU có nhiệm vụ gì?", "Quyết định tiến trình nào được sử dụng CPU tiếp theo", "Cấp phát bộ nhớ", "Quản lý tệp tin", "Điều khiển thiết bị vào ra", "A", "easy"),
    ("Thuật toán lập lịch FCFS hoạt động thế nào?", "Tiến trình đến trước được phục vụ trước", "Tiến trình ngắn nhất trước", "Tiến trình ưu tiên cao trước", "Chia đều thời gian", "A", "easy"),
    ("Thuật toán lập lịch SJF có ưu điểm gì?", "Thời gian chờ trung bình nhỏ nhất", "Công bằng nhất", "Đơn giản nhất", "Phù hợp thời gian thực", "A", "medium"),
    ("Thuật toán Round Robin dựa trên nguyên tắc nào?", "Mỗi tiến trình được cấp một lượng tử thời gian luân phiên", "Tiến trình ngắn chạy trước", "Ưu tiên cao chạy trước", "Chạy đến khi hoàn thành", "A", "medium"),
    ("Hiện tượng đói tài nguyên (starvation) là gì?", "Tiến trình chờ mãi không được cấp tài nguyên", "Hai tiến trình chờ nhau", "Bộ nhớ bị đầy", "CPU quá tải", "A", "medium"),
    ("Deadlock (bế tắc) xảy ra khi nào?", "Các tiến trình chờ nhau giải phóng tài nguyên và không tiến trình nào tiếp tục được", "CPU hoạt động 100%", "Bộ nhớ bị phân mảnh", "Tiến trình bị lỗi", "A", "medium"),
    ("Bốn điều kiện cần để xảy ra deadlock gồm gì?", "Loại trừ tương hỗ, giữ và chờ, không trưng dụng, chờ vòng tròn", "Đói tài nguyên, phân mảnh, tràn bộ đệm, quá tải", "CPU, RAM, đĩa, mạng", "Đọc, ghi, xóa, sửa", "A", "hard"),
    ("Semaphore dùng để làm gì?", "Đồng bộ hóa truy cập tài nguyên chia sẻ giữa các tiến trình", "Cấp phát bộ nhớ", "Lập lịch CPU", "Quản lý tệp tin", "A", "medium"),
    ("Vùng găng (critical section) là gì?", "Đoạn mã truy cập tài nguyên chia sẻ cần được bảo vệ", "Vùng nhớ hệ điều hành", "Phần khởi động máy", "Vùng đĩa dự phòng", "A", "medium"),
    ("Bộ nhớ ảo (virtual memory) có tác dụng gì?", "Cho phép chạy chương trình lớn hơn bộ nhớ vật lý thực có", "Tăng tốc độ CPU", "Giảm dung lượng đĩa", "Bảo vệ khỏi virus", "A", "medium"),
    ("Phân trang (paging) là kỹ thuật gì?", "Chia bộ nhớ thành các khối cố định để quản lý", "Chia đĩa thành phân vùng", "Nén dữ liệu bộ nhớ", "Sao lưu bộ nhớ", "A", "medium"),
    ("Lỗi trang (page fault) xảy ra khi nào?", "Khi trang cần truy cập không có trong bộ nhớ chính", "Khi CPU quá tải", "Khi đĩa bị đầy", "Khi tiến trình kết thúc", "A", "medium"),
    ("Thuật toán thay trang LRU dựa trên nguyên tắc nào?", "Thay trang lâu nhất chưa được sử dụng", "Thay trang vào trước", "Thay trang ngẫu nhiên", "Thay trang lớn nhất", "A", "medium"),
    ("Hiện tượng thrashing là gì?", "Hệ thống dành phần lớn thời gian để hoán chuyển trang thay vì xử lý", "CPU chạy quá nhanh", "Đĩa cứng bị hỏng", "Bộ nhớ bị rò rỉ", "A", "hard"),
    ("Phân mảnh ngoài (external fragmentation) là gì?", "Bộ nhớ trống bị chia nhỏ rải rác không dùng được cho yêu cầu lớn", "Vùng nhớ cấp thừa trong khối", "Đĩa bị chia nhiều phân vùng", "Tệp bị lưu rải rác", "A", "hard"),
    ("Hệ thống tệp tin (file system) có chức năng gì?", "Tổ chức, lưu trữ và quản lý tệp trên thiết bị lưu trữ", "Quản lý tiến trình", "Lập lịch CPU", "Điều khiển mạng", "A", "easy"),
    ("NTFS là hệ thống tệp của hệ điều hành nào?", "Windows", "Linux", "macOS", "Android", "A", "easy"),
    ("Ext4 là hệ thống tệp phổ biến của hệ điều hành nào?", "Linux", "Windows", "macOS", "iOS", "A", "easy"),
    ("Thư mục gốc trong Linux được ký hiệu là gì?", "Dấu gạch chéo /", "C:", "root:", "Dấu chấm .", "A", "easy"),
    ("Lệnh nào trong Linux dùng để liệt kê tệp trong thư mục?", "ls", "dir", "list", "show", "A", "easy"),
    ("Lệnh cd trong Linux dùng để làm gì?", "Chuyển thư mục làm việc", "Sao chép tệp", "Xóa tệp", "Tạo thư mục", "A", "easy"),
    ("Lệnh nào dùng để tạo thư mục mới trong Linux?", "mkdir", "touch", "rm", "cp", "A", "easy"),
    ("Lệnh chmod trong Linux dùng để làm gì?", "Thay đổi quyền truy cập tệp", "Đổi tên tệp", "Di chuyển tệp", "Nén tệp", "A", "medium"),
    ("Quyền 755 trong Linux có ý nghĩa gì?", "Chủ sở hữu đọc ghi thực thi, nhóm và người khác đọc và thực thi", "Mọi người có toàn quyền", "Chỉ chủ sở hữu đọc được", "Không ai có quyền gì", "A", "hard"),
    ("Tiến trình nền (background process) trong Linux được chạy bằng ký hiệu nào?", "Dấu và (&) ở cuối lệnh", "Dấu chấm than", "Dấu hai chấm", "Dấu sao", "A", "medium"),
    ("Kernel là gì?", "Phần lõi của hệ điều hành quản lý tài nguyên phần cứng", "Giao diện người dùng", "Trình biên dịch", "Ứng dụng hệ thống", "A", "easy"),
    ("Chế độ kernel khác chế độ người dùng ở điểm nào?", "Chế độ kernel có toàn quyền truy cập phần cứng", "Chế độ người dùng nhanh hơn", "Không có khác biệt", "Chế độ kernel chỉ chạy ứng dụng", "A", "medium"),
    ("Lời gọi hệ thống (system call) là gì?", "Cơ chế để chương trình yêu cầu dịch vụ từ hệ điều hành", "Lệnh gọi hàm trong chương trình", "Thông báo lỗi", "Ngắt phần cứng", "A", "medium"),
    ("Ngắt (interrupt) trong hệ điều hành có tác dụng gì?", "Báo hiệu cho CPU tạm dừng để xử lý sự kiện khẩn cấp", "Kết thúc chương trình", "Xóa bộ nhớ", "Khởi động lại máy", "A", "medium"),
    ("Trình điều khiển thiết bị (driver) có chức năng gì?", "Giúp hệ điều hành giao tiếp với phần cứng cụ thể", "Quản lý tiến trình", "Lập lịch CPU", "Nén dữ liệu", "A", "easy"),
    ("Swap trong Linux có vai trò gì?", "Vùng đĩa dùng làm bộ nhớ mở rộng khi RAM đầy", "Thư mục chứa tệp tạm", "Vùng lưu nhật ký hệ thống", "Phân vùng khởi động", "A", "medium"),
    ("Hệ điều hành đa nhiệm (multitasking) nghĩa là gì?", "Chạy nhiều tiến trình đồng thời bằng cách chia sẻ CPU", "Chỉ chạy một chương trình", "Cần nhiều CPU", "Chạy nhiều hệ điều hành", "A", "easy"),
    ("Hệ điều hành thời gian thực (real-time OS) yêu cầu gì?", "Đáp ứng trong khoảng thời gian xác định nghiêm ngặt", "Giao diện đẹp", "Dung lượng lớn", "Nhiều ứng dụng", "A", "medium"),
    ("Máy ảo (Virtual Machine) là gì?", "Môi trường mô phỏng một máy tính hoàn chỉnh bằng phần mềm", "Máy tính không có màn hình", "Máy chủ đặt trên mây", "Phần mềm diệt virus", "A", "easy"),
    ("Container khác máy ảo ở điểm nào?", "Container chia sẻ kernel của hệ điều hành chủ nên nhẹ hơn", "Container nặng hơn máy ảo", "Container cần phần cứng riêng", "Không có khác biệt", "A", "medium"),
    ("Quá trình khởi động máy tính (boot) bắt đầu từ đâu?", "BIOS/UEFI kiểm tra phần cứng rồi nạp bộ nạp khởi động", "Hệ điều hành chạy trước", "Ứng dụng khởi động trước", "Từ ổ đĩa mạng", "A", "medium"),
    ("Tiến trình zombie trong Linux là gì?", "Tiến trình đã kết thúc nhưng chưa được tiến trình cha thu nhận", "Tiến trình chạy vô hạn", "Tiến trình bị nhiễm virus", "Tiến trình chiếm nhiều CPU", "A", "hard"),
    ("Lệnh ps trong Linux dùng để làm gì?", "Xem danh sách tiến trình đang chạy", "Xem dung lượng đĩa", "Xem cấu hình mạng", "Xem người dùng đăng nhập", "A", "easy"),
    ("Lệnh kill trong Linux dùng để làm gì?", "Gửi tín hiệu để kết thúc tiến trình", "Xóa tệp tin", "Tắt máy tính", "Đóng cửa sổ", "A", "easy"),
    ("Tệp trong Linux được phân quyền cho những đối tượng nào?", "Chủ sở hữu, nhóm và người khác", "Chỉ chủ sở hữu", "Chỉ quản trị viên", "Mọi người như nhau", "A", "medium"),
    ("Tài khoản root trong Linux có đặc quyền gì?", "Toàn quyền quản trị hệ thống", "Chỉ đọc tệp hệ thống", "Chỉ chạy ứng dụng", "Không có quyền đặc biệt", "A", "easy"),
    ("RAID 1 có đặc điểm gì?", "Sao chép dữ liệu giống nhau trên hai ổ đĩa để dự phòng", "Chia dữ liệu để tăng tốc", "Nén dữ liệu trước khi lưu", "Mã hóa toàn bộ ổ đĩa", "A", "hard"),
    ("Journaling trong hệ thống tệp có tác dụng gì?", "Ghi nhật ký thay đổi để phục hồi khi sự cố", "Tăng dung lượng đĩa", "Nén tệp tin", "Chống virus", "A", "hard"),
    ("Hệ điều hành Android được xây dựng dựa trên nhân nào?", "Linux", "Windows NT", "Unix BSD", "macOS", "A", "easy"),
    ("Chức năng bảo vệ bộ nhớ của hệ điều hành nhằm mục đích gì?", "Ngăn tiến trình này truy cập vùng nhớ của tiến trình khác", "Tăng dung lượng RAM", "Tăng tốc truy xuất", "Nén dữ liệu bộ nhớ", "A", "medium"),
    ("Cache trong hệ điều hành có vai trò gì?", "Lưu tạm dữ liệu hay dùng để tăng tốc truy xuất", "Lưu trữ vĩnh viễn", "Sao lưu dữ liệu", "Mã hóa thông tin", "A", "easy"),
]

LAP_TRINH_WEB = [
    ("HTML là ngôn ngữ dùng để làm gì?", "Xây dựng cấu trúc nội dung trang web", "Định dạng giao diện", "Xử lý logic phía máy chủ", "Quản lý cơ sở dữ liệu", "A", "easy"),
    ("CSS được dùng để làm gì?", "Định dạng và trình bày giao diện trang web", "Tạo cấu trúc trang", "Xử lý sự kiện người dùng", "Kết nối cơ sở dữ liệu", "A", "easy"),
    ("JavaScript chủ yếu dùng để làm gì?", "Tạo tương tác động cho trang web", "Định dạng màu sắc", "Tạo bảng dữ liệu", "Cấu hình máy chủ", "A", "easy"),
    ("Thẻ nào dùng để tạo tiêu đề lớn nhất trong HTML?", "h1", "h6", "title", "head", "A", "easy"),
    ("Thẻ nào dùng để tạo liên kết trong HTML?", "a", "link", "href", "url", "A", "easy"),
    ("Thuộc tính nào của thẻ a xác định địa chỉ liên kết?", "href", "src", "link", "url", "A", "easy"),
    ("Thẻ nào dùng để chèn hình ảnh?", "img", "image", "picture", "src", "A", "easy"),
    ("Thuộc tính alt của thẻ img có tác dụng gì?", "Hiển thị văn bản thay thế khi ảnh không tải được", "Đặt kích thước ảnh", "Đặt viền ảnh", "Tạo liên kết cho ảnh", "A", "medium"),
    ("Thẻ nào dùng để tạo danh sách không thứ tự?", "ul", "ol", "li", "dl", "A", "easy"),
    ("Thẻ form trong HTML dùng để làm gì?", "Tạo biểu mẫu thu thập dữ liệu từ người dùng", "Định dạng văn bản", "Chèn video", "Tạo bảng", "A", "easy"),
    ("Phương thức GET và POST khác nhau ở điểm nào?", "GET gửi dữ liệu qua URL, POST gửi trong thân yêu cầu", "POST nhanh hơn GET", "GET bảo mật hơn POST", "Không có khác biệt", "A", "medium"),
    ("Trong CSS, selector nào chọn phần tử theo id?", "Dấu thăng #", "Dấu chấm .", "Dấu sao *", "Dấu hai chấm :", "A", "easy"),
    ("Trong CSS, selector nào chọn phần tử theo class?", "Dấu chấm .", "Dấu thăng #", "Dấu sao *", "Dấu gạch dưới _", "A", "easy"),
    ("Thuộc tính CSS nào dùng để đổi màu chữ?", "color", "background-color", "font-size", "text-align", "A", "easy"),
    ("Mô hình hộp (Box Model) trong CSS gồm những thành phần nào?", "Content, padding, border và margin", "Header, body, footer", "Width, height, color", "Top, right, bottom, left", "A", "medium"),
    ("Thuộc tính display: flex dùng để làm gì?", "Bố trí phần tử theo mô hình flexbox linh hoạt", "Ẩn phần tử", "Cố định vị trí", "Tạo hiệu ứng chuyển động", "A", "medium"),
    ("Responsive design nghĩa là gì?", "Giao diện tự điều chỉnh phù hợp với nhiều kích thước màn hình", "Trang web tải nhanh", "Trang có nhiều hiệu ứng", "Trang hỗ trợ nhiều ngôn ngữ", "A", "easy"),
    ("Media query trong CSS dùng để làm gì?", "Áp dụng style theo điều kiện kích thước màn hình hoặc thiết bị", "Chèn hình ảnh", "Tạo hoạt ảnh", "Nhúng video", "A", "medium"),
    ("DOM là gì?", "Mô hình đối tượng tài liệu biểu diễn cấu trúc trang web", "Một ngôn ngữ lập trình", "Một giao thức mạng", "Một hệ quản trị CSDL", "A", "medium"),
    ("Phương thức nào trong JavaScript dùng để lấy phần tử theo id?", "document.getElementById()", "document.querySelectorAll()", "document.createElement()", "document.write()", "A", "easy"),
    ("Sự kiện onclick trong JavaScript xảy ra khi nào?", "Khi người dùng nhấp chuột vào phần tử", "Khi trang tải xong", "Khi di chuột qua", "Khi nhấn phím", "A", "easy"),
    ("Từ khóa nào khai báo biến có phạm vi khối trong JavaScript hiện đại?", "let", "var", "function", "global", "A", "medium"),
    ("Sự khác nhau giữa let và var là gì?", "let có phạm vi khối, var có phạm vi hàm", "var mới hơn let", "let không gán lại được", "Không có khác biệt", "A", "medium"),
    ("Từ khóa const trong JavaScript nghĩa là gì?", "Khai báo hằng không gán lại giá trị mới", "Khai báo biến toàn cục", "Khai báo hàm", "Khai báo mảng", "A", "easy"),
    ("JSON là gì?", "Định dạng trao đổi dữ liệu dạng văn bản dựa trên cú pháp đối tượng JavaScript", "Một ngôn ngữ lập trình", "Một cơ sở dữ liệu", "Một giao thức mạng", "A", "easy"),
    ("API REST sử dụng phương thức HTTP nào để lấy dữ liệu?", "GET", "POST", "PUT", "DELETE", "A", "easy"),
    ("Phương thức HTTP nào dùng để tạo mới tài nguyên theo chuẩn REST?", "POST", "GET", "HEAD", "OPTIONS", "A", "easy"),
    ("Mã trạng thái HTTP 404 nghĩa là gì?", "Không tìm thấy tài nguyên", "Thành công", "Lỗi máy chủ", "Không có quyền truy cập", "A", "easy"),
    ("Mã trạng thái HTTP 200 nghĩa là gì?", "Yêu cầu thành công", "Chuyển hướng", "Lỗi phía máy khách", "Lỗi máy chủ", "A", "easy"),
    ("Mã trạng thái HTTP 500 nghĩa là gì?", "Lỗi phía máy chủ", "Không tìm thấy trang", "Thành công", "Chưa xác thực", "A", "easy"),
    ("Mã trạng thái 401 và 403 khác nhau thế nào?", "401 là chưa xác thực, 403 là đã xác thực nhưng không đủ quyền", "Hai mã giống nhau", "401 là lỗi máy chủ", "403 là không tìm thấy", "A", "hard"),
    ("Cookie dùng để làm gì trong ứng dụng web?", "Lưu thông tin nhỏ trên trình duyệt người dùng", "Lưu dữ liệu trên máy chủ", "Tăng tốc tải trang", "Mã hóa kết nối", "A", "easy"),
    ("Session khác Cookie ở điểm nào?", "Session lưu ở phía máy chủ, Cookie lưu ở trình duyệt", "Session lưu ở trình duyệt", "Cookie an toàn hơn tuyệt đối", "Không có khác biệt", "A", "medium"),
    ("JWT được dùng để làm gì?", "Xác thực và truyền thông tin an toàn giữa các bên dưới dạng token", "Nén dữ liệu", "Vẽ giao diện", "Kết nối cơ sở dữ liệu", "A", "medium"),
    ("CORS là cơ chế gì?", "Kiểm soát việc chia sẻ tài nguyên giữa các nguồn gốc khác nhau", "Nén tệp tĩnh", "Mã hóa mật khẩu", "Cân bằng tải máy chủ", "A", "hard"),
    ("Tấn công XSS là gì?", "Chèn mã script độc hại vào trang web để chạy trên trình duyệt nạn nhân", "Làm quá tải máy chủ", "Chèn câu lệnh SQL", "Nghe lén gói tin", "A", "medium"),
    ("Cách phòng chống XSS hiệu quả là gì?", "Kiểm tra và mã hóa dữ liệu đầu vào trước khi hiển thị", "Đổi mật khẩu thường xuyên", "Dùng HTTPS là đủ", "Giới hạn số người dùng", "A", "medium"),
    ("Framework nào sau đây dùng cho frontend?", "Angular", "Express", "Django", "Laravel", "A", "easy"),
    ("Node.js là gì?", "Môi trường chạy JavaScript phía máy chủ", "Một trình duyệt web", "Một hệ quản trị CSDL", "Một ngôn ngữ lập trình mới", "A", "easy"),
    ("SPA (Single Page Application) có đặc điểm gì?", "Tải một lần và cập nhật nội dung động không tải lại toàn trang", "Chỉ có một trang duy nhất không đổi", "Không dùng JavaScript", "Không kết nối máy chủ", "A", "medium"),
    ("AJAX cho phép làm gì?", "Gửi và nhận dữ liệu từ máy chủ mà không tải lại trang", "Tạo hiệu ứng CSS", "Nén hình ảnh", "Tạo cơ sở dữ liệu", "A", "medium"),
    ("Thẻ meta viewport trong HTML có tác dụng gì?", "Điều chỉnh hiển thị phù hợp trên thiết bị di động", "Đặt tiêu đề trang", "Khai báo bộ ký tự", "Chèn CSS", "A", "medium"),
    ("Thuộc tính position: absolute trong CSS nghĩa là gì?", "Định vị tuyệt đối so với phần tử cha có position khác static", "Cố định trên màn hình", "Vị trí mặc định", "Nổi bên trái", "A", "hard"),
    ("Thuộc tính z-index dùng để làm gì?", "Xác định thứ tự chồng lớp của các phần tử", "Đặt độ trong suốt", "Đặt kích thước chữ", "Căn lề phần tử", "A", "medium"),
    ("Local Storage trong trình duyệt có đặc điểm gì?", "Lưu dữ liệu lâu dài trên trình duyệt cho tới khi bị xóa", "Mất khi đóng tab", "Lưu trên máy chủ", "Chỉ lưu được số", "A", "medium"),
    ("HTTPS khác HTTP ở điểm nào?", "Dữ liệu được mã hóa khi truyền", "Tốc độ nhanh hơn nhiều", "Không cần máy chủ", "Chỉ dùng cho trang tĩnh", "A", "easy"),
    ("Hàm bất đồng bộ async/await trong JavaScript dùng để làm gì?", "Viết mã xử lý bất đồng bộ dễ đọc hơn Promise lồng nhau", "Tăng tốc vòng lặp", "Khai báo biến", "Tạo phần tử DOM", "A", "medium"),
    ("Promise trong JavaScript đại diện cho điều gì?", "Kết quả của một thao tác bất đồng bộ sẽ hoàn thành trong tương lai", "Một biến hằng số", "Một vòng lặp", "Một sự kiện chuột", "A", "medium"),
    ("Công cụ nào thường dùng để kiểm tra lỗi trang web trong trình duyệt?", "DevTools (Công cụ dành cho nhà phát triển)", "Notepad", "Task Manager", "Control Panel", "A", "easy"),
    ("Semantic HTML mang lại lợi ích gì?", "Giúp máy tìm kiếm và trình đọc màn hình hiểu đúng cấu trúc nội dung", "Làm trang tải nhanh hơn nhiều lần", "Giảm dung lượng CSS", "Thay thế JavaScript", "A", "medium"),
]

CONG_NGHE_PHAN_MEM = [
    ("Công nghệ phần mềm là gì?", "Ngành áp dụng phương pháp kỹ thuật có hệ thống vào phát triển và bảo trì phần mềm", "Việc viết mã chương trình", "Thiết kế phần cứng máy tính", "Quản trị mạng", "A", "easy"),
    ("Vòng đời phát triển phần mềm gồm những giai đoạn cơ bản nào?", "Phân tích, thiết kế, cài đặt, kiểm thử và bảo trì", "Viết mã và chạy thử", "Mua và cài đặt", "Thiết kế và bán hàng", "A", "easy"),
    ("Mô hình thác nước (Waterfall) có đặc điểm gì?", "Các giai đoạn tuần tự, giai đoạn sau bắt đầu khi giai đoạn trước hoàn tất", "Lặp đi lặp lại liên tục", "Phát triển song song mọi giai đoạn", "Không cần tài liệu", "A", "easy"),
    ("Nhược điểm chính của mô hình thác nước là gì?", "Khó thay đổi yêu cầu khi đã sang giai đoạn sau", "Tốn quá nhiều nhân lực", "Không có tài liệu", "Không kiểm thử được", "A", "medium"),
    ("Mô hình Agile nhấn mạnh điều gì?", "Phát triển lặp, thích ứng thay đổi và hợp tác với khách hàng", "Tài liệu đầy đủ trước khi lập trình", "Kế hoạch cố định không đổi", "Bàn giao một lần duy nhất", "A", "easy"),
    ("Scrum là gì?", "Một khung làm việc thuộc Agile chia công việc thành các Sprint", "Một ngôn ngữ lập trình", "Một công cụ kiểm thử", "Một mô hình cơ sở dữ liệu", "A", "easy"),
    ("Sprint trong Scrum thường kéo dài bao lâu?", "1 đến 4 tuần", "1 ngày", "6 tháng", "1 năm", "A", "medium"),
    ("Vai trò Product Owner trong Scrum có nhiệm vụ gì?", "Quản lý và sắp xếp ưu tiên danh sách yêu cầu sản phẩm", "Viết mã chương trình", "Kiểm thử phần mềm", "Quản trị máy chủ", "A", "medium"),
    ("Scrum Master có vai trò gì?", "Hỗ trợ nhóm tuân thủ Scrum và loại bỏ trở ngại", "Quyết định mọi yêu cầu", "Trực tiếp lập trình", "Ký hợp đồng với khách hàng", "A", "medium"),
    ("Daily Standup trong Scrum có mục đích gì?", "Đồng bộ tiến độ và phát hiện trở ngại hàng ngày", "Báo cáo cho cấp trên", "Đánh giá năng lực cá nhân", "Lập kế hoạch dài hạn", "A", "medium"),
    ("Đặc tả yêu cầu phần mềm (SRS) là gì?", "Tài liệu mô tả đầy đủ chức năng và ràng buộc của hệ thống", "Mã nguồn chương trình", "Kế hoạch kiểm thử", "Sổ tay người dùng", "A", "medium"),
    ("Yêu cầu chức năng khác yêu cầu phi chức năng ở điểm nào?", "Yêu cầu chức năng mô tả hệ thống làm gì, phi chức năng mô tả làm tốt đến đâu", "Không có khác biệt", "Phi chức năng quan trọng hơn", "Chức năng chỉ có trong Agile", "A", "medium"),
    ("Ví dụ nào là yêu cầu phi chức năng?", "Hệ thống phải phản hồi dưới 2 giây", "Người dùng đăng nhập bằng tài khoản", "Hệ thống cho phép tạo đề thi", "Giáo viên nhập điểm", "A", "medium"),
    ("Biểu đồ Use Case dùng để mô tả gì?", "Chức năng hệ thống từ góc nhìn người sử dụng", "Cấu trúc lớp đối tượng", "Trình tự thời gian của thông điệp", "Trạng thái của đối tượng", "A", "easy"),
    ("Biểu đồ lớp (Class Diagram) mô tả gì?", "Cấu trúc tĩnh gồm các lớp và quan hệ giữa chúng", "Luồng công việc", "Trình tự tương tác", "Trạng thái hệ thống", "A", "easy"),
    ("Biểu đồ tuần tự (Sequence Diagram) mô tả gì?", "Trình tự trao đổi thông điệp giữa các đối tượng theo thời gian", "Cấu trúc dữ liệu", "Chức năng người dùng", "Kiến trúc triển khai", "A", "medium"),
    ("Biểu đồ hoạt động (Activity Diagram) dùng để mô tả gì?", "Luồng xử lý và các bước của một quy trình", "Quan hệ giữa các lớp", "Trạng thái đối tượng", "Cấu hình phần cứng", "A", "medium"),
    ("UML là gì?", "Ngôn ngữ mô hình hóa thống nhất dùng trong phân tích thiết kế phần mềm", "Một ngôn ngữ lập trình", "Một hệ quản trị CSDL", "Một công cụ kiểm thử", "A", "easy"),
    ("Kiến trúc ba lớp gồm những tầng nào?", "Trình diễn, nghiệp vụ và dữ liệu", "Nhập, xử lý, xuất", "Client, server, router", "Frontend, backend, database server", "A", "medium"),
    ("Mô hình MVC gồm những thành phần nào?", "Model, View, Controller", "Module, Version, Class", "Method, Variable, Constant", "Main, View, Config", "A", "easy"),
    ("Trong MVC, Model có nhiệm vụ gì?", "Quản lý dữ liệu và logic nghiệp vụ", "Hiển thị giao diện", "Điều phối yêu cầu người dùng", "Cấu hình máy chủ", "A", "medium"),
    ("Nguyên tắc SOLID trong thiết kế hướng đối tượng gồm mấy nguyên tắc?", "5", "3", "4", "7", "A", "medium"),
    ("Nguyên tắc trách nhiệm đơn (Single Responsibility) nghĩa là gì?", "Mỗi lớp chỉ nên có một lý do để thay đổi", "Một lớp làm được mọi việc", "Lớp phải kế thừa nhiều lớp", "Mọi phương thức đều công khai", "A", "medium"),
    ("Design Pattern là gì?", "Giải pháp mẫu đã được kiểm chứng cho vấn đề thiết kế thường gặp", "Mẫu giao diện người dùng", "Một loại biểu đồ UML", "Quy trình phát triển phần mềm", "A", "easy"),
    ("Mẫu Singleton đảm bảo điều gì?", "Một lớp chỉ có duy nhất một thể hiện trong toàn hệ thống", "Nhiều đối tượng cùng loại", "Đối tượng tự động hủy", "Kế thừa nhiều tầng", "A", "medium"),
    ("Mẫu Factory dùng để làm gì?", "Tạo đối tượng mà không cần chỉ rõ lớp cụ thể", "Quản lý kết nối CSDL", "Đồng bộ luồng", "Ghi nhật ký hệ thống", "A", "medium"),
    ("Kiểm thử hộp đen (Black-box testing) dựa trên điều gì?", "Chức năng và đầu vào đầu ra, không quan tâm mã nguồn bên trong", "Cấu trúc mã nguồn", "Sơ đồ luồng điều khiển", "Độ phủ câu lệnh", "A", "medium"),
    ("Kiểm thử hộp trắng (White-box testing) dựa trên điều gì?", "Cấu trúc bên trong của mã nguồn", "Chỉ giao diện người dùng", "Ý kiến khách hàng", "Tài liệu yêu cầu", "A", "medium"),
    ("Kiểm thử đơn vị (Unit Test) kiểm tra đối tượng nào?", "Từng hàm hoặc thành phần nhỏ nhất một cách độc lập", "Toàn bộ hệ thống", "Giao diện người dùng", "Hiệu năng máy chủ", "A", "easy"),
    ("Kiểm thử tích hợp (Integration Test) nhằm mục đích gì?", "Kiểm tra sự phối hợp giữa các thành phần đã tích hợp", "Kiểm tra từng hàm riêng lẻ", "Đo tốc độ phản hồi", "Kiểm tra giao diện màu sắc", "A", "medium"),
    ("Kiểm thử hồi quy (Regression Test) dùng để làm gì?", "Đảm bảo thay đổi mới không làm hỏng chức năng đang chạy tốt", "Kiểm tra hiệu năng", "Kiểm tra bảo mật", "Kiểm tra giao diện", "A", "medium"),
    ("Kiểm thử chấp nhận (UAT) do ai thực hiện?", "Người dùng cuối hoặc khách hàng", "Lập trình viên", "Quản trị mạng", "Nhà cung cấp máy chủ", "A", "easy"),
    ("Test case gồm những thành phần cơ bản nào?", "Điều kiện đầu vào, các bước thực hiện và kết quả mong đợi", "Chỉ mô tả lỗi", "Mã nguồn chương trình", "Sơ đồ thiết kế", "A", "easy"),
    ("TDD (Test-Driven Development) nghĩa là gì?", "Viết kiểm thử trước rồi mới viết mã để kiểm thử đạt", "Kiểm thử sau khi hoàn thành sản phẩm", "Chỉ kiểm thử thủ công", "Không cần kiểm thử", "A", "medium"),
    ("Lỗi (bug) khác lỗi vận hành (failure) ở điểm nào?", "Bug là khiếm khuyết trong mã, failure là biểu hiện sai khi chạy", "Hai khái niệm giống nhau", "Bug chỉ xuất hiện khi chạy", "Failure nằm trong mã nguồn", "A", "hard"),
    ("Quản lý phiên bản mã nguồn dùng công cụ nào phổ biến nhất?", "Git", "Excel", "Photoshop", "MySQL", "A", "easy"),
    ("Lệnh git commit dùng để làm gì?", "Ghi lại thay đổi vào lịch sử kho mã nguồn", "Tải mã về máy", "Đẩy mã lên máy chủ", "Tạo nhánh mới", "A", "easy"),
    ("Nhánh (branch) trong Git dùng để làm gì?", "Phát triển tính năng song song mà không ảnh hưởng nhánh chính", "Sao lưu toàn bộ dự án", "Xóa lịch sử thay đổi", "Nén mã nguồn", "A", "medium"),
    ("CI/CD là gì?", "Tích hợp liên tục và triển khai liên tục để tự động hóa quy trình phát hành", "Một mẫu thiết kế", "Một loại cơ sở dữ liệu", "Một ngôn ngữ lập trình", "A", "medium"),
    ("Bảo trì phần mềm gồm những loại nào?", "Sửa lỗi, thích ứng, hoàn thiện và phòng ngừa", "Chỉ sửa lỗi", "Chỉ thêm chức năng", "Chỉ nâng cấp phần cứng", "A", "hard"),
    ("Chi phí bảo trì thường chiếm tỷ lệ thế nào trong tổng chi phí phần mềm?", "Phần lớn, thường trên 50%", "Dưới 5%", "Khoảng 10%", "Không đáng kể", "A", "medium"),
    ("Nợ kỹ thuật (technical debt) là gì?", "Chi phí phát sinh về sau do chọn giải pháp nhanh thay vì giải pháp tốt", "Khoản vay mua phần mềm", "Chi phí bản quyền", "Tiền lương lập trình viên", "A", "medium"),
    ("Refactoring là gì?", "Cải tiến cấu trúc mã nguồn mà không thay đổi hành vi bên ngoài", "Thêm chức năng mới", "Sửa lỗi nghiêm trọng", "Viết lại toàn bộ hệ thống", "A", "medium"),
    ("Tài liệu nào cần bàn giao cho người dùng cuối?", "Hướng dẫn sử dụng", "Mã nguồn chi tiết", "Biểu đồ lớp", "Kế hoạch kiểm thử nội bộ", "A", "easy"),
    ("Ước lượng chi phí phần mềm bằng phương pháp COCOMO dựa trên yếu tố nào?", "Quy mô mã nguồn và độ phức tạp dự án", "Số lượng khách hàng", "Giá phần cứng", "Thời gian bảo hành", "A", "hard"),
    ("Rủi ro trong dự án phần mềm nên được xử lý thế nào?", "Nhận diện sớm, đánh giá và có kế hoạch ứng phó", "Bỏ qua cho đến khi xảy ra", "Chỉ báo cáo khi kết thúc", "Chuyển hết cho khách hàng", "A", "medium"),
    ("Chất lượng phần mềm được đánh giá qua tiêu chí nào?", "Tính đúng đắn, tin cậy, hiệu quả, dễ bảo trì và dễ sử dụng", "Chỉ tốc độ chạy", "Chỉ giao diện đẹp", "Chỉ số dòng mã", "A", "easy"),
    ("Prototype (mẫu thử) trong phát triển phần mềm dùng để làm gì?", "Làm rõ yêu cầu và lấy phản hồi sớm từ người dùng", "Bàn giao sản phẩm cuối", "Thay thế tài liệu thiết kế", "Kiểm thử hiệu năng", "A", "medium"),
    ("Mô hình xoắn ốc (Spiral) nhấn mạnh yếu tố nào?", "Phân tích và quản lý rủi ro qua từng vòng lặp", "Tuần tự nghiêm ngặt", "Không cần tài liệu", "Bàn giao một lần", "A", "hard"),
    ("Kiểm thử phi chức năng bao gồm loại nào?", "Kiểm thử hiệu năng, bảo mật và khả năng sử dụng", "Kiểm thử đơn vị", "Kiểm thử chức năng đăng nhập", "Kiểm thử tích hợp", "A", "medium"),
]

DATA = {
    'Lập trình C/C++': LAP_TRINH_C,
    'Cấu trúc dữ liệu và giải thuật': CTDL_GT,
    'Cơ sở dữ liệu nâng cao': CO_SO_DU_LIEU,
    'Mạng máy tính': MANG_MAY_TINH,
    'Hệ điều hành': HE_DIEU_HANH,
    'Lập trình Web nâng cao': LAP_TRINH_WEB,
    'Công nghệ phần mềm': CONG_NGHE_PHAN_MEM,
}
