# -*- coding: utf-8 -*-
"""Nhóm đại cương: Pháp luật, GDQP, Tiếng Anh, Tin học đại cương, Kỹ năng mềm."""

PHAP_LUAT = [
    ("Nhà nước có đặc trưng cơ bản nào sau đây?", "Có quyền lực công cộng đặc biệt và chủ quyền quốc gia", "Do một cá nhân sở hữu", "Không cần bộ máy cưỡng chế", "Không có lãnh thổ xác định", "A", "easy"),
    ("Pháp luật là gì?", "Hệ thống quy tắc xử sự chung do Nhà nước ban hành và bảo đảm thực hiện", "Các quy ước của làng xã", "Quy định nội bộ của doanh nghiệp", "Chuẩn mực đạo đức xã hội", "A", "easy"),
    ("Thuộc tính nào sau đây là của pháp luật?", "Tính quy phạm phổ biến, tính xác định chặt chẽ về hình thức, tính cưỡng chế", "Tính tự nguyện tuyệt đối", "Tính địa phương", "Tính tạm thời", "A", "medium"),
    ("Văn bản quy phạm pháp luật nào có hiệu lực pháp lý cao nhất ở Việt Nam?", "Hiến pháp", "Luật", "Nghị định", "Thông tư", "A", "easy"),
    ("Cơ quan nào có quyền ban hành Hiến pháp và luật ở Việt Nam?", "Quốc hội", "Chính phủ", "Tòa án nhân dân tối cao", "Chủ tịch nước", "A", "easy"),
    ("Chính phủ ban hành loại văn bản nào?", "Nghị định", "Luật", "Hiến pháp", "Nghị quyết của Quốc hội", "A", "easy"),
    ("Quan hệ pháp luật gồm những thành phần nào?", "Chủ thể, khách thể và nội dung", "Nguyên đơn và bị đơn", "Quyền và nghĩa vụ", "Hành vi và hậu quả", "A", "medium"),
    ("Năng lực pháp luật của cá nhân có từ khi nào?", "Từ khi sinh ra", "Từ khi đủ 6 tuổi", "Từ khi đủ 18 tuổi", "Từ khi có việc làm", "A", "medium"),
    ("Năng lực hành vi dân sự đầy đủ của cá nhân có từ bao nhiêu tuổi?", "Đủ 15 tuổi", "Đủ 16 tuổi", "Đủ 18 tuổi", "Đủ 21 tuổi", "C", "easy"),
    ("Vi phạm pháp luật có mấy dấu hiệu cơ bản?", "Hai dấu hiệu", "Ba dấu hiệu", "Bốn dấu hiệu", "Năm dấu hiệu", "C", "medium"),
    ("Cấu thành vi phạm pháp luật gồm những yếu tố nào?", "Mặt khách quan, mặt chủ quan, chủ thể và khách thể", "Nguyên nhân và kết quả", "Hành vi và hình phạt", "Lỗi và thiệt hại", "A", "medium"),
    ("Lỗi trong vi phạm pháp luật được chia thành mấy loại chính?", "Lỗi cố ý và lỗi vô ý", "Lỗi nặng và lỗi nhẹ", "Lỗi cá nhân và lỗi tập thể", "Lỗi trực tiếp và lỗi gián tiếp", "A", "easy"),
    ("Trách nhiệm pháp lý nào nghiêm khắc nhất?", "Trách nhiệm hình sự", "Trách nhiệm hành chính", "Trách nhiệm dân sự", "Trách nhiệm kỷ luật", "A", "easy"),
    ("Tội phạm theo Bộ luật Hình sự Việt Nam là gì?", "Hành vi nguy hiểm cho xã hội được quy định trong Bộ luật Hình sự", "Mọi hành vi trái đạo đức", "Hành vi vi phạm hợp đồng", "Hành vi gây thiệt hại tài sản", "A", "medium"),
    ("Tuổi chịu trách nhiệm hình sự đầy đủ theo pháp luật Việt Nam là bao nhiêu?", "Từ đủ 14 tuổi", "Từ đủ 16 tuổi", "Từ đủ 18 tuổi", "Từ đủ 20 tuổi", "B", "medium"),
    ("Hình phạt nào là hình phạt chính trong luật hình sự?", "Tù có thời hạn", "Cấm cư trú", "Tịch thu tài sản", "Quản chế", "A", "medium"),
    ("Nguyên tắc suy đoán vô tội có nội dung gì?", "Người bị buộc tội được coi là không có tội cho đến khi có bản án kết tội có hiệu lực", "Người bị bắt là có tội", "Tòa án phải xử theo dư luận", "Bị cáo phải tự chứng minh mình vô tội", "A", "medium"),
    ("Quan hệ dân sự dựa trên nguyên tắc nào?", "Bình đẳng, tự nguyện, thiện chí, trung thực", "Mệnh lệnh phục tùng", "Ưu tiên bên có tài sản lớn", "Do cơ quan nhà nước quyết định", "A", "easy"),
    ("Hợp đồng dân sự là gì?", "Sự thỏa thuận giữa các bên về xác lập, thay đổi, chấm dứt quyền và nghĩa vụ", "Mệnh lệnh của cơ quan nhà nước", "Bản cam kết một chiều", "Quy định nội bộ tổ chức", "A", "easy"),
    ("Điều kiện nào làm hợp đồng vô hiệu?", "Vi phạm điều cấm của luật hoặc trái đạo đức xã hội", "Có nhiều điều khoản", "Được lập bằng văn bản", "Có người làm chứng", "A", "medium"),
    ("Quyền sở hữu bao gồm những quyền năng nào?", "Chiếm hữu, sử dụng và định đoạt", "Mua, bán và cho thuê", "Quản lý và bảo vệ", "Cầm cố và thế chấp", "A", "easy"),
    ("Thừa kế theo pháp luật được áp dụng khi nào?", "Khi không có di chúc hoặc di chúc không hợp pháp", "Khi có di chúc rõ ràng", "Khi người chết còn nợ", "Khi có tranh chấp tài sản", "A", "medium"),
    ("Hàng thừa kế thứ nhất gồm những ai?", "Vợ chồng, cha mẹ đẻ, cha mẹ nuôi, con đẻ, con nuôi", "Ông bà, anh chị em ruột", "Cô dì chú bác", "Cháu ruột", "A", "medium"),
    ("Độ tuổi kết hôn theo Luật Hôn nhân và Gia đình Việt Nam là bao nhiêu?", "Nam từ đủ 20, nữ từ đủ 18", "Nam từ đủ 18, nữ từ đủ 16", "Cả hai từ đủ 18", "Cả hai từ đủ 20", "A", "easy"),
    ("Hành vi nào bị cấm trong hôn nhân?", "Kết hôn giả tạo, tảo hôn, cưỡng ép kết hôn", "Kết hôn khác tôn giáo", "Kết hôn với người nước ngoài", "Kết hôn muộn", "A", "easy"),
    ("Vi phạm hành chính khác tội phạm ở điểm nào?", "Mức độ nguy hiểm cho xã hội thấp hơn", "Không có lỗi", "Không bị xử lý", "Chỉ do tổ chức thực hiện", "A", "medium"),
    ("Hình thức xử phạt chính trong xử lý vi phạm hành chính là gì?", "Cảnh cáo và phạt tiền", "Tù giam", "Tử hình", "Cải tạo không giam giữ", "A", "easy"),
    ("Hợp đồng lao động phải có nội dung chủ yếu nào?", "Công việc, địa điểm, thời hạn, tiền lương và điều kiện làm việc", "Chỉ cần tiền lương", "Chỉ cần thời hạn", "Chỉ cần chữ ký hai bên", "A", "easy"),
    ("Thời giờ làm việc bình thường theo Bộ luật Lao động là bao nhiêu?", "Không quá 8 giờ/ngày và 48 giờ/tuần", "Không quá 10 giờ/ngày", "Không quá 6 giờ/ngày", "Không giới hạn", "A", "easy"),
    ("Người lao động có quyền đơn phương chấm dứt hợp đồng khi nào?", "Khi báo trước theo đúng thời hạn luật định", "Bất cứ lúc nào không cần báo", "Chỉ khi được người sử dụng lao động đồng ý", "Không bao giờ được phép", "A", "medium"),
    ("Cơ quan nào thực hiện quyền tư pháp ở Việt Nam?", "Tòa án nhân dân", "Quốc hội", "Chính phủ", "Viện kiểm sát nhân dân", "A", "easy"),
    ("Viện kiểm sát nhân dân có chức năng gì?", "Thực hành quyền công tố và kiểm sát hoạt động tư pháp", "Xét xử các vụ án", "Ban hành luật", "Điều hành kinh tế", "A", "medium"),
    ("Hiến pháp hiện hành của Việt Nam được ban hành năm nào?", "1980", "1992", "2013", "2015", "C", "easy"),
    ("Quyền con người theo Hiến pháp 2013 được quy định như thế nào?", "Được công nhận, tôn trọng, bảo vệ và bảo đảm theo Hiến pháp và pháp luật", "Chỉ dành cho công dân Việt Nam", "Do Chính phủ quyết định", "Không được ghi nhận", "A", "medium"),
    ("Nghĩa vụ cơ bản của công dân Việt Nam gồm gì?", "Trung thành với Tổ quốc, bảo vệ Tổ quốc, nộp thuế, tuân theo Hiến pháp và pháp luật", "Chỉ nộp thuế", "Chỉ đi bầu cử", "Chỉ tham gia lao động", "A", "easy"),
    ("Doanh nghiệp tư nhân có đặc điểm gì?", "Do một cá nhân làm chủ và tự chịu trách nhiệm bằng toàn bộ tài sản của mình", "Có tư cách pháp nhân", "Do nhiều người góp vốn", "Được phát hành cổ phiếu", "A", "medium"),
    ("Công ty cổ phần có đặc điểm nào?", "Vốn điều lệ chia thành cổ phần, cổ đông chịu trách nhiệm hữu hạn", "Chỉ có một chủ sở hữu", "Không có tư cách pháp nhân", "Không được chuyển nhượng vốn", "A", "medium"),
    ("Sở hữu trí tuệ bao gồm những đối tượng nào?", "Quyền tác giả, quyền sở hữu công nghiệp và quyền đối với giống cây trồng", "Chỉ nhãn hiệu hàng hóa", "Chỉ sáng chế", "Chỉ tác phẩm văn học", "A", "medium"),
    ("Thời hiệu khởi kiện vụ án dân sự thông thường là bao lâu?", "2 năm kể từ ngày quyền lợi bị xâm phạm", "6 tháng", "5 năm", "Không có thời hiệu", "A", "hard"),
    ("Nguyên tắc pháp chế xã hội chủ nghĩa đòi hỏi điều gì?", "Mọi chủ thể phải tuân thủ pháp luật một cách nghiêm chỉnh và thống nhất", "Chỉ cơ quan nhà nước phải tuân thủ", "Chỉ áp dụng với công dân", "Có thể linh hoạt bỏ qua", "A", "medium"),
    ("Áp dụng pháp luật là hoạt động của ai?", "Cơ quan nhà nước có thẩm quyền hoặc người được ủy quyền", "Mọi công dân", "Các tổ chức xã hội", "Doanh nghiệp tư nhân", "A", "medium"),
    ("Hành vi tham nhũng theo Luật Phòng chống tham nhũng là gì?", "Hành vi của người có chức vụ quyền hạn lợi dụng chức vụ vì vụ lợi", "Mọi hành vi vi phạm pháp luật", "Hành vi trốn thuế", "Hành vi gian lận thương mại", "A", "medium"),
    ("Quyền khiếu nại của công dân nhằm mục đích gì?", "Đề nghị xem xét lại quyết định hành chính xâm phạm quyền lợi hợp pháp", "Tố giác tội phạm", "Yêu cầu bồi thường thiệt hại dân sự", "Đề nghị ban hành luật mới", "A", "medium"),
    ("Tố cáo khác khiếu nại ở điểm nào?", "Tố cáo là báo cho cơ quan có thẩm quyền về hành vi vi phạm pháp luật của người khác", "Tố cáo chỉ liên quan quyền lợi bản thân", "Tố cáo do cơ quan nhà nước thực hiện", "Hai khái niệm giống nhau", "A", "medium"),
    ("Bảo hiểm xã hội bắt buộc áp dụng cho đối tượng nào?", "Người lao động có hợp đồng lao động từ đủ 1 tháng trở lên", "Chỉ cán bộ công chức", "Chỉ người trên 40 tuổi", "Người lao động tự do", "A", "medium"),
    ("Thuế thu nhập cá nhân đánh vào đối tượng nào?", "Thu nhập chịu thuế của cá nhân sau khi trừ các khoản giảm trừ", "Toàn bộ thu nhập không trừ gì", "Chỉ thu nhập từ kinh doanh", "Chỉ thu nhập từ lương", "A", "medium"),
    ("Đất đai ở Việt Nam thuộc hình thức sở hữu nào?", "Sở hữu toàn dân do Nhà nước đại diện chủ sở hữu", "Sở hữu tư nhân", "Sở hữu tập thể", "Sở hữu hỗn hợp", "A", "easy"),
    ("Người sử dụng đất có quyền nào sau đây?", "Chuyển nhượng, cho thuê, thừa kế, thế chấp quyền sử dụng đất", "Bán đứt quyền sở hữu đất", "Tự ý chuyển mục đích sử dụng", "Khai thác khoáng sản tùy ý", "A", "medium"),
    ("Bảo vệ môi trường là trách nhiệm của ai?", "Của mọi cơ quan, tổ chức, cá nhân", "Chỉ của cơ quan nhà nước", "Chỉ của doanh nghiệp sản xuất", "Chỉ của tổ chức quốc tế", "A", "easy"),
    ("Vi phạm pháp luật về an toàn giao thông thuộc loại vi phạm nào phổ biến nhất?", "Vi phạm hành chính", "Vi phạm hình sự", "Vi phạm dân sự", "Vi phạm kỷ luật", "A", "easy"),
    ("Mục đích của pháp luật trong nhà nước pháp quyền là gì?", "Bảo vệ quyền con người, quyền công dân và trật tự xã hội", "Trừng phạt người vi phạm", "Tăng thu ngân sách", "Củng cố quyền lực cá nhân", "A", "easy"),
]

GDQP = [
    ("Quốc phòng toàn dân là gì?", "Sức mạnh quốc phòng của đất nước được xây dựng trên nền tảng toàn dân", "Chỉ do quân đội đảm nhiệm", "Do lực lượng công an thực hiện", "Do các doanh nghiệp quốc phòng lo", "A", "easy"),
    ("Lực lượng vũ trang nhân dân Việt Nam gồm những thành phần nào?", "Quân đội nhân dân, Công an nhân dân và Dân quân tự vệ", "Chỉ Quân đội nhân dân", "Quân đội và cảnh sát biển", "Quân đội và lực lượng dự bị", "A", "easy"),
    ("Quân đội nhân dân Việt Nam được thành lập ngày nào?", "22/12/1944", "19/8/1945", "2/9/1945", "7/5/1954", "A", "easy"),
    ("Chức năng của Quân đội nhân dân Việt Nam là gì?", "Đội quân chiến đấu, đội quân công tác và đội quân lao động sản xuất", "Chỉ chiến đấu bảo vệ Tổ quốc", "Chỉ làm kinh tế", "Chỉ giữ gìn trật tự xã hội", "A", "medium"),
    ("Nguyên tắc lãnh đạo của Đảng đối với Quân đội là gì?", "Tuyệt đối, trực tiếp về mọi mặt", "Gián tiếp thông qua Chính phủ", "Chỉ về mặt chính trị", "Phân cấp cho địa phương", "A", "medium"),
    ("Chiến tranh nhân dân bảo vệ Tổ quốc có tính chất gì?", "Toàn dân, toàn diện, chính nghĩa và tự vệ", "Chỉ dựa vào quân chủ lực", "Mang tính tiến công xâm lược", "Chỉ diễn ra trên bộ", "A", "medium"),
    ("Thế trận chiến tranh nhân dân được xây dựng như thế nào?", "Rộng khắp cả nước, có trọng tâm trọng điểm", "Chỉ tập trung ở biên giới", "Chỉ ở các thành phố lớn", "Chỉ ở vùng biển đảo", "A", "medium"),
    ("Khu vực phòng thủ tỉnh, thành phố có vai trò gì?", "Là bộ phận hợp thành thế trận quốc phòng toàn dân ở địa phương", "Chỉ là nơi đóng quân", "Chỉ để huấn luyện", "Chỉ hoạt động khi có chiến tranh", "A", "medium"),
    ("Nghĩa vụ quân sự là gì?", "Nghĩa vụ vẻ vang của công dân phục vụ trong Quân đội nhân dân", "Quyền tự nguyện của công dân", "Nghĩa vụ chỉ của nam giới trên 25 tuổi", "Công việc có trả lương như lao động thường", "A", "easy"),
    ("Độ tuổi gọi nhập ngũ trong thời bình là bao nhiêu?", "Từ đủ 18 tuổi đến hết 25 tuổi", "Từ đủ 16 đến 20 tuổi", "Từ đủ 20 đến 30 tuổi", "Từ đủ 21 đến 27 tuổi", "A", "medium"),
    ("Thời hạn phục vụ tại ngũ trong thời bình của hạ sĩ quan, binh sĩ là bao lâu?", "18 tháng", "24 tháng", "30 tháng", "36 tháng", "B", "medium"),
    ("Dân quân tự vệ là lực lượng gì?", "Lực lượng vũ trang quần chúng không thoát ly sản xuất, công tác", "Lực lượng quân đội chính quy", "Lực lượng cảnh sát cơ động", "Lực lượng bảo vệ dân phố", "A", "medium"),
    ("Chủ quyền lãnh thổ quốc gia bao gồm những bộ phận nào?", "Vùng đất, vùng nước, vùng trời và lòng đất", "Chỉ vùng đất liền", "Chỉ vùng biển", "Vùng đất và vùng biển", "A", "medium"),
    ("Lãnh hải của Việt Nam rộng bao nhiêu hải lý tính từ đường cơ sở?", "12 hải lý", "24 hải lý", "200 hải lý", "350 hải lý", "A", "medium"),
    ("Vùng đặc quyền kinh tế của Việt Nam rộng bao nhiêu hải lý?", "12 hải lý", "24 hải lý", "200 hải lý", "300 hải lý", "C", "medium"),
    ("Vùng tiếp giáp lãnh hải rộng bao nhiêu hải lý tính từ đường cơ sở?", "12 hải lý", "24 hải lý", "50 hải lý", "200 hải lý", "B", "hard"),
    ("Hai quần đảo lớn thuộc chủ quyền Việt Nam trên Biển Đông là gì?", "Hoàng Sa và Trường Sa", "Phú Quốc và Côn Đảo", "Cát Bà và Bạch Long Vĩ", "Lý Sơn và Phú Quý", "A", "easy"),
    ("Công ước quốc tế nào là cơ sở pháp lý về biển mà Việt Nam là thành viên?", "Công ước Luật Biển năm 1982 (UNCLOS)", "Công ước Geneva 1949", "Hiến chương ASEAN", "Công ước Viên 1969", "A", "medium"),
    ("Bảo vệ Tổ quốc Việt Nam xã hội chủ nghĩa bao gồm những nội dung nào?", "Bảo vệ độc lập chủ quyền, chế độ, Đảng, Nhà nước và nhân dân", "Chỉ bảo vệ biên giới", "Chỉ chống xâm lược từ bên ngoài", "Chỉ giữ gìn an ninh trật tự", "A", "medium"),
    ("Diễn biến hòa bình là gì?", "Chiến lược chống phá bằng biện pháp phi vũ trang trên nhiều lĩnh vực", "Một cuộc chiến tranh cục bộ", "Quá trình đàm phán hòa bình", "Chính sách ngoại giao mềm dẻo", "A", "medium"),
    ("Bạo loạn lật đổ thường được tiến hành bằng cách nào?", "Kích động quần chúng gây rối, dùng bạo lực chống chính quyền", "Đàm phán chính trị", "Bầu cử dân chủ", "Vận động hành lang quốc tế", "A", "medium"),
    ("Biện pháp phòng chống diễn biến hòa bình hiệu quả nhất là gì?", "Xây dựng đất nước vững mạnh toàn diện, giữ vững lòng dân", "Đóng cửa biên giới", "Cấm mọi thông tin nước ngoài", "Tăng cường vũ khí hiện đại", "A", "medium"),
    ("An ninh quốc gia là gì?", "Sự ổn định, phát triển bền vững của chế độ và Nhà nước, bất khả xâm phạm của Tổ quốc", "Chỉ là trật tự an toàn xã hội", "Chỉ liên quan đến quân sự", "Chỉ là an ninh kinh tế", "A", "medium"),
    ("Nền quốc phòng toàn dân và an ninh nhân dân có quan hệ thế nào?", "Gắn bó chặt chẽ, kết hợp với nhau trong bảo vệ Tổ quốc", "Hoàn toàn tách biệt", "Đối lập nhau", "Không liên quan", "A", "easy"),
    ("Kết hợp kinh tế với quốc phòng nhằm mục đích gì?", "Phát triển kinh tế gắn với tăng cường tiềm lực quốc phòng", "Chỉ phát triển công nghiệp quân sự", "Giảm chi tiêu quốc phòng", "Chuyển quân đội sang làm kinh tế", "A", "medium"),
    ("Đường lối đối ngoại quốc phòng của Việt Nam theo phương châm nào?", "Bốn không: không liên minh quân sự, không theo nước này chống nước kia, không cho đặt căn cứ quân sự, không dùng vũ lực trước", "Liên minh với các cường quốc", "Trung lập tuyệt đối", "Đóng cửa hoàn toàn", "A", "hard"),
    ("Vũ khí công nghệ cao có đặc điểm gì?", "Độ chính xác cao, uy lực lớn, tầm xa và khả năng tự động hóa", "Giá thành rẻ", "Dễ chế tạo", "Không cần điều khiển", "A", "easy"),
    ("Biện pháp phòng chống vũ khí công nghệ cao là gì?", "Ngụy trang, nghi binh, phân tán và cơ động", "Tập trung lực lượng một chỗ", "Đứng yên tại chỗ", "Chỉ dùng vũ khí hiện đại đối kháng", "A", "medium"),
    ("Ba loại hình tác chiến cơ bản trong nghệ thuật quân sự Việt Nam là gì?", "Tiến công, phòng ngự và phản công", "Bao vây, cô lập và tiêu diệt", "Tấn công, rút lui và cố thủ", "Đánh nhanh, đánh chắc và đánh dài", "A", "medium"),
    ("Tư tưởng chỉ đạo tác chiến của Việt Nam là gì?", "Lấy nhỏ thắng lớn, lấy ít địch nhiều, lấy chất lượng cao thắng số lượng đông", "Dùng số đông áp đảo", "Chỉ phòng thủ bị động", "Dựa hoàn toàn vào vũ khí hiện đại", "A", "medium"),
    ("Kỹ thuật băng bó vết thương nhằm mục đích gì?", "Cầm máu, chống nhiễm khuẩn và giảm đau", "Chỉ để che vết thương", "Làm liền da ngay lập tức", "Thay thế phẫu thuật", "A", "easy"),
    ("Khi gặp người bị chảy máu động mạch, cần làm gì trước tiên?", "Ép chặt trên đường đi của động mạch phía trên vết thương", "Rửa vết thương bằng nước", "Đưa đi bệnh viện ngay không sơ cứu", "Bôi thuốc mỡ", "A", "medium"),
    ("Thứ tự ưu tiên khi cấp cứu nhiều nạn nhân là gì?", "Ưu tiên người nguy kịch có khả năng cứu sống", "Ưu tiên người kêu to nhất", "Ưu tiên người đến trước", "Ưu tiên người quen biết", "A", "medium"),
    ("Đội hình cơ bản trong điều lệnh đội ngũ gồm những gì?", "Hàng dọc và hàng ngang", "Vòng tròn và hình vuông", "Chữ V và chữ U", "Tự do theo nhóm", "A", "easy"),
    ("Bắn súng tiểu liên AK ở tư thế nằm có ưu điểm gì?", "Vững chắc, độ chính xác cao và ít bị lộ", "Cơ động nhanh nhất", "Quan sát rộng nhất", "Bắn được nhiều đạn nhất", "A", "medium"),
    ("Yếu tố nào quyết định độ chính xác khi bắn súng?", "Ngắm đúng, giữ súng vững và bóp cò êm", "Bóp cò thật nhanh", "Nín thở càng lâu càng tốt", "Dùng nhiều đạn", "A", "medium"),
    ("Lịch sử nghệ thuật đánh giặc của dân tộc ta nổi bật với truyền thống nào?", "Toàn dân đánh giặc, đánh giặc bằng mưu trí sáng tạo", "Chỉ dùng quân đội chuyên nghiệp", "Dựa vào viện trợ nước ngoài", "Phòng thủ trong thành lũy", "A", "easy"),
    ("Chiến thắng Bạch Đằng năm 938 gắn với tên tuổi ai?", "Ngô Quyền", "Lý Thường Kiệt", "Trần Hưng Đạo", "Lê Lợi", "A", "easy"),
    ("Ba lần đánh thắng quân Nguyên - Mông gắn với triều đại nào?", "Nhà Trần", "Nhà Lý", "Nhà Lê", "Nhà Nguyễn", "A", "easy"),
    ("Chiến thuật nổi tiếng của Trần Hưng Đạo là gì?", "Vườn không nhà trống, lấy đoản binh chế trường trận", "Đánh nhanh thắng nhanh", "Cố thủ trong thành", "Đầu hàng để bảo toàn lực lượng", "A", "medium"),
    ("Công tác quốc phòng ở địa phương do ai chịu trách nhiệm chính?", "Cấp ủy Đảng và chính quyền địa phương", "Chỉ cơ quan quân sự", "Bộ Quốc phòng trực tiếp", "Các doanh nghiệp trên địa bàn", "A", "medium"),
    ("Phòng thủ dân sự nhằm mục đích gì?", "Phòng chống, khắc phục hậu quả chiến tranh, thảm họa và thiên tai", "Chỉ chống chiến tranh hạt nhân", "Chỉ bảo vệ cơ quan nhà nước", "Chỉ hoạt động thời chiến", "A", "medium"),
    ("Sinh viên có trách nhiệm gì với nhiệm vụ bảo vệ Tổ quốc?", "Học tập tốt, rèn luyện sức khỏe, sẵn sàng thực hiện nghĩa vụ quân sự", "Không có trách nhiệm gì", "Chỉ cần đóng thuế", "Chỉ tham gia khi có chiến tranh", "A", "easy"),
    ("Mục tiêu của giáo dục quốc phòng và an ninh cho sinh viên là gì?", "Trang bị kiến thức quốc phòng an ninh và kỹ năng quân sự cần thiết", "Đào tạo thành sĩ quan chuyên nghiệp", "Chỉ rèn luyện thể lực", "Chỉ học lý thuyết chính trị", "A", "easy"),
    ("Trật tự an toàn xã hội bao gồm nội dung nào?", "Trạng thái xã hội có kỷ cương, mọi người sống và làm việc theo pháp luật", "Chỉ là an toàn giao thông", "Chỉ là phòng cháy chữa cháy", "Chỉ là chống tội phạm hình sự", "A", "medium"),
    ("Tội phạm sử dụng công nghệ cao có đặc điểm gì?", "Sử dụng máy tính, mạng viễn thông làm phương tiện phạm tội", "Chỉ xảy ra ở nước ngoài", "Không gây thiệt hại lớn", "Dễ phát hiện và xử lý", "A", "easy"),
    ("Biện pháp cơ bản phòng chống tội phạm là gì?", "Kết hợp phòng ngừa xã hội với đấu tranh trấn áp", "Chỉ tăng hình phạt", "Chỉ tuyên truyền", "Chỉ dựa vào lực lượng công an", "A", "medium"),
    ("Vi phạm pháp luật về ma túy bị xử lý như thế nào?", "Có thể bị xử phạt hành chính hoặc truy cứu trách nhiệm hình sự tùy mức độ", "Chỉ bị nhắc nhở", "Chỉ bị phạt tiền", "Không bị xử lý nếu dùng ít", "A", "easy"),
    ("An ninh mạng có vai trò gì hiện nay?", "Bảo vệ không gian mạng quốc gia, phòng chống thông tin xấu độc", "Chỉ chống virus máy tính", "Chỉ bảo vệ dữ liệu doanh nghiệp", "Không quan trọng với quốc phòng", "A", "easy"),
    ("Trách nhiệm của công dân khi sử dụng mạng xã hội là gì?", "Không đăng tải, chia sẻ thông tin sai sự thật, chống phá Nhà nước", "Được đăng tải mọi nội dung", "Chỉ cần ẩn danh là được", "Không có trách nhiệm pháp lý", "A", "easy"),
]

TIENG_ANH = [
    ("Choose the correct answer: She ___ to school every day.", "go", "goes", "going", "gone", "B", "easy"),
    ("Choose the correct answer: They ___ football yesterday.", "play", "plays", "played", "playing", "C", "easy"),
    ("Choose the correct answer: I have lived here ___ 2010.", "for", "since", "from", "during", "B", "medium"),
    ("Choose the correct answer: If it ___ tomorrow, we will stay at home.", "rain", "rains", "rained", "will rain", "B", "medium"),
    ("Choose the correct answer: This book is ___ than that one.", "interesting", "more interesting", "most interesting", "the most interesting", "B", "easy"),
    ("Choose the correct answer: He is the ___ student in the class.", "tall", "taller", "tallest", "more tall", "C", "easy"),
    ("Choose the correct answer: The letter ___ by Mary last week.", "wrote", "was written", "is written", "has written", "B", "medium"),
    ("Choose the correct answer: I wish I ___ more free time.", "have", "had", "will have", "having", "B", "hard"),
    ("Choose the correct answer: She asked me where I ___ from.", "come", "came", "will come", "coming", "B", "medium"),
    ("Choose the correct answer: Neither John nor his friends ___ coming.", "is", "are", "was", "has", "B", "hard"),
    ("Choose the word with different stress pattern.", "'water", "'table", "'window", "de'cide", "D", "medium"),
    ("Choose the word whose underlined part is pronounced differently: cats, dogs, books, maps", "cats", "dogs", "books", "maps", "B", "medium"),
    ("Choose the correct answer: I am looking forward to ___ you.", "see", "seeing", "saw", "seen", "B", "medium"),
    ("Choose the correct answer: He suggested ___ to the cinema.", "to go", "going", "go", "went", "B", "medium"),
    ("Choose the correct answer: It is the best film I have ___ seen.", "never", "ever", "already", "yet", "B", "medium"),
    ("Choose the correct answer: She has been studying English ___ five years.", "since", "for", "in", "at", "B", "easy"),
    ("Choose the correct answer: My father ___ working in this company since 2015.", "has been", "have been", "is", "was", "A", "medium"),
    ("Choose the correct answer: The man ___ lives next door is a doctor.", "which", "who", "whom", "whose", "B", "medium"),
    ("Choose the correct answer: This is the house ___ roof was damaged.", "which", "who", "whose", "that", "C", "hard"),
    ("Choose the correct answer: You had better ___ some rest.", "take", "to take", "taking", "took", "A", "medium"),
    ("Choose the correct answer: I would rather ___ at home tonight.", "stay", "to stay", "staying", "stayed", "A", "hard"),
    ("Choose the correct answer: He used to ___ a lot when he was young.", "travel", "traveling", "traveled", "travels", "A", "medium"),
    ("Choose the correct answer: The meeting ___ off because of the storm.", "put", "was put", "puts", "putting", "B", "medium"),
    ("Choose the correct answer: She is interested ___ learning Japanese.", "on", "in", "at", "for", "B", "easy"),
    ("Choose the correct answer: They are proud ___ their daughter.", "of", "on", "with", "for", "A", "easy"),
    ("Choose the correct answer: He apologized ___ being late.", "of", "for", "on", "about to", "B", "medium"),
    ("Choose the correct answer: Despite ___ tired, he continued working.", "be", "being", "to be", "was", "B", "hard"),
    ("Choose the correct answer: ___ he is poor, he is happy.", "Despite", "In spite of", "Although", "Because", "C", "medium"),
    ("Choose the correct answer: The more you practice, ___ you become.", "the better", "better", "the best", "best", "A", "hard"),
    ("Choose the correct answer: Hardly ___ arrived when the phone rang.", "he had", "had he", "he has", "has he", "B", "hard"),
    ("What does the abbreviation CV stand for in job applications?", "Curriculum Vitae", "Certified Value", "Career Version", "Company Volume", "A", "easy"),
    ("Choose the correct answer: Please ___ me know if you need help.", "let", "to let", "letting", "lets", "A", "easy"),
    ("Choose the correct answer: There ___ a lot of people at the party.", "was", "were", "is", "has", "B", "easy"),
    ("Choose the correct answer: How ___ money do you need?", "many", "much", "few", "little of", "B", "easy"),
    ("Choose the correct answer: She speaks English ___ than her brother.", "fluent", "more fluently", "most fluently", "fluently", "B", "medium"),
    ("Choose the correct answer: I have ___ finished my homework.", "yet", "already", "still", "ever", "B", "easy"),
    ("Choose the correct answer: The company ___ by a young engineer in 2018.", "founded", "was founded", "has founded", "founds", "B", "medium"),
    ("Choose the correct answer: If I ___ you, I would accept the offer.", "am", "was", "were", "will be", "C", "medium"),
    ("Choose the correct answer: By next year, she ___ here for a decade.", "will work", "will have worked", "works", "worked", "B", "hard"),
    ("Choose the correct answer: He denied ___ the money.", "to steal", "stealing", "steal", "stole", "B", "medium"),
    ("Choose the correct answer: The teacher made us ___ the exercise again.", "do", "to do", "doing", "done", "A", "medium"),
    ("Choose the correct answer: I am not used to ___ up early.", "get", "getting", "got", "gets", "B", "hard"),
    ("Choose the correct meaning of the idiom: once in a blue moon", "very often", "very rarely", "every night", "immediately", "B", "medium"),
    ("Choose the correct answer: Could you turn ___ the light please?", "in", "on", "into", "up to", "B", "easy"),
    ("Choose the correct answer: We need to look ___ this problem carefully.", "into", "in", "at to", "for to", "A", "medium"),
    ("Choose the correct answer: My computer broke ___ yesterday.", "down", "up", "into", "off", "A", "easy"),
    ("Choose the correct answer: The report must ___ before Friday.", "submit", "be submitted", "submitted", "submitting", "B", "medium"),
    ("Choose the correct answer: Not only ___ he intelligent but he is also kind.", "is", "he is", "does", "has", "A", "hard"),
    ("Choose the correct answer: It was such ___ interesting book that I read it twice.", "a", "an", "the", "no article", "B", "medium"),
    ("Choose the correct answer: I would like to make ___ appointment with the doctor.", "a", "an", "the", "no article", "B", "easy"),
]

TIN_HOC_DAI_CUONG = [
    ("Đơn vị nhỏ nhất biểu diễn thông tin trong máy tính là gì?", "Bit", "Byte", "Kilobyte", "Word", "A", "easy"),
    ("1 Byte bằng bao nhiêu bit?", "4 bit", "8 bit", "16 bit", "32 bit", "B", "easy"),
    ("Bộ phận nào được xem là bộ não của máy tính?", "RAM", "Ổ cứng", "CPU", "Card màn hình", "C", "easy"),
    ("RAM có đặc điểm gì?", "Lưu trữ vĩnh viễn", "Mất dữ liệu khi tắt máy", "Chỉ đọc không ghi", "Chậm hơn ổ cứng", "B", "easy"),
    ("Phần mềm nào sau đây là hệ điều hành?", "Microsoft Word", "Google Chrome", "Windows 11", "Photoshop", "C", "easy"),
    ("Hệ đếm nhị phân sử dụng những chữ số nào?", "0 và 1", "0 đến 7", "0 đến 9", "0 đến F", "A", "easy"),
    ("Số nhị phân 1010 có giá trị thập phân là bao nhiêu?", "8", "10", "12", "14", "B", "medium"),
    ("Số thập phân 13 đổi sang nhị phân là gì?", "1011", "1101", "1110", "1001", "B", "medium"),
    ("Thiết bị nào là thiết bị nhập?", "Máy in", "Màn hình", "Bàn phím", "Loa", "C", "easy"),
    ("Phần mở rộng nào dùng cho tệp Microsoft Word?", "xlsx", "docx", "pptx", "pdf", "B", "easy"),
    ("Trong Excel, công thức tính tổng ô A1 đến A10 là gì?", "=SUM(A1:A10)", "=TOTAL(A1:A10)", "=ADD(A1:A10)", "=COUNT(A1:A10)", "A", "easy"),
    ("Hàm nào trong Excel dùng để đếm số ô chứa số?", "SUM", "COUNT", "AVERAGE", "MAX", "B", "easy"),
    ("Trong Excel, ký hiệu $A$1 thể hiện kiểu địa chỉ nào?", "Tương đối", "Tuyệt đối", "Hỗn hợp", "Không hợp lệ", "B", "medium"),
    ("Địa chỉ IPv4 gồm bao nhiêu bit?", "16 bit", "32 bit", "64 bit", "128 bit", "B", "medium"),
    ("Giao thức nào dùng để truyền tải trang web?", "FTP", "SMTP", "HTTP", "SSH", "C", "easy"),
    ("DNS có chức năng gì?", "Cấp phát IP động", "Phân giải tên miền thành địa chỉ IP", "Mã hóa dữ liệu", "Chặn truy cập trái phép", "B", "medium"),
    ("Mạng LAN là viết tắt của cụm từ nào?", "Local Area Network", "Large Access Network", "Linked Access Node", "Local Access Number", "A", "easy"),
    ("Đơn vị đo dung lượng nào lớn nhất?", "Megabyte", "Gigabyte", "Terabyte", "Kilobyte", "C", "easy"),
    ("Phần mềm mã nguồn mở có đặc điểm gì?", "Luôn phải trả phí", "Được công khai mã nguồn", "Chỉ chạy trên Windows", "Không được sửa đổi", "B", "easy"),
    ("Tổ hợp phím Ctrl + C dùng để làm gì?", "Cắt", "Sao chép", "Dán", "Hoàn tác", "B", "easy"),
    ("Tổ hợp phím Ctrl + Z dùng để làm gì?", "Sao chép", "Dán", "Hoàn tác thao tác vừa thực hiện", "Lưu tệp", "C", "easy"),
    ("ROM có đặc điểm nào?", "Ghi xóa tự do", "Chủ yếu chỉ đọc, không mất khi tắt máy", "Nhanh hơn RAM", "Dung lượng rất lớn", "B", "medium"),
    ("Virus máy tính là gì?", "Một loại phần cứng", "Chương trình gây hại có khả năng lây lan", "Một giao thức mạng", "Một hệ điều hành", "B", "easy"),
    ("Thư mục dùng để làm gì?", "Chạy chương trình", "Tổ chức và chứa các tệp tin", "Kết nối Internet", "Tăng tốc CPU", "B", "easy"),
    ("Phần mở rộng exe biểu thị loại tệp nào?", "Tệp văn bản", "Tệp thực thi", "Tệp hình ảnh", "Tệp nén", "B", "easy"),
    ("Chức năng chính của hệ điều hành là gì?", "Soạn thảo văn bản", "Quản lý tài nguyên và điều phối hoạt động máy tính", "Thiết kế đồ họa", "Duyệt web", "B", "medium"),
    ("Bộ nhớ đệm Cache có vai trò gì?", "Lưu trữ lâu dài", "Tăng tốc truy xuất dữ liệu cho CPU", "Hiển thị hình ảnh", "Lưu phím bấm", "B", "medium"),
    ("Đâu là trình duyệt web?", "Windows Explorer", "Mozilla Firefox", "Microsoft Excel", "Notepad", "B", "easy"),
    ("Thuật ngữ phần cứng chỉ điều gì?", "Các chương trình máy tính", "Các bộ phận vật lý của máy tính", "Dữ liệu người dùng", "Kết nối mạng", "B", "easy"),
    ("Thuật toán là gì?", "Một ngôn ngữ lập trình", "Dãy hữu hạn các bước giải quyết một bài toán", "Một thiết bị phần cứng", "Một hệ điều hành", "B", "medium"),
    ("Để bảo vệ dữ liệu khỏi mất mát, biện pháp nào quan trọng nhất?", "Tắt máy thường xuyên", "Sao lưu dữ liệu định kỳ", "Xóa bớt tệp tin", "Đổi hình nền", "B", "easy"),
    ("Trong Word, chức năng Mail Merge dùng để làm gì?", "Trộn thư, tạo hàng loạt văn bản từ một danh sách", "Gửi email trực tiếp", "Ghép nhiều tệp Word", "Kiểm tra chính tả", "A", "medium"),
    ("Trong PowerPoint, chế độ nào dùng để trình chiếu?", "Normal View", "Slide Show", "Outline View", "Notes Page", "B", "easy"),
    ("Hàm IF trong Excel dùng để làm gì?", "Tính tổng có điều kiện", "Kiểm tra điều kiện và trả về giá trị tương ứng", "Đếm ô trống", "Sắp xếp dữ liệu", "B", "medium"),
    ("Hàm VLOOKUP trong Excel dùng để làm gì?", "Tìm kiếm giá trị theo cột dọc và trả về giá trị tương ứng", "Tính trung bình", "Đếm ký tự", "Nối chuỗi", "A", "hard"),
    ("Định dạng tệp nào giữ nguyên bố cục khi mở trên mọi thiết bị?", "DOCX", "PDF", "TXT", "RTF", "B", "easy"),
    ("Wifi là công nghệ kết nối gì?", "Kết nối mạng không dây", "Kết nối bằng cáp quang", "Kết nối qua cổng USB", "Kết nối Bluetooth", "A", "easy"),
    ("Điện toán đám mây (Cloud Computing) là gì?", "Cung cấp tài nguyên máy tính qua Internet theo nhu cầu", "Máy tính đặt trên cao", "Phần mềm dự báo thời tiết", "Mạng nội bộ doanh nghiệp", "A", "medium"),
    ("Dữ liệu lớn (Big Data) có đặc trưng nào?", "Khối lượng lớn, tốc độ nhanh và đa dạng", "Chỉ lưu trên giấy", "Kích thước nhỏ dễ xử lý", "Chỉ có dạng số", "A", "medium"),
    ("Mã hóa dữ liệu nhằm mục đích gì?", "Bảo mật, ngăn người không có quyền đọc được nội dung", "Giảm dung lượng tệp", "Tăng tốc truyền tải", "Sửa lỗi dữ liệu", "A", "medium"),
    ("Tường lửa (Firewall) có chức năng gì?", "Kiểm soát lưu lượng mạng ra vào để bảo vệ hệ thống", "Diệt virus có sẵn trong máy", "Tăng tốc độ Internet", "Sao lưu dữ liệu", "A", "medium"),
    ("Phishing là hình thức tấn công nào?", "Giả mạo để lừa lấy thông tin cá nhân", "Làm quá tải máy chủ", "Phá hủy phần cứng", "Nghe lén sóng wifi", "A", "medium"),
    ("Mật khẩu mạnh nên có đặc điểm gì?", "Đủ dài, kết hợp chữ hoa, chữ thường, số và ký tự đặc biệt", "Là ngày sinh dễ nhớ", "Chỉ gồm 4 chữ số", "Giống nhau ở mọi tài khoản", "A", "easy"),
    ("Bản quyền phần mềm được bảo vệ bởi luật nào?", "Luật Sở hữu trí tuệ", "Luật Doanh nghiệp", "Luật Lao động", "Luật Đất đai", "A", "easy"),
    ("Đơn vị đo tốc độ truyền dữ liệu mạng là gì?", "Hertz", "bps (bit per second)", "Byte", "Pixel", "B", "medium"),
    ("Độ phân giải màn hình được tính bằng gì?", "Số điểm ảnh theo chiều ngang và dọc", "Kích thước đường chéo", "Tần số quét", "Độ sáng", "A", "easy"),
    ("Hệ đếm thập lục phân (hexa) dùng bao nhiêu ký tự?", "8", "10", "16", "32", "C", "medium"),
    ("Trong hệ hexa, ký tự A tương ứng số thập phân nào?", "9", "10", "11", "15", "B", "medium"),
    ("Trí tuệ nhân tạo (AI) là gì?", "Công nghệ giúp máy tính mô phỏng khả năng tư duy của con người", "Một loại phần cứng mới", "Một ngôn ngữ lập trình", "Một hệ điều hành", "A", "easy"),
    ("Chữ ký số có tác dụng gì?", "Xác thực danh tính và bảo đảm toàn vẹn của văn bản điện tử", "Làm đẹp văn bản", "Nén dữ liệu", "Tăng tốc gửi email", "A", "medium"),
]

KY_NANG_MEM = [
    ("Kỹ năng mềm là gì?", "Nhóm kỹ năng liên quan đến cách ứng xử, giao tiếp và làm việc với người khác", "Kỹ năng sử dụng phần mềm máy tính", "Kỹ năng chuyên môn nghề nghiệp", "Kỹ năng vận hành máy móc", "A", "easy"),
    ("Giao tiếp hiệu quả bao gồm yếu tố nào?", "Lắng nghe, diễn đạt rõ ràng và phản hồi phù hợp", "Chỉ nói thật nhiều", "Chỉ im lặng lắng nghe", "Chỉ dùng ngôn ngữ cơ thể", "A", "easy"),
    ("Lắng nghe chủ động thể hiện qua hành vi nào?", "Tập trung, đặt câu hỏi làm rõ và phản hồi lại nội dung", "Ngắt lời để góp ý ngay", "Vừa nghe vừa dùng điện thoại", "Gật đầu cho qua chuyện", "A", "easy"),
    ("Ngôn ngữ cơ thể chiếm vai trò như thế nào trong giao tiếp?", "Truyền tải phần lớn thông điệp cảm xúc", "Không có ý nghĩa gì", "Chỉ quan trọng khi thuyết trình", "Chỉ dành cho diễn viên", "A", "medium"),
    ("Khi thuyết trình, điều quan trọng nhất là gì?", "Hiểu rõ đối tượng nghe và truyền đạt thông điệp rõ ràng", "Nói càng nhanh càng tốt", "Đọc nguyên văn slide", "Dùng thật nhiều hiệu ứng", "A", "easy"),
    ("Slide thuyết trình tốt nên như thế nào?", "Ít chữ, ý chính rõ ràng, hình ảnh minh họa phù hợp", "Càng nhiều chữ càng đầy đủ", "Nhiều màu sắc rực rỡ", "Chỉ toàn hình ảnh không có chữ", "A", "easy"),
    ("Cách khắc phục hồi hộp khi nói trước đám đông là gì?", "Chuẩn bị kỹ, tập luyện trước và hít thở sâu", "Tránh nhìn khán giả", "Nói thật nhanh cho xong", "Học thuộc lòng từng chữ", "A", "easy"),
    ("Kỹ năng làm việc nhóm đòi hỏi điều gì?", "Hợp tác, chia sẻ thông tin và tôn trọng ý kiến khác biệt", "Mỗi người làm riêng phần mình", "Một người quyết định tất cả", "Tránh mọi tranh luận", "A", "easy"),
    ("Vai trò của trưởng nhóm là gì?", "Điều phối công việc, tạo động lực và giải quyết xung đột", "Làm thay toàn bộ công việc", "Chỉ giám sát và phê bình", "Chỉ báo cáo kết quả", "A", "easy"),
    ("Khi có xung đột trong nhóm, cách xử lý tốt nhất là gì?", "Trao đổi thẳng thắn, tập trung vào vấn đề chứ không vào cá nhân", "Im lặng bỏ qua", "Tranh cãi đến khi thắng", "Báo cáo cấp trên ngay lập tức", "A", "medium"),
    ("Phương pháp brainstorming có nguyên tắc nào?", "Khuyến khích mọi ý tưởng, không phê phán trong giai đoạn đầu", "Chỉ nhận ý tưởng khả thi", "Chỉ trưởng nhóm được nêu ý tưởng", "Đánh giá ngay từng ý tưởng", "A", "medium"),
    ("Quản lý thời gian hiệu quả bắt đầu từ việc gì?", "Xác định mục tiêu và sắp xếp thứ tự ưu tiên công việc", "Làm việc nhiều giờ hơn", "Làm nhiều việc cùng lúc", "Trì hoãn việc khó", "A", "easy"),
    ("Ma trận Eisenhower phân loại công việc theo tiêu chí nào?", "Mức độ quan trọng và mức độ khẩn cấp", "Thời gian và chi phí", "Khó và dễ", "Cá nhân và tập thể", "A", "medium"),
    ("Theo ma trận Eisenhower, việc quan trọng nhưng không khẩn cấp nên xử lý thế nào?", "Lên kế hoạch thực hiện", "Làm ngay lập tức", "Ủy thác cho người khác", "Loại bỏ", "A", "hard"),
    ("Nguyên tắc SMART trong đặt mục tiêu gồm những yếu tố nào?", "Cụ thể, đo lường được, khả thi, liên quan và có thời hạn", "Nhanh, mạnh, chính xác", "Đơn giản, rẻ, hiệu quả", "Sáng tạo, mới mẻ, độc đáo", "A", "medium"),
    ("Kỹ năng giải quyết vấn đề gồm bước đầu tiên nào?", "Xác định và phân tích đúng vấn đề", "Đưa ra giải pháp ngay", "Tìm người chịu trách nhiệm", "Báo cáo cấp trên", "A", "medium"),
    ("Tư duy phản biện là gì?", "Khả năng phân tích, đánh giá thông tin một cách khách quan trước khi kết luận", "Luôn phản đối ý kiến người khác", "Chấp nhận mọi thông tin", "Tranh luận để thắng", "A", "medium"),
    ("Tư duy sáng tạo thể hiện qua điều gì?", "Nhìn vấn đề từ nhiều góc độ và đưa ra giải pháp mới mẻ", "Làm theo cách cũ cho an toàn", "Sao chép ý tưởng người khác", "Tránh mọi rủi ro", "A", "easy"),
    ("Trí tuệ cảm xúc (EQ) bao gồm năng lực nào?", "Nhận biết và quản lý cảm xúc của bản thân và người khác", "Ghi nhớ nhiều thông tin", "Tính toán nhanh", "Học ngoại ngữ giỏi", "A", "medium"),
    ("Khi nhận phản hồi tiêu cực, thái độ đúng đắn là gì?", "Bình tĩnh lắng nghe, ghi nhận và rút kinh nghiệm", "Phản bác ngay lập tức", "Im lặng và giận dỗi", "Bỏ ngoài tai", "A", "easy"),
    ("Cách đưa phản hồi mang tính xây dựng là gì?", "Cụ thể, tập trung vào hành vi và đề xuất hướng cải thiện", "Chỉ trích tính cách cá nhân", "Nói chung chung", "Phê bình trước đám đông", "A", "medium"),
    ("Kỹ năng đàm phán hiệu quả hướng tới kết quả nào?", "Đôi bên cùng có lợi", "Bên mình thắng tuyệt đối", "Nhượng bộ hoàn toàn", "Kéo dài không kết thúc", "A", "medium"),
    ("Chuẩn bị cho một buổi phỏng vấn xin việc cần làm gì?", "Tìm hiểu về công ty, vị trí ứng tuyển và chuẩn bị câu trả lời", "Chỉ cần ăn mặc đẹp", "Đến sớm là đủ", "Không cần chuẩn bị gì", "A", "easy"),
    ("Một CV tốt nên có đặc điểm gì?", "Ngắn gọn, trung thực, nêu bật kinh nghiệm phù hợp vị trí ứng tuyển", "Càng dài càng tốt", "Liệt kê mọi hoạt động từ nhỏ", "Dùng nhiều màu sắc bắt mắt", "A", "easy"),
    ("Khi trả lời câu hỏi Điểm yếu của bạn là gì, nên trả lời thế nào?", "Nêu điểm yếu thật kèm cách bạn đang khắc phục", "Nói không có điểm yếu nào", "Kể hết mọi khuyết điểm", "Từ chối trả lời", "A", "medium"),
    ("Văn hóa doanh nghiệp là gì?", "Hệ thống giá trị, chuẩn mực và hành vi chung của tổ chức", "Các hoạt động văn nghệ trong công ty", "Quy định về đồng phục", "Chính sách lương thưởng", "A", "medium"),
    ("Đạo đức nghề nghiệp đòi hỏi điều gì?", "Trung thực, trách nhiệm và tôn trọng lợi ích chung", "Chỉ cần hoàn thành công việc", "Tuân thủ tuyệt đối mọi mệnh lệnh", "Đặt lợi ích cá nhân lên trên", "A", "easy"),
    ("Kỹ năng thích ứng quan trọng vì lý do gì?", "Môi trường làm việc và công nghệ luôn thay đổi nhanh", "Để tránh phải học thêm", "Để làm hài lòng mọi người", "Để giữ nguyên cách làm cũ", "A", "easy"),
    ("Học tập suốt đời có ý nghĩa gì?", "Liên tục cập nhật kiến thức kỹ năng để không bị tụt hậu", "Chỉ học khi còn trẻ", "Chỉ học khi công ty yêu cầu", "Học để lấy nhiều bằng cấp", "A", "easy"),
    ("Kỹ năng viết email chuyên nghiệp cần lưu ý gì?", "Tiêu đề rõ ràng, nội dung ngắn gọn, xưng hô lịch sự", "Viết càng dài càng trang trọng", "Dùng nhiều biểu tượng cảm xúc", "Không cần tiêu đề", "A", "easy"),
    ("Khi làm việc từ xa, yếu tố nào quan trọng nhất?", "Tự giác, kỷ luật và giao tiếp chủ động", "Có thiết bị đắt tiền", "Làm việc ban đêm", "Luôn online 24 giờ", "A", "easy"),
    ("Stress trong công việc nên được xử lý như thế nào?", "Nhận diện nguyên nhân, sắp xếp lại công việc và nghỉ ngơi hợp lý", "Bỏ qua và làm tiếp", "Nghỉ việc ngay", "Đổ lỗi cho người khác", "A", "easy"),
    ("Cân bằng công việc và cuộc sống mang lại lợi ích gì?", "Duy trì sức khỏe, hiệu suất và hạnh phúc lâu dài", "Giảm thu nhập", "Ít cơ hội thăng tiến", "Không có lợi ích rõ ràng", "A", "easy"),
    ("Kỹ năng ra quyết định hiệu quả cần dựa trên gì?", "Thông tin đầy đủ, phân tích lựa chọn và cân nhắc hậu quả", "Cảm tính nhất thời", "Ý kiến của số đông", "Quyết định càng nhanh càng tốt", "A", "medium"),
    ("Ủy thác công việc mang lại lợi ích gì?", "Giảm tải cho người quản lý và phát triển năng lực nhân viên", "Đẩy việc khó cho người khác", "Tránh trách nhiệm", "Giảm chi phí nhân sự", "A", "medium"),
    ("Networking trong nghề nghiệp có nghĩa là gì?", "Xây dựng và duy trì mạng lưới quan hệ nghề nghiệp", "Lắp đặt hệ thống mạng", "Tham gia mạng xã hội", "Kết nối máy tính với nhau", "A", "easy"),
    ("Kỹ năng thuyết phục dựa trên yếu tố nào?", "Lập luận logic, bằng chứng thuyết phục và thấu hiểu người nghe", "Nói to và nhiều", "Áp đặt quan điểm", "Hứa hẹn quá mức", "A", "medium"),
    ("Khi làm việc với người có quan điểm khác biệt, nên làm gì?", "Tôn trọng, tìm hiểu lý do và tìm điểm chung", "Tránh tiếp xúc", "Cố gắng thay đổi họ ngay", "Phớt lờ ý kiến của họ", "A", "easy"),
    ("Kỹ năng ghi chép hiệu quả trong cuộc họp là gì?", "Ghi ý chính, quyết định và người chịu trách nhiệm", "Ghi nguyên văn mọi lời nói", "Không cần ghi gì", "Chỉ ghi khi được yêu cầu", "A", "easy"),
    ("Trách nhiệm cá nhân trong công việc thể hiện qua điều gì?", "Chủ động hoàn thành nhiệm vụ và nhận trách nhiệm về kết quả", "Chỉ làm khi được nhắc", "Đổ lỗi khi thất bại", "Chờ chỉ đạo cụ thể từng bước", "A", "easy"),
    ("Thái độ tích cực ảnh hưởng thế nào đến hiệu quả công việc?", "Tăng động lực, khả năng vượt khó và tinh thần đồng đội", "Không ảnh hưởng gì", "Chỉ ảnh hưởng đến cá nhân", "Làm giảm tính nghiêm túc", "A", "easy"),
    ("Kỹ năng đọc hiểu nhanh giúp ích gì?", "Nắm bắt thông tin quan trọng trong thời gian ngắn", "Đọc được nhiều tiểu thuyết", "Ghi nhớ nguyên văn", "Không có tác dụng thực tế", "A", "easy"),
    ("Khi được giao nhiệm vụ chưa rõ ràng, nên làm gì?", "Chủ động hỏi lại để làm rõ yêu cầu và tiêu chí đánh giá", "Tự đoán và làm theo ý mình", "Chờ người khác làm trước", "Từ chối nhiệm vụ", "A", "easy"),
    ("Kỹ năng quản lý dự án cơ bản gồm những gì?", "Lập kế hoạch, phân công, theo dõi tiến độ và đánh giá kết quả", "Chỉ giao việc cho nhân viên", "Chỉ báo cáo cuối kỳ", "Chỉ kiểm soát chi phí", "A", "medium"),
    ("Nguyên tắc Pareto (80/20) trong công việc có nghĩa là gì?", "Khoảng 80% kết quả đến từ 20% nỗ lực quan trọng nhất", "Làm 80% việc trong 20% thời gian", "Chỉ cần hoàn thành 80% công việc", "20% nhân viên làm 80% việc", "A", "hard"),
    ("Kỹ năng tự đánh giá bản thân giúp ích gì?", "Nhận ra điểm mạnh, điểm yếu để phát triển phù hợp", "Tự tin tuyệt đối vào mình", "So sánh mình với người khác", "Che giấu khuyết điểm", "A", "easy"),
    ("Khi thất bại trong công việc, thái độ đúng là gì?", "Phân tích nguyên nhân, rút bài học và tiếp tục cố gắng", "Từ bỏ ngay", "Đổ lỗi cho hoàn cảnh", "Che giấu thất bại", "A", "easy"),
    ("Kỹ năng giao tiếp liên văn hóa quan trọng khi nào?", "Khi làm việc với đối tác, đồng nghiệp từ nền văn hóa khác", "Chỉ khi đi du lịch", "Chỉ khi học ngoại ngữ", "Không cần thiết", "A", "easy"),
    ("Tinh thần khởi nghiệp thể hiện qua điều gì?", "Chủ động tìm cơ hội, dám chấp nhận rủi ro có tính toán", "Luôn làm theo hướng dẫn", "Tránh mọi thay đổi", "Chỉ quan tâm đến lương", "A", "easy"),
    ("Mục tiêu cuối cùng của rèn luyện kỹ năng mềm là gì?", "Làm việc hiệu quả hơn và phát triển bản thân toàn diện", "Có thêm chứng chỉ", "Gây ấn tượng với cấp trên", "Thay thế kiến thức chuyên môn", "A", "easy"),
]

DATA = {
    'Pháp luật đại cương': PHAP_LUAT,
    'Giáo dục quốc phòng và an ninh': GDQP,
    'Tiếng Anh (Đại học)': TIENG_ANH,
    'Tin học đại cương': TIN_HOC_DAI_CUONG,
    'Kỹ năng mềm': KY_NANG_MEM,
}
