# -*- coding: utf-8 -*-
"""Nhóm Lý luận chính trị. Mỗi câu: (nội dung, A, B, C, D, đáp án đúng, độ khó)."""

TRIET_HOC = [
    ("Vấn đề cơ bản của triết học là gì?", "Quan hệ giữa vật chất và ý thức", "Quan hệ giữa con người và tự nhiên", "Quan hệ giữa cá nhân và xã hội", "Quan hệ giữa lý luận và thực tiễn", "A", "easy"),
    ("Chủ nghĩa duy vật khẳng định điều gì?", "Ý thức có trước, quyết định vật chất", "Vật chất có trước, quyết định ý thức", "Vật chất và ý thức cùng có trước", "Không thể nhận thức được thế giới", "B", "easy"),
    ("Theo Lênin, vật chất là gì?", "Toàn bộ các sự vật có thể nhìn thấy", "Phạm trù triết học chỉ thực tại khách quan tồn tại độc lập với ý thức", "Tổng hợp các nguyên tử", "Năng lượng của vũ trụ", "B", "medium"),
    ("Thuộc tính cơ bản nhất của vật chất theo chủ nghĩa duy vật biện chứng là gì?", "Có khối lượng", "Tồn tại khách quan", "Có thể quan sát bằng mắt", "Luôn đứng yên", "B", "medium"),
    ("Ý thức có nguồn gốc xã hội trực tiếp từ đâu?", "Lao động và ngôn ngữ", "Bộ não người", "Thế giới tự nhiên", "Tôn giáo", "A", "medium"),
    ("Phép biện chứng duy vật có mấy quy luật cơ bản?", "Hai quy luật", "Ba quy luật", "Bốn quy luật", "Sáu quy luật", "B", "easy"),
    ("Quy luật nào chỉ ra nguồn gốc, động lực của sự phát triển?", "Quy luật lượng - chất", "Quy luật thống nhất và đấu tranh của các mặt đối lập", "Quy luật phủ định của phủ định", "Quy luật giá trị", "B", "medium"),
    ("Quy luật nào chỉ ra cách thức của sự phát triển?", "Quy luật lượng đổi dẫn đến chất đổi", "Quy luật mâu thuẫn", "Quy luật phủ định của phủ định", "Quy luật cung cầu", "A", "medium"),
    ("Quy luật nào chỉ ra khuynh hướng của sự phát triển?", "Quy luật mâu thuẫn", "Quy luật lượng - chất", "Quy luật phủ định của phủ định", "Quy luật bảo toàn năng lượng", "C", "medium"),
    ("Theo phép biện chứng, phát triển diễn ra theo hình thức nào?", "Đường thẳng đi lên", "Đường xoáy ốc đi lên", "Vòng tròn khép kín", "Đường thẳng đi xuống", "B", "medium"),
    ("Độ trong quy luật lượng - chất là gì?", "Giới hạn mà sự thay đổi lượng chưa làm thay đổi chất", "Mức độ phát triển cao nhất", "Điểm mà chất mới ra đời", "Tốc độ biến đổi của sự vật", "A", "hard"),
    ("Điểm nút là khái niệm chỉ điều gì?", "Điểm giới hạn mà tại đó sự thay đổi lượng làm chất thay đổi", "Điểm khởi đầu của sự vật", "Điểm kết thúc của quá trình", "Trung điểm của quá trình phát triển", "A", "hard"),
    ("Bước nhảy là gì?", "Sự thay đổi dần dần về lượng", "Sự chuyển hóa về chất do thay đổi về lượng gây ra", "Sự đứng yên tương đối", "Sự lặp lại của cái cũ", "B", "medium"),
    ("Mâu thuẫn biện chứng là gì?", "Sự xung đột giữa các cá nhân", "Sự thống nhất và đấu tranh giữa các mặt đối lập", "Sai lầm trong tư duy logic", "Sự khác nhau giữa hai sự vật", "B", "medium"),
    ("Phủ định biện chứng có đặc điểm cơ bản nào?", "Xóa bỏ hoàn toàn cái cũ", "Tính khách quan và tính kế thừa", "Do ý muốn chủ quan quyết định", "Chấm dứt sự phát triển", "B", "medium"),
    ("Hai nguyên lý cơ bản của phép biện chứng duy vật là gì?", "Nguyên lý về mối liên hệ phổ biến và nguyên lý về sự phát triển", "Nguyên lý nhân quả và nguyên lý tất yếu", "Nguyên lý vận động và nguyên lý đứng yên", "Nguyên lý thực tiễn và nguyên lý nhận thức", "A", "medium"),
    ("Cặp phạm trù nào phản ánh quan hệ giữa cái sinh ra và cái được sinh ra?", "Nội dung - hình thức", "Nguyên nhân - kết quả", "Bản chất - hiện tượng", "Cái chung - cái riêng", "B", "easy"),
    ("Phạm trù nào chỉ cái nhất định phải xảy ra trong điều kiện nhất định?", "Ngẫu nhiên", "Tất nhiên", "Khả năng", "Hiện tượng", "B", "medium"),
    ("Thực tiễn là gì?", "Hoạt động nhận thức của con người", "Hoạt động vật chất có mục đích, mang tính lịch sử - xã hội của con người", "Hoạt động tư duy trừu tượng", "Hoạt động tôn giáo", "B", "medium"),
    ("Vai trò của thực tiễn đối với nhận thức là gì?", "Là cơ sở, động lực, mục đích và tiêu chuẩn của chân lý", "Chỉ là kết quả của nhận thức", "Không liên quan đến nhận thức", "Chỉ kiểm tra nhận thức", "A", "medium"),
    ("Con đường biện chứng của nhận thức chân lý đi theo trình tự nào?", "Từ tư duy trừu tượng đến trực quan sinh động", "Từ trực quan sinh động đến tư duy trừu tượng và đến thực tiễn", "Từ thực tiễn đến lý luận rồi dừng lại", "Từ lý luận đến lý luận", "B", "hard"),
    ("Chân lý theo quan điểm mácxít có tính chất gì?", "Chỉ mang tính chủ quan", "Khách quan, cụ thể, tương đối và tuyệt đối", "Bất biến và vĩnh cửu", "Do số đông quyết định", "B", "medium"),
    ("Hình thức nào thuộc giai đoạn nhận thức cảm tính?", "Khái niệm", "Phán đoán", "Tri giác", "Suy luận", "C", "easy"),
    ("Hình thức nào thuộc giai đoạn nhận thức lý tính?", "Cảm giác", "Tri giác", "Biểu tượng", "Khái niệm", "D", "easy"),
    ("Tồn tại xã hội quyết định yếu tố nào?", "Ý thức xã hội", "Điều kiện tự nhiên", "Quy luật vật lý", "Cấu tạo sinh học của con người", "A", "medium"),
    ("Yếu tố nào giữ vai trò quyết định trong tồn tại xã hội?", "Điều kiện địa lý", "Dân số", "Phương thức sản xuất vật chất", "Truyền thống văn hóa", "C", "medium"),
    ("Lực lượng sản xuất bao gồm những yếu tố nào?", "Người lao động và tư liệu sản xuất", "Quan hệ sở hữu và quan hệ phân phối", "Nhà nước và pháp luật", "Đạo đức và tôn giáo", "A", "medium"),
    ("Trong lực lượng sản xuất, yếu tố nào giữ vai trò quyết định nhất?", "Công cụ lao động", "Người lao động", "Đối tượng lao động", "Vốn đầu tư", "B", "hard"),
    ("Quan hệ sản xuất bao gồm những mặt nào?", "Sở hữu tư liệu sản xuất, tổ chức quản lý và phân phối sản phẩm", "Lao động, vốn và công nghệ", "Kinh tế, chính trị và văn hóa", "Nhà nước, pháp luật và đạo đức", "A", "medium"),
    ("Cơ sở hạ tầng trong triết học Mác - Lênin là gì?", "Hệ thống đường sá, cầu cống", "Toàn bộ quan hệ sản xuất hợp thành cơ cấu kinh tế của xã hội", "Hệ thống chính trị của nhà nước", "Nền tảng đạo đức xã hội", "B", "hard"),
    ("Kiến trúc thượng tầng bao gồm những gì?", "Quan điểm chính trị, pháp quyền, đạo đức và các thiết chế tương ứng", "Nhà máy, xí nghiệp", "Lực lượng sản xuất hiện đại", "Tài nguyên thiên nhiên", "A", "medium"),
    ("Hình thái kinh tế - xã hội là phạm trù chỉ điều gì?", "Xã hội ở từng giai đoạn lịch sử với quan hệ sản xuất và kiến trúc thượng tầng tương ứng", "Trình độ phát triển kinh tế của một quốc gia", "Chế độ chính trị đương thời", "Tổng sản phẩm quốc nội", "A", "medium"),
    ("Theo Mác, động lực trực tiếp của các cuộc cách mạng xã hội là gì?", "Ý chí của lãnh tụ", "Đấu tranh giai cấp", "Sự phát triển của khoa học", "Yếu tố ngẫu nhiên của lịch sử", "B", "medium"),
    ("Giai cấp theo Lênin được phân biệt chủ yếu dựa trên tiêu chí nào?", "Địa vị trong một hệ thống sản xuất xã hội nhất định", "Trình độ học vấn", "Nguồn gốc dân tộc", "Nơi cư trú", "A", "medium"),
    ("Nhà nước ra đời do nguyên nhân nào?", "Do thỏa thuận tự nguyện của mọi người", "Do xuất hiện chế độ tư hữu và mâu thuẫn giai cấp không thể điều hòa", "Do ý muốn của các nhà thông thái", "Do nhu cầu tôn giáo", "B", "medium"),
    ("Quần chúng nhân dân có vai trò gì trong lịch sử?", "Là lực lượng sáng tạo chân chính ra lịch sử", "Chỉ là người thừa hành", "Không có vai trò đáng kể", "Chỉ quan trọng trong chiến tranh", "A", "easy"),
    ("Con người theo quan niệm mácxít là gì?", "Thực thể thuần túy sinh học", "Thực thể thuần túy xã hội", "Thực thể thống nhất giữa mặt sinh học và mặt xã hội", "Sản phẩm của đấng siêu nhiên", "C", "medium"),
    ("Bản chất con người theo Mác được quyết định bởi điều gì?", "Tổng hòa các quan hệ xã hội", "Cấu tạo gen di truyền", "Môi trường tự nhiên", "Số phận định sẵn", "A", "medium"),
    ("Vận động theo triết học Mác - Lênin là gì?", "Sự di chuyển vị trí trong không gian", "Mọi sự biến đổi nói chung, là phương thức tồn tại của vật chất", "Sự thay đổi về tốc độ", "Hoạt động của con người", "B", "medium"),
    ("Đứng yên theo phép biện chứng có tính chất gì?", "Tuyệt đối và vĩnh viễn", "Tương đối và tạm thời", "Không tồn tại", "Là bản chất của vật chất", "B", "medium"),
    ("Không gian và thời gian theo chủ nghĩa duy vật biện chứng là gì?", "Hình thức tồn tại của vật chất", "Sản phẩm của ý thức con người", "Tồn tại độc lập ngoài vật chất", "Do thần linh tạo ra", "A", "medium"),
    ("Ý thức có tính chất nào sau đây?", "Sao chép nguyên xi hiện thực", "Phản ánh sáng tạo hiện thực khách quan vào bộ óc người", "Hoàn toàn độc lập với vật chất", "Có trước vật chất", "B", "medium"),
    ("Nguyên tắc khách quan trong hoạt động nhận thức đòi hỏi điều gì?", "Xuất phát từ thực tế khách quan, tôn trọng quy luật khách quan", "Xuất phát từ mong muốn chủ quan", "Dựa vào kinh nghiệm cá nhân là đủ", "Tin vào trực giác", "A", "medium"),
    ("Bệnh chủ quan duy ý chí biểu hiện như thế nào?", "Tuyệt đối hóa vai trò của ý chí, coi thường quy luật khách quan", "Quá đề cao điều kiện vật chất", "Không dám hành động", "Chỉ dựa vào lý luận sách vở", "A", "medium"),
    ("Quan điểm toàn diện yêu cầu điều gì khi xem xét sự vật?", "Xem xét trong mối liên hệ nhiều mặt, có trọng tâm trọng điểm", "Chỉ xem xét một mặt nổi bật nhất", "Xem xét tách rời khỏi hoàn cảnh", "Chỉ dựa vào hình thức bên ngoài", "A", "medium"),
    ("Quan điểm lịch sử - cụ thể đòi hỏi điều gì?", "Xem xét sự vật gắn với điều kiện, hoàn cảnh lịch sử cụ thể", "Áp dụng một công thức chung cho mọi trường hợp", "Chỉ nghiên cứu quá khứ", "Bỏ qua yếu tố thời gian", "A", "medium"),
    ("Cái riêng và cái chung có quan hệ như thế nào?", "Cái chung tồn tại trong cái riêng, thông qua cái riêng", "Cái chung tồn tại độc lập ngoài cái riêng", "Cái riêng không chứa cái chung", "Hai cái hoàn toàn tách biệt", "A", "hard"),
    ("Bản chất và hiện tượng có quan hệ ra sao?", "Bản chất bộc lộ qua hiện tượng, hiện tượng biểu hiện bản chất", "Hai cái hoàn toàn trùng khít nhau", "Hiện tượng quyết định bản chất", "Bản chất không thể nhận thức được", "A", "medium"),
    ("Khả năng và hiện thực khác nhau ở điểm nào?", "Khả năng là cái chưa có nhưng sẽ có, hiện thực là cái đang tồn tại", "Khả năng là cái đã có, hiện thực là cái sẽ có", "Hai khái niệm đồng nhất", "Khả năng không bao giờ thành hiện thực", "A", "medium"),
    ("Nội dung và hình thức có mối quan hệ như thế nào?", "Nội dung quyết định hình thức, hình thức tác động trở lại nội dung", "Hình thức quyết định hoàn toàn nội dung", "Hai cái không liên quan", "Nội dung luôn bất biến", "A", "medium"),
    ("Sự thống nhất giữa lý luận và thực tiễn đòi hỏi điều gì?", "Lý luận phải xuất phát từ thực tiễn và được kiểm nghiệm bằng thực tiễn", "Lý luận độc lập với thực tiễn", "Thực tiễn không cần lý luận dẫn đường", "Chỉ cần học thuộc lý luận", "A", "medium"),
]

KINH_TE_CHINH_TRI = [
    ("Đối tượng nghiên cứu của kinh tế chính trị Mác - Lênin là gì?", "Quan hệ sản xuất trong mối liên hệ với lực lượng sản xuất và kiến trúc thượng tầng", "Cách thức kinh doanh của doanh nghiệp", "Chính sách tiền tệ của ngân hàng", "Hành vi tiêu dùng cá nhân", "A", "medium"),
    ("Hàng hóa có mấy thuộc tính cơ bản?", "Một thuộc tính", "Hai thuộc tính", "Ba thuộc tính", "Bốn thuộc tính", "B", "easy"),
    ("Hai thuộc tính của hàng hóa là gì?", "Giá trị sử dụng và giá trị", "Giá cả và số lượng", "Chất lượng và mẫu mã", "Cung và cầu", "A", "easy"),
    ("Giá trị của hàng hóa được quyết định bởi yếu tố nào?", "Lao động xã hội cần thiết kết tinh trong hàng hóa", "Sở thích của người mua", "Chi phí quảng cáo", "Độ hiếm của hàng hóa", "A", "medium"),
    ("Giá trị sử dụng của hàng hóa là gì?", "Công dụng của vật phẩm thỏa mãn nhu cầu con người", "Số tiền phải trả để mua", "Thời gian sản xuất ra nó", "Lợi nhuận thu được", "A", "easy"),
    ("Lao động sản xuất hàng hóa có tính chất hai mặt nào?", "Lao động cụ thể và lao động trừu tượng", "Lao động chân tay và lao động trí óc", "Lao động giản đơn và lao động phức tạp", "Lao động cá nhân và lao động tập thể", "A", "medium"),
    ("Lao động trừu tượng tạo ra cái gì của hàng hóa?", "Giá trị sử dụng", "Giá trị", "Hình dáng bên ngoài", "Thương hiệu", "B", "medium"),
    ("Lượng giá trị hàng hóa được đo bằng gì?", "Thời gian lao động xã hội cần thiết", "Thời gian lao động cá biệt", "Số lượng nguyên liệu tiêu hao", "Giá bán trên thị trường", "A", "medium"),
    ("Năng suất lao động tăng thì lượng giá trị một đơn vị hàng hóa thay đổi thế nào?", "Tăng lên", "Giảm xuống", "Không đổi", "Tăng gấp đôi", "B", "hard"),
    ("Quy luật giá trị yêu cầu sản xuất và trao đổi hàng hóa dựa trên cơ sở nào?", "Hao phí lao động xã hội cần thiết", "Ý muốn của người bán", "Quy định của nhà nước", "Sự khan hiếm tự nhiên", "A", "medium"),
    ("Tiền tệ có mấy chức năng cơ bản theo Mác?", "Ba chức năng", "Bốn chức năng", "Năm chức năng", "Sáu chức năng", "C", "medium"),
    ("Chức năng nào là chức năng đầu tiên và cơ bản nhất của tiền?", "Thước đo giá trị", "Phương tiện lưu thông", "Phương tiện cất trữ", "Tiền tệ thế giới", "A", "medium"),
    ("Công thức chung của tư bản là gì?", "H - T - H", "T - H - T'", "H - H", "T - T", "B", "medium"),
    ("Giá trị thặng dư là gì?", "Phần giá trị dôi ra ngoài giá trị sức lao động do công nhân tạo ra", "Lợi nhuận từ buôn bán chênh lệch giá", "Tiền lãi ngân hàng", "Thuế nhà nước thu được", "A", "medium"),
    ("Sức lao động trở thành hàng hóa cần điều kiện gì?", "Người lao động tự do về thân thể và không có tư liệu sản xuất", "Người lao động có trình độ cao", "Có nhiều nhà máy", "Có hệ thống ngân hàng phát triển", "A", "hard"),
    ("Hàng hóa sức lao động có đặc điểm gì đặc biệt?", "Khi sử dụng tạo ra giá trị lớn hơn giá trị bản thân nó", "Không có giá trị sử dụng", "Không thể mua bán", "Giá trị không thay đổi", "A", "hard"),
    ("Tư bản bất biến là bộ phận tư bản dùng để làm gì?", "Mua tư liệu sản xuất, giá trị không thay đổi trong quá trình sản xuất", "Trả lương cho công nhân", "Đầu tư chứng khoán", "Nộp thuế", "A", "medium"),
    ("Tư bản khả biến là bộ phận tư bản dùng để làm gì?", "Mua máy móc thiết bị", "Mua sức lao động, tạo ra giá trị thặng dư", "Mua nguyên vật liệu", "Trả tiền thuê đất", "B", "medium"),
    ("Tỷ suất giá trị thặng dư phản ánh điều gì?", "Trình độ bóc lột lao động làm thuê", "Hiệu quả sử dụng vốn", "Tốc độ chu chuyển tư bản", "Quy mô doanh nghiệp", "A", "medium"),
    ("Giá trị thặng dư tuyệt đối thu được bằng cách nào?", "Kéo dài ngày lao động hoặc tăng cường độ lao động", "Tăng năng suất lao động xã hội", "Giảm giá nguyên liệu", "Mở rộng thị trường", "A", "medium"),
    ("Giá trị thặng dư tương đối thu được bằng cách nào?", "Rút ngắn thời gian lao động tất yếu nhờ tăng năng suất lao động", "Kéo dài ngày lao động", "Tăng số lượng công nhân", "Giảm lương trực tiếp", "A", "hard"),
    ("Tích lũy tư bản là gì?", "Chuyển hóa một phần giá trị thặng dư thành tư bản phụ thêm", "Cất giữ tiền trong két", "Vay vốn ngân hàng", "Bán bớt tài sản", "A", "medium"),
    ("Cấu tạo hữu cơ của tư bản là gì?", "Tỷ lệ giữa tư bản bất biến và tư bản khả biến phản ánh cấu tạo kỹ thuật", "Tỷ lệ giữa vốn và nợ", "Tỷ lệ lợi nhuận trên doanh thu", "Cơ cấu ngành nghề", "A", "hard"),
    ("Tuần hoàn của tư bản trải qua mấy giai đoạn?", "Hai giai đoạn", "Ba giai đoạn", "Bốn giai đoạn", "Năm giai đoạn", "B", "medium"),
    ("Chu chuyển tư bản là gì?", "Tuần hoàn của tư bản lặp đi lặp lại có định kỳ", "Việc vay và trả nợ", "Sự thay đổi chủ sở hữu", "Quá trình phá sản", "A", "medium"),
    ("Tư bản cố định có đặc điểm gì?", "Giá trị chuyển dần từng phần vào sản phẩm", "Giá trị chuyển hết một lần vào sản phẩm", "Không tham gia sản xuất", "Luôn tăng giá trị", "A", "medium"),
    ("Tư bản lưu động bao gồm những gì?", "Nguyên nhiên vật liệu và tiền lương", "Nhà xưởng và máy móc", "Bằng phát minh sáng chế", "Đất đai", "A", "medium"),
    ("Lợi nhuận theo Mác thực chất là gì?", "Hình thức biểu hiện của giá trị thặng dư", "Phần thưởng cho tài kinh doanh", "Chênh lệch do may rủi thị trường", "Tiền công của nhà tư bản", "A", "medium"),
    ("Tỷ suất lợi nhuận được tính bằng công thức nào?", "Giá trị thặng dư chia tổng tư bản ứng trước", "Giá trị thặng dư chia tư bản khả biến", "Doanh thu chia chi phí", "Lợi nhuận chia doanh thu", "A", "hard"),
    ("Cạnh tranh giữa các ngành dẫn đến hình thành cái gì?", "Tỷ suất lợi nhuận bình quân", "Giá trị cá biệt", "Độc quyền hoàn toàn", "Giá trị thặng dư siêu ngạch", "A", "hard"),
    ("Giá cả sản xuất bằng gì?", "Chi phí sản xuất cộng lợi nhuận bình quân", "Giá trị hàng hóa", "Chi phí nguyên liệu", "Giá bán lẻ trên thị trường", "A", "hard"),
    ("Địa tô tư bản chủ nghĩa là gì?", "Phần giá trị thặng dư siêu ngạch nộp cho địa chủ", "Thuế đất nhà nước thu", "Tiền thuê nhà ở", "Lợi nhuận của nông dân", "A", "medium"),
    ("Địa tô chênh lệch I gắn với yếu tố nào?", "Độ màu mỡ tự nhiên và vị trí thuận lợi của đất", "Đầu tư thâm canh liên tiếp", "Quyền sở hữu ruộng đất", "Giá nông sản trên thị trường", "A", "hard"),
    ("Chủ nghĩa tư bản độc quyền ra đời vào thời kỳ nào?", "Đầu thế kỷ XVI", "Giữa thế kỷ XVIII", "Cuối thế kỷ XIX đầu thế kỷ XX", "Sau năm 1945", "C", "medium"),
    ("Lênin nêu mấy đặc điểm kinh tế cơ bản của chủ nghĩa đế quốc?", "Ba đặc điểm", "Bốn đặc điểm", "Năm đặc điểm", "Sáu đặc điểm", "C", "medium"),
    ("Tổ chức độc quyền hình thành do nguyên nhân chủ yếu nào?", "Tích tụ và tập trung sản xuất phát triển đến mức độ cao", "Chính sách của nhà nước", "Ý muốn của các nhà tư bản", "Sự khan hiếm tài nguyên", "A", "medium"),
    ("Tư bản tài chính là kết quả của sự kết hợp nào?", "Độc quyền công nghiệp và độc quyền ngân hàng", "Nhà nước và doanh nghiệp", "Thương nghiệp và nông nghiệp", "Trong nước và nước ngoài", "A", "medium"),
    ("Xuất khẩu tư bản khác xuất khẩu hàng hóa ở điểm nào?", "Đưa tư bản ra nước ngoài để thu giá trị thặng dư", "Bán hàng hóa ra nước ngoài", "Chuyển giao công nghệ miễn phí", "Viện trợ nhân đạo", "A", "medium"),
    ("Kinh tế thị trường định hướng xã hội chủ nghĩa ở Việt Nam có đặc trưng gì?", "Vận hành theo quy luật thị trường, có sự quản lý của Nhà nước, hướng tới mục tiêu dân giàu nước mạnh", "Nhà nước quyết định toàn bộ giá cả", "Hoàn toàn tự do không có quản lý", "Chỉ có kinh tế nhà nước", "A", "medium"),
    ("Thành phần kinh tế nào giữ vai trò chủ đạo trong nền kinh tế Việt Nam?", "Kinh tế nhà nước", "Kinh tế tư nhân", "Kinh tế có vốn đầu tư nước ngoài", "Kinh tế tập thể", "A", "easy"),
    ("Công nghiệp hóa, hiện đại hóa ở Việt Nam nhằm mục tiêu gì?", "Chuyển nền kinh tế sang nền sản xuất dựa trên công nghệ hiện đại", "Chỉ phát triển nông nghiệp", "Giảm quy mô nền kinh tế", "Tăng nhập khẩu hàng tiêu dùng", "A", "medium"),
    ("Sở hữu toàn dân về đất đai ở Việt Nam do ai làm đại diện chủ sở hữu?", "Nhà nước", "Doanh nghiệp", "Hộ gia đình", "Tổ chức quốc tế", "A", "easy"),
    ("Quy luật cung cầu tác động đến giá cả như thế nào?", "Cung lớn hơn cầu thì giá có xu hướng giảm", "Cung lớn hơn cầu thì giá tăng", "Cung cầu không ảnh hưởng đến giá", "Giá luôn bằng giá trị", "A", "easy"),
    ("Lạm phát là hiện tượng gì?", "Mức giá chung tăng lên, sức mua đồng tiền giảm", "Giá cả giảm liên tục", "Thất nghiệp tăng cao", "Sản lượng giảm sút", "A", "easy"),
    ("Hội nhập kinh tế quốc tế mang lại lợi ích chủ yếu nào?", "Mở rộng thị trường, thu hút vốn và công nghệ", "Tự cung tự cấp hoàn toàn", "Đóng cửa nền kinh tế", "Giảm cạnh tranh trong nước", "A", "easy"),
    ("Giá trị thặng dư siêu ngạch là gì?", "Phần giá trị thặng dư dôi ra do giá trị cá biệt thấp hơn giá trị xã hội", "Giá trị thặng dư do kéo dài ngày lao động", "Lợi nhuận độc quyền", "Địa tô tuyệt đối", "A", "hard"),
    ("Tái sản xuất mở rộng có đặc điểm gì?", "Quy mô sản xuất năm sau lớn hơn năm trước", "Quy mô sản xuất không đổi", "Quy mô sản xuất thu hẹp", "Chỉ sản xuất hàng tiêu dùng", "A", "medium"),
    ("Thị trường thực hiện chức năng nào sau đây?", "Thừa nhận giá trị và giá trị sử dụng của hàng hóa", "Quyết định công nghệ sản xuất", "Ấn định mức lương tối thiểu", "Phân bổ ngân sách nhà nước", "A", "medium"),
    ("Cạnh tranh trong nội bộ ngành dẫn tới kết quả gì?", "Hình thành giá trị thị trường của hàng hóa", "Hình thành lợi nhuận bình quân", "Xóa bỏ hoàn toàn cạnh tranh", "Giảm năng suất lao động", "A", "hard"),
    ("Vai trò của Nhà nước trong nền kinh tế thị trường định hướng XHCN là gì?", "Định hướng, điều tiết và khắc phục khuyết tật của thị trường", "Trực tiếp sản xuất mọi hàng hóa", "Ấn định toàn bộ giá cả", "Không can thiệp vào kinh tế", "A", "medium"),
]

CNXH_KHOA_HOC = [
    ("Chủ nghĩa xã hội khoa học do ai sáng lập?", "C. Mác và Ph. Ăngghen", "V.I. Lênin", "Hồ Chí Minh", "Xanh Ximông và Phurie", "A", "easy"),
    ("Tác phẩm nào đánh dấu sự ra đời của chủ nghĩa xã hội khoa học?", "Tuyên ngôn của Đảng Cộng sản", "Tư bản", "Nhà nước và cách mạng", "Chống Đuyrinh", "A", "easy"),
    ("Tuyên ngôn của Đảng Cộng sản ra đời năm nào?", "1844", "1848", "1867", "1871", "B", "easy"),
    ("Hai phát kiến vĩ đại của Mác là gì?", "Chủ nghĩa duy vật lịch sử và học thuyết giá trị thặng dư", "Thuyết tiến hóa và thuyết tế bào", "Định luật bảo toàn năng lượng và thuyết nguyên tử", "Phép biện chứng và logic hình thức", "A", "medium"),
    ("Sứ mệnh lịch sử của giai cấp công nhân là gì?", "Xóa bỏ chủ nghĩa tư bản, xây dựng chủ nghĩa xã hội và cộng sản chủ nghĩa", "Giành lấy quyền sở hữu tư liệu sản xuất cho riêng mình", "Phát triển kinh tế tư nhân", "Duy trì trật tự xã hội hiện có", "A", "medium"),
    ("Vì sao giai cấp công nhân có sứ mệnh lịch sử đó?", "Do địa vị kinh tế - xã hội khách quan quy định", "Do đông về số lượng", "Do được giáo dục tốt nhất", "Do có nhiều của cải", "A", "medium"),
    ("Đặc điểm nào thuộc về giai cấp công nhân hiện đại?", "Gắn với nền sản xuất công nghiệp và có tính tổ chức kỷ luật cao", "Sở hữu tư liệu sản xuất chủ yếu", "Chủ yếu làm nông nghiệp", "Không tham gia sản xuất vật chất", "A", "medium"),
    ("Điều kiện chủ quan để giai cấp công nhân thực hiện sứ mệnh lịch sử là gì?", "Sự trưởng thành về ý thức và có chính đảng lãnh đạo", "Số lượng công nhân đông đảo", "Nền kinh tế phát triển cao", "Sự ủng hộ của quốc tế", "A", "hard"),
    ("Cách mạng xã hội chủ nghĩa có nguyên nhân sâu xa từ đâu?", "Mâu thuẫn giữa lực lượng sản xuất và quan hệ sản xuất tư bản chủ nghĩa", "Ý chí của lãnh tụ cách mạng", "Thiên tai và dịch bệnh", "Sự can thiệp từ bên ngoài", "A", "medium"),
    ("Hình thái kinh tế - xã hội cộng sản chủ nghĩa gồm mấy giai đoạn?", "Hai giai đoạn", "Ba giai đoạn", "Bốn giai đoạn", "Một giai đoạn duy nhất", "A", "medium"),
    ("Giai đoạn thấp của hình thái cộng sản chủ nghĩa được gọi là gì?", "Chủ nghĩa xã hội", "Chủ nghĩa cộng sản", "Chủ nghĩa tư bản nhà nước", "Thời kỳ quá độ", "A", "easy"),
    ("Nguyên tắc phân phối chủ yếu trong chủ nghĩa xã hội là gì?", "Phân phối theo lao động", "Phân phối theo nhu cầu", "Phân phối bình quân", "Phân phối theo vốn góp", "A", "medium"),
    ("Nguyên tắc phân phối trong xã hội cộng sản chủ nghĩa là gì?", "Làm theo năng lực, hưởng theo nhu cầu", "Làm theo năng lực, hưởng theo lao động", "Phân phối đều cho mọi người", "Phân phối theo chức vụ", "A", "medium"),
    ("Thời kỳ quá độ lên chủ nghĩa xã hội là gì?", "Thời kỳ cải biến cách mạng từ xã hội cũ sang xã hội mới", "Thời kỳ khủng hoảng kinh tế", "Thời kỳ chiến tranh", "Giai đoạn cuối của chủ nghĩa tư bản", "A", "medium"),
    ("Đặc điểm nổi bật của thời kỳ quá độ là gì?", "Tồn tại đan xen nhiều thành phần kinh tế và nhiều yếu tố xã hội cũ mới", "Chỉ còn một thành phần kinh tế", "Không còn giai cấp", "Kinh tế phát triển đồng đều", "A", "medium"),
    ("Việt Nam quá độ lên chủ nghĩa xã hội theo hình thức nào?", "Bỏ qua chế độ tư bản chủ nghĩa", "Trải qua đầy đủ chế độ tư bản chủ nghĩa", "Quay lại chế độ phong kiến", "Không qua thời kỳ quá độ", "A", "medium"),
    ("Dân chủ xã hội chủ nghĩa có bản chất giai cấp nào?", "Giai cấp công nhân", "Giai cấp tư sản", "Giai cấp địa chủ", "Không mang bản chất giai cấp", "A", "medium"),
    ("Nhà nước xã hội chủ nghĩa có chức năng cơ bản nào?", "Tổ chức xây dựng kinh tế - xã hội và trấn áp sự phản kháng của kẻ thù", "Chỉ có chức năng trấn áp", "Chỉ có chức năng đối ngoại", "Không có chức năng kinh tế", "A", "medium"),
    ("Nhà nước pháp quyền xã hội chủ nghĩa Việt Nam là của ai?", "Của nhân dân, do nhân dân, vì nhân dân", "Của giai cấp tư sản", "Của tầng lớp trí thức", "Của các doanh nghiệp", "A", "easy"),
    ("Cơ cấu xã hội - giai cấp trong thời kỳ quá độ ở Việt Nam gồm những lực lượng nào?", "Công nhân, nông dân, trí thức và các tầng lớp khác", "Chỉ có công nhân", "Chỉ có nông dân", "Chỉ có doanh nhân", "A", "easy"),
    ("Liên minh giai cấp nào là nền tảng của khối đại đoàn kết dân tộc ở Việt Nam?", "Công nhân - nông dân - trí thức", "Tư sản - địa chủ", "Trí thức - doanh nhân", "Công nhân - tư sản", "A", "easy"),
    ("Vấn đề dân tộc theo quan điểm mácxít cần giải quyết theo nguyên tắc nào?", "Bình đẳng, đoàn kết, tôn trọng và giúp nhau cùng phát triển", "Đồng hóa các dân tộc thiểu số", "Tách biệt hoàn toàn các dân tộc", "Ưu tiên tuyệt đối một dân tộc", "A", "medium"),
    ("Cương lĩnh dân tộc của Lênin gồm những nội dung nào?", "Các dân tộc hoàn toàn bình đẳng, được quyền tự quyết và liên hiệp công nhân các dân tộc", "Các dân tộc phải hợp nhất thành một", "Dân tộc lớn lãnh đạo dân tộc nhỏ", "Mỗi dân tộc phát triển biệt lập", "A", "hard"),
    ("Quan điểm của chủ nghĩa Mác - Lênin về tôn giáo trong CNXH là gì?", "Tôn trọng và bảo đảm quyền tự do tín ngưỡng của nhân dân", "Cấm mọi hoạt động tôn giáo", "Bắt buộc mọi người theo một tôn giáo", "Không quan tâm đến tôn giáo", "A", "medium"),
    ("Nguồn gốc của tôn giáo theo chủ nghĩa Mác - Lênin bao gồm gì?", "Nguồn gốc kinh tế - xã hội, nhận thức và tâm lý", "Chỉ do thần linh tạo ra", "Chỉ do trình độ học vấn thấp", "Chỉ do yếu tố di truyền", "A", "medium"),
    ("Gia đình có chức năng cơ bản nào?", "Tái sản xuất con người, kinh tế, giáo dục và thỏa mãn nhu cầu tâm sinh lý", "Chỉ có chức năng kinh tế", "Chỉ có chức năng sinh con", "Không có chức năng xã hội", "A", "easy"),
    ("Cơ sở kinh tế của gia đình trong chủ nghĩa xã hội là gì?", "Chế độ công hữu về tư liệu sản xuất chủ yếu", "Chế độ tư hữu tuyệt đối", "Chế độ nô lệ", "Kinh tế tự nhiên", "A", "medium"),
    ("Mục tiêu cao nhất của chủ nghĩa xã hội là gì?", "Giải phóng con người, phát triển toàn diện con người", "Tăng trưởng kinh tế bằng mọi giá", "Mở rộng lãnh thổ", "Tích lũy của cải cho nhà nước", "A", "medium"),
    ("Đặc trưng nào thể hiện bản chất của xã hội xã hội chủ nghĩa mà Việt Nam xây dựng?", "Dân giàu, nước mạnh, dân chủ, công bằng, văn minh", "Kinh tế tự cung tự cấp", "Nhà nước sở hữu toàn bộ tài sản", "Xóa bỏ mọi hình thức thị trường", "A", "easy"),
    ("Nền dân chủ xã hội chủ nghĩa khác dân chủ tư sản ở điểm căn bản nào?", "Quyền lực thực sự thuộc về nhân dân lao động", "Có bầu cử định kỳ", "Có hiến pháp thành văn", "Có nhiều đảng phái", "A", "hard"),
    ("Cách mạng xã hội chủ nghĩa trên lĩnh vực tư tưởng - văn hóa nhằm mục đích gì?", "Xây dựng nền văn hóa mới và con người mới xã hội chủ nghĩa", "Xóa bỏ toàn bộ văn hóa truyền thống", "Sao chép văn hóa nước ngoài", "Chỉ phát triển nghệ thuật giải trí", "A", "medium"),
    ("Động lực chủ yếu của công cuộc xây dựng chủ nghĩa xã hội ở Việt Nam là gì?", "Đại đoàn kết toàn dân tộc và lợi ích chính đáng của nhân dân", "Viện trợ nước ngoài", "Tài nguyên thiên nhiên", "Vay nợ quốc tế", "A", "medium"),
    ("Vai trò của Đảng Cộng sản trong hệ thống chính trị xã hội chủ nghĩa là gì?", "Lãnh đạo Nhà nước và xã hội", "Trực tiếp điều hành mọi doanh nghiệp", "Thay thế chức năng của Nhà nước", "Chỉ làm công tác tuyên truyền", "A", "easy"),
    ("Đặc điểm của giai cấp công nhân Việt Nam là gì?", "Ra đời trước giai cấp tư sản dân tộc, gắn bó mật thiết với nông dân", "Ra đời sau khi giành độc lập", "Không có quan hệ với nông dân", "Chiếm đa số dân cư", "A", "hard"),
    ("Xu hướng khách quan của sự phát triển quan hệ dân tộc theo Lênin là gì?", "Các dân tộc thức tỉnh ý thức dân tộc và các dân tộc xích lại gần nhau", "Các dân tộc ngày càng tách biệt", "Các dân tộc bị đồng hóa hoàn toàn", "Quan hệ dân tộc không thay đổi", "A", "hard"),
    ("Chức năng giáo dục của gia đình có ý nghĩa gì?", "Hình thành nhân cách, đạo đức và lối sống cho thế hệ trẻ", "Chỉ dạy kiến thức văn hóa", "Thay thế hoàn toàn nhà trường", "Không ảnh hưởng đến xã hội", "A", "easy"),
    ("Chủ nghĩa xã hội không tưởng có hạn chế cơ bản nào?", "Không chỉ ra được lực lượng và con đường hiện thực để cải tạo xã hội", "Không phê phán chủ nghĩa tư bản", "Không quan tâm đến người lao động", "Không có giá trị lịch sử", "A", "medium"),
    ("Ba nguồn gốc lý luận của chủ nghĩa Mác là gì?", "Triết học cổ điển Đức, kinh tế chính trị Anh và chủ nghĩa xã hội không tưởng Pháp", "Triết học Hy Lạp, luật La Mã và thần học", "Khoa học tự nhiên, toán học và logic", "Văn học Nga, nghệ thuật Ý và âm nhạc Đức", "A", "medium"),
    ("Cách mạng Tháng Mười Nga thành công năm nào?", "1905", "1917", "1919", "1945", "B", "easy"),
    ("Ý nghĩa quốc tế của Cách mạng Tháng Mười Nga là gì?", "Mở ra thời đại quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội trên phạm vi thế giới", "Kết thúc chiến tranh thế giới thứ hai", "Thành lập Liên hợp quốc", "Xóa bỏ chế độ nô lệ", "A", "medium"),
    ("Nguyên nhân chủ yếu dẫn tới sự sụp đổ mô hình CNXH ở Liên Xô và Đông Âu là gì?", "Sai lầm trong đường lối và chậm đổi mới, cùng sự chống phá từ bên ngoài", "Thiếu tài nguyên thiên nhiên", "Dân số quá ít", "Không có nền công nghiệp", "A", "hard"),
    ("Bài học rút ra từ sự sụp đổ mô hình CNXH ở Liên Xô là gì?", "Phải kiên định mục tiêu nhưng đổi mới sáng tạo phù hợp thực tiễn", "Từ bỏ hoàn toàn con đường xã hội chủ nghĩa", "Đóng cửa hoàn toàn với thế giới", "Không cần vai trò lãnh đạo của Đảng", "A", "medium"),
    ("Công bằng xã hội trong chủ nghĩa xã hội được hiểu như thế nào?", "Phân phối hợp lý theo cống hiến, đồng thời bảo đảm an sinh xã hội", "Chia đều tuyệt đối cho mọi người", "Ai mạnh người đó hưởng nhiều", "Chỉ ưu tiên người có chức vụ", "A", "medium"),
    ("Hệ thống chính trị xã hội chủ nghĩa ở Việt Nam gồm những bộ phận nào?", "Đảng, Nhà nước và Mặt trận Tổ quốc cùng các tổ chức chính trị - xã hội", "Chỉ có Nhà nước", "Chỉ có Đảng", "Chỉ có các doanh nghiệp nhà nước", "A", "easy"),
    ("Quyền lực nhà nước ở Việt Nam được tổ chức theo nguyên tắc nào?", "Thống nhất, có phân công phối hợp và kiểm soát giữa các cơ quan", "Tam quyền phân lập tuyệt đối", "Tập trung toàn bộ vào một cá nhân", "Phân chia theo vùng miền", "A", "medium"),
    ("Vấn đề tôn giáo cần được giải quyết bằng phương pháp nào?", "Vận động, thuyết phục và cải thiện đời sống vật chất tinh thần của nhân dân", "Mệnh lệnh hành chính", "Cưỡng chế bằng vũ lực", "Bỏ mặc không quản lý", "A", "medium"),
    ("Chế độ hôn nhân trong chủ nghĩa xã hội dựa trên cơ sở nào?", "Tự nguyện, tiến bộ, một vợ một chồng, vợ chồng bình đẳng", "Sắp đặt của cha mẹ", "Địa vị kinh tế", "Quy định của làng xã", "A", "easy"),
    ("Trí thức có vai trò gì trong thời kỳ quá độ lên chủ nghĩa xã hội?", "Lực lượng quan trọng trong phát triển khoa học công nghệ và kinh tế tri thức", "Không có vai trò đáng kể", "Chỉ làm công tác giảng dạy", "Đối lập với giai cấp công nhân", "A", "easy"),
    ("Toàn cầu hóa đặt ra yêu cầu gì với các nước xã hội chủ nghĩa?", "Chủ động hội nhập, giữ vững độc lập tự chủ và bản sắc dân tộc", "Đóng cửa hoàn toàn", "Hòa tan vào trật tự thế giới", "Từ bỏ mục tiêu phát triển", "A", "medium"),
    ("Tiêu chí đánh giá sự tiến bộ xã hội theo chủ nghĩa Mác là gì?", "Trình độ phát triển của lực lượng sản xuất và mức độ giải phóng con người", "Số lượng vũ khí quân sự", "Diện tích lãnh thổ", "Số lượng dân cư", "A", "hard"),
]

TU_TUONG_HCM = [
    ("Tư tưởng Hồ Chí Minh là gì?", "Hệ thống quan điểm toàn diện và sâu sắc về những vấn đề cơ bản của cách mạng Việt Nam", "Một tác phẩm văn học", "Một học thuyết kinh tế", "Một trường phái triết học phương Tây", "A", "easy"),
    ("Nguồn gốc lý luận quan trọng nhất hình thành tư tưởng Hồ Chí Minh là gì?", "Chủ nghĩa Mác - Lênin", "Nho giáo", "Phật giáo", "Tư tưởng dân chủ tư sản Pháp", "A", "easy"),
    ("Nguyễn Ái Quốc ra đi tìm đường cứu nước vào năm nào?", "1905", "1911", "1920", "1930", "B", "easy"),
    ("Nguyễn Ái Quốc đọc Sơ thảo Luận cương của Lênin vào năm nào?", "1917", "1919", "1920", "1925", "C", "medium"),
    ("Đảng Cộng sản Việt Nam được thành lập vào thời gian nào?", "Ngày 3/2/1930", "Ngày 19/8/1945", "Ngày 2/9/1945", "Ngày 7/5/1954", "A", "easy"),
    ("Theo Hồ Chí Minh, cách mạng giải phóng dân tộc muốn thắng lợi phải đi theo con đường nào?", "Con đường cách mạng vô sản", "Con đường cách mạng tư sản", "Con đường cải lương", "Con đường bạo động đơn thuần", "A", "medium"),
    ("Theo Hồ Chí Minh, lực lượng của cách mạng giải phóng dân tộc là ai?", "Toàn dân tộc, nòng cốt là công nông", "Chỉ giai cấp công nhân", "Chỉ tầng lớp trí thức", "Chỉ lực lượng vũ trang", "A", "medium"),
    ("Luận điểm sáng tạo của Hồ Chí Minh về quan hệ giữa cách mạng thuộc địa và cách mạng chính quốc là gì?", "Cách mạng thuộc địa có thể nổ ra và giành thắng lợi trước", "Phải chờ cách mạng chính quốc thắng lợi trước", "Hai cuộc cách mạng không liên quan", "Cách mạng thuộc địa không thể thắng lợi", "A", "hard"),
    ("Theo Hồ Chí Minh, độc lập dân tộc phải gắn liền với điều gì?", "Chủ nghĩa xã hội", "Chế độ quân chủ", "Chủ nghĩa tư bản", "Chế độ đa đảng", "A", "medium"),
    ("Câu nói Không có gì quý hơn độc lập, tự do được Hồ Chí Minh nêu ra năm nào?", "1945", "1954", "1966", "1969", "C", "medium"),
    ("Bản Tuyên ngôn Độc lập được Hồ Chí Minh đọc vào ngày nào?", "19/8/1945", "2/9/1945", "6/1/1946", "19/12/1946", "B", "easy"),
    ("Theo Hồ Chí Minh, đặc trưng bản chất nhất của chủ nghĩa xã hội là gì?", "Do nhân dân lao động làm chủ", "Có nền công nghiệp hiện đại", "Có quân đội mạnh", "Có nhiều tài nguyên", "A", "medium"),
    ("Theo Hồ Chí Minh, mục tiêu của chủ nghĩa xã hội là gì?", "Nâng cao đời sống vật chất và tinh thần của nhân dân", "Tăng ngân sách nhà nước", "Mở rộng ảnh hưởng quốc tế", "Xây dựng nhiều công trình lớn", "A", "easy"),
    ("Theo Hồ Chí Minh, động lực quan trọng nhất của chủ nghĩa xã hội là gì?", "Con người", "Vốn đầu tư", "Tài nguyên", "Công nghệ nhập khẩu", "A", "medium"),
    ("Hồ Chí Minh xác định Đảng Cộng sản Việt Nam là đảng của ai?", "Của giai cấp công nhân, của nhân dân lao động và của dân tộc Việt Nam", "Chỉ của giai cấp công nhân", "Của tầng lớp trí thức", "Của mọi giai cấp không phân biệt", "A", "medium"),
    ("Nguyên tắc tổ chức cơ bản của Đảng theo Hồ Chí Minh là gì?", "Tập trung dân chủ", "Tự do tuyệt đối", "Tập trung quan liêu", "Phân quyền hoàn toàn", "A", "easy"),
    ("Theo Hồ Chí Minh, tự phê bình và phê bình có ý nghĩa gì?", "Là quy luật phát triển của Đảng, giúp Đảng trong sạch vững mạnh", "Là hình thức kỷ luật cán bộ", "Chỉ áp dụng khi có sai phạm lớn", "Không cần thiết trong thời bình", "A", "medium"),
    ("Nhà nước theo tư tưởng Hồ Chí Minh mang bản chất gì?", "Nhà nước của dân, do dân, vì dân mang bản chất giai cấp công nhân", "Nhà nước phi giai cấp", "Nhà nước của giai cấp tư sản", "Nhà nước quân chủ lập hiến", "A", "medium"),
    ("Theo Hồ Chí Minh, gốc của người cách mạng là gì?", "Đạo đức", "Tài năng", "Học vấn", "Quan hệ xã hội", "A", "easy"),
    ("Phẩm chất đạo đức cơ bản nhất theo Hồ Chí Minh là gì?", "Trung với nước, hiếu với dân", "Cần kiệm liêm chính", "Yêu thương con người", "Tinh thần quốc tế trong sáng", "A", "medium"),
    ("Cần, kiệm, liêm, chính, chí công vô tư là nội dung thuộc lĩnh vực nào?", "Đạo đức cách mạng", "Kinh tế chính trị", "Quân sự", "Ngoại giao", "A", "easy"),
    ("Theo Hồ Chí Minh, Liêm có nghĩa là gì?", "Trong sạch, không tham lam", "Siêng năng chăm chỉ", "Tiết kiệm không lãng phí", "Ngay thẳng đúng đắn", "A", "medium"),
    ("Theo Hồ Chí Minh, Chính có nghĩa là gì?", "Thẳng thắn, đứng đắn với mình, với người và với việc", "Chăm chỉ làm việc", "Không tham ô", "Tiết kiệm của công", "A", "medium"),
    ("Ba nguyên tắc xây dựng đạo đức mới theo Hồ Chí Minh là gì?", "Nói đi đôi với làm, xây đi đôi với chống, tu dưỡng suốt đời", "Học tập, lao động, chiến đấu", "Đoàn kết, kỷ luật, sáng tạo", "Cần, kiệm, liêm", "A", "hard"),
    ("Theo Hồ Chí Minh, đại đoàn kết dân tộc là gì?", "Vấn đề chiến lược, quyết định thành công của cách mạng", "Sách lược tạm thời", "Chỉ áp dụng trong chiến tranh", "Công việc riêng của Mặt trận", "A", "medium"),
    ("Nền tảng của khối đại đoàn kết dân tộc theo Hồ Chí Minh là gì?", "Liên minh công - nông - trí thức", "Tầng lớp doanh nhân", "Đội ngũ quân đội", "Người Việt Nam ở nước ngoài", "A", "medium"),
    ("Hình thức tổ chức của khối đại đoàn kết dân tộc là gì?", "Mặt trận dân tộc thống nhất", "Công đoàn", "Hợp tác xã", "Hội đồng nhân dân", "A", "easy"),
    ("Theo Hồ Chí Minh, đoàn kết quốc tế nhằm mục đích gì?", "Kết hợp sức mạnh dân tộc với sức mạnh thời đại", "Phụ thuộc vào nước lớn", "Can thiệp vào công việc nước khác", "Mở rộng lãnh thổ", "A", "medium"),
    ("Nguyên tắc trong quan hệ đối ngoại theo Hồ Chí Minh là gì?", "Độc lập tự chủ, tự lực tự cường gắn với hợp tác quốc tế", "Hoàn toàn dựa vào bên ngoài", "Đóng cửa không giao thiệp", "Liên minh quân sự với nước lớn", "A", "medium"),
    ("Theo Hồ Chí Minh, văn hóa có vai trò gì?", "Soi đường cho quốc dân đi", "Chỉ để giải trí", "Không liên quan đến chính trị", "Chỉ phục vụ tầng lớp trên", "A", "medium"),
    ("Hồ Chí Minh xác định văn hóa Việt Nam mới có tính chất gì?", "Dân tộc, khoa học, đại chúng", "Hoàn toàn hiện đại hóa theo phương Tây", "Bảo thủ giữ nguyên truyền thống", "Chỉ mang tính bác học", "A", "medium"),
    ("Theo Hồ Chí Minh, Vì lợi ích mười năm thì phải trồng cây, vì lợi ích trăm năm thì phải làm gì?", "Trồng người", "Xây nhà máy", "Mở đường sá", "Tích lũy của cải", "A", "easy"),
    ("Con người mới xã hội chủ nghĩa theo Hồ Chí Minh cần có gì?", "Vừa hồng vừa chuyên, có đức và có tài", "Chỉ cần giỏi chuyên môn", "Chỉ cần đạo đức tốt", "Chỉ cần trung thành tuyệt đối", "A", "easy"),
    ("Theo Hồ Chí Minh, có tài mà không có đức thì thế nào?", "Là người vô dụng", "Vẫn có ích cho xã hội", "Là người hoàn hảo", "Không ảnh hưởng gì", "A", "easy"),
    ("Quan điểm của Hồ Chí Minh về giáo dục là gì?", "Học đi đôi với hành, lý luận gắn với thực tiễn", "Chỉ chú trọng lý thuyết", "Chỉ chú trọng thực hành", "Học để làm quan", "A", "easy"),
    ("Theo Hồ Chí Minh, dân chủ nghĩa là gì?", "Dân là chủ và dân làm chủ", "Nhà nước quyết định thay dân", "Đa số áp đặt thiểu số", "Tự do không giới hạn", "A", "medium"),
    ("Theo Hồ Chí Minh, cán bộ là gì?", "Gốc của mọi công việc", "Người chỉ đạo từ xa", "Người hưởng đặc quyền", "Người chỉ làm hành chính", "A", "easy"),
    ("Bệnh nào bị Hồ Chí Minh coi là kẻ thù của cách mạng?", "Tham ô, lãng phí, quan liêu", "Nóng vội trong công việc", "Thiếu kinh nghiệm", "Học vấn chưa cao", "A", "easy"),
    ("Theo Hồ Chí Minh, thực hành tiết kiệm nhằm mục đích gì?", "Tích lũy vốn để xây dựng đất nước, nâng cao đời sống nhân dân", "Hạn chế tiêu dùng của nhân dân", "Giảm chi tiêu quốc phòng", "Tăng tích trữ vàng bạc", "A", "medium"),
    ("Chiến lược quân sự nổi bật trong tư tưởng Hồ Chí Minh là gì?", "Chiến tranh nhân dân toàn dân toàn diện", "Chỉ dựa vào quân đội chính quy", "Chỉ dùng ngoại giao", "Phòng thủ bị động", "A", "medium"),
    ("Theo Hồ Chí Minh, xây dựng lực lượng vũ trang nhân dân gồm mấy thứ quân?", "Hai thứ quân", "Ba thứ quân", "Bốn thứ quân", "Một thứ quân duy nhất", "B", "medium"),
    ("Di chúc của Chủ tịch Hồ Chí Minh được viết vào những năm nào?", "1945 - 1946", "1954 - 1955", "1965 - 1969", "1930 - 1931", "C", "medium"),
    ("Trong Di chúc, Hồ Chí Minh dặn dò điều gì trước hết về Đảng?", "Giữ gìn sự đoàn kết nhất trí trong Đảng như giữ gìn con ngươi của mắt mình", "Mở rộng số lượng đảng viên", "Xây dựng nhiều trụ sở", "Tăng cường ngân sách cho Đảng", "A", "medium"),
    ("Theo Hồ Chí Minh, muốn xây dựng chủ nghĩa xã hội trước hết cần có gì?", "Con người xã hội chủ nghĩa", "Nhiều nhà máy hiện đại", "Vốn vay nước ngoài", "Hệ thống pháp luật đầy đủ", "A", "medium"),
    ("Phương pháp cách mạng nổi bật của Hồ Chí Minh là gì?", "Dĩ bất biến ứng vạn biến", "Cứng nhắc theo nguyên tắc", "Tùy tiện thay đổi mục tiêu", "Chờ thời cơ từ bên ngoài", "A", "hard"),
    ("Bản chất khoa học và cách mạng của tư tưởng Hồ Chí Minh thể hiện ở chỗ nào?", "Vận dụng sáng tạo chủ nghĩa Mác - Lênin vào điều kiện cụ thể Việt Nam", "Sao chép nguyên mẫu mô hình nước ngoài", "Dựa hoàn toàn vào kinh nghiệm dân gian", "Xuất phát từ ý muốn chủ quan", "A", "medium"),
    ("Hồ Chí Minh được UNESCO vinh danh vào năm nào?", "1969", "1975", "1987", "1990", "C", "hard"),
    ("UNESCO vinh danh Hồ Chí Minh với danh hiệu nào?", "Anh hùng giải phóng dân tộc và Nhà văn hóa kiệt xuất của Việt Nam", "Nhà quân sự lỗi lạc thế giới", "Nhà kinh tế học xuất sắc", "Nhà ngoại giao tiêu biểu", "A", "medium"),
    ("Theo Hồ Chí Minh, nhân dân có vị trí như thế nào trong sự nghiệp cách mạng?", "Là gốc, là lực lượng quyết định mọi thắng lợi", "Là đối tượng được lãnh đạo thụ động", "Chỉ tham gia khi có chiến tranh", "Không giữ vai trò quyết định", "A", "easy"),
    ("Học tập và làm theo tư tưởng, đạo đức, phong cách Hồ Chí Minh nhằm mục đích gì?", "Xây dựng đội ngũ cán bộ đảng viên có đức có tài, phục vụ nhân dân", "Hình thức tuyên truyền thuần túy", "Thay thế việc học chuyên môn", "Chỉ áp dụng cho lãnh đạo cấp cao", "A", "easy"),
    ("Phong cách làm việc nổi bật của Hồ Chí Minh là gì?", "Quần chúng, dân chủ, khoa học và nêu gương", "Mệnh lệnh hành chính", "Làm việc một mình", "Dựa vào cấp dưới báo cáo", "A", "medium"),
]

LICH_SU_DANG = [
    ("Đảng Cộng sản Việt Nam ra đời là kết quả của sự kết hợp giữa những yếu tố nào?", "Chủ nghĩa Mác - Lênin, phong trào công nhân và phong trào yêu nước", "Phong trào nông dân và trí thức", "Chỉ phong trào công nhân", "Sự giúp đỡ của Quốc tế Cộng sản", "A", "medium"),
    ("Hội nghị thành lập Đảng đầu năm 1930 diễn ra ở đâu?", "Hương Cảng, Trung Quốc", "Pác Bó, Cao Bằng", "Paris, Pháp", "Mátxcơva, Liên Xô", "A", "medium"),
    ("Ai chủ trì Hội nghị thành lập Đảng Cộng sản Việt Nam?", "Nguyễn Ái Quốc", "Trần Phú", "Lê Hồng Phong", "Hà Huy Tập", "A", "easy"),
    ("Ba tổ chức cộng sản năm 1929 hợp nhất thành Đảng Cộng sản Việt Nam gồm những tổ chức nào?", "Đông Dương Cộng sản Đảng, An Nam Cộng sản Đảng, Đông Dương Cộng sản Liên đoàn", "Việt Nam Quốc dân Đảng và Tân Việt", "Hội Việt Nam Cách mạng Thanh niên và Việt Minh", "Đảng Lao động và Đảng Dân chủ", "A", "medium"),
    ("Cương lĩnh chính trị đầu tiên của Đảng do ai soạn thảo?", "Nguyễn Ái Quốc", "Trần Phú", "Lê Duẩn", "Trường Chinh", "A", "easy"),
    ("Luận cương chính trị tháng 10/1930 do ai soạn thảo?", "Nguyễn Ái Quốc", "Trần Phú", "Nguyễn Văn Cừ", "Lê Hồng Phong", "B", "medium"),
    ("Phong trào cách mạng 1930 - 1931 đạt đỉnh cao ở đâu?", "Xô viết Nghệ - Tĩnh", "Nam Kỳ", "Bắc Sơn", "Ba Tơ", "A", "easy"),
    ("Mặt trận Việt Minh được thành lập vào thời gian nào?", "Tháng 5/1941", "Tháng 8/1945", "Tháng 9/1939", "Tháng 3/1935", "A", "medium"),
    ("Hội nghị Trung ương lần thứ 8 (5/1941) có chủ trương quan trọng gì?", "Đặt nhiệm vụ giải phóng dân tộc lên hàng đầu", "Tập trung đấu tranh giai cấp", "Thành lập chính phủ liên hiệp", "Tiến hành cải cách ruộng đất", "A", "hard"),
    ("Cách mạng Tháng Tám thành công vào năm nào?", "1930", "1941", "1945", "1954", "C", "easy"),
    ("Nước Việt Nam Dân chủ Cộng hòa ra đời vào ngày nào?", "19/8/1945", "2/9/1945", "6/1/1946", "19/12/1946", "B", "easy"),
    ("Cuộc Tổng tuyển cử đầu tiên của nước Việt Nam độc lập diễn ra khi nào?", "6/1/1946", "2/9/1945", "19/12/1946", "1/5/1946", "A", "medium"),
    ("Lời kêu gọi Toàn quốc kháng chiến được phát đi vào thời gian nào?", "19/12/1946", "2/9/1945", "7/5/1954", "30/4/1975", "A", "medium"),
    ("Đường lối kháng chiến chống Pháp của Đảng là gì?", "Toàn dân, toàn diện, trường kỳ, tự lực cánh sinh", "Đánh nhanh thắng nhanh", "Chỉ dựa vào viện trợ quốc tế", "Phòng thủ bị động", "A", "medium"),
    ("Chiến thắng Điện Biên Phủ diễn ra vào năm nào?", "1945", "1950", "1954", "1968", "C", "easy"),
    ("Hiệp định Giơnevơ được ký kết vào năm nào?", "1945", "1954", "1973", "1975", "B", "easy"),
    ("Sau Hiệp định Giơnevơ, Việt Nam tạm thời bị chia cắt ở vĩ tuyến nào?", "Vĩ tuyến 16", "Vĩ tuyến 17", "Vĩ tuyến 18", "Vĩ tuyến 20", "B", "medium"),
    ("Đại hội III của Đảng (1960) xác định nhiệm vụ chiến lược nào?", "Xây dựng CNXH ở miền Bắc và giải phóng miền Nam", "Chỉ xây dựng CNXH ở miền Bắc", "Chỉ đấu tranh chính trị ở miền Nam", "Thống nhất bằng con đường ngoại giao", "A", "medium"),
    ("Mặt trận Dân tộc Giải phóng miền Nam Việt Nam thành lập năm nào?", "1954", "1960", "1968", "1973", "B", "medium"),
    ("Cuộc Tổng tiến công và nổi dậy Tết Mậu Thân diễn ra năm nào?", "1965", "1968", "1972", "1975", "B", "easy"),
    ("Hiệp định Paris về chấm dứt chiến tranh ở Việt Nam được ký năm nào?", "1968", "1972", "1973", "1975", "C", "easy"),
    ("Chiến dịch Hồ Chí Minh kết thúc thắng lợi vào ngày nào?", "30/4/1975", "2/9/1975", "7/5/1975", "19/5/1975", "A", "easy"),
    ("Đất nước Việt Nam thống nhất về mặt nhà nước vào năm nào?", "1975", "1976", "1980", "1986", "B", "medium"),
    ("Đại hội VI của Đảng (1986) có ý nghĩa lịch sử gì?", "Khởi xướng công cuộc đổi mới toàn diện đất nước", "Quyết định thống nhất đất nước", "Phát động kháng chiến chống Mỹ", "Thành lập Mặt trận Việt Minh", "A", "easy"),
    ("Bài học lớn được Đại hội VI rút ra là gì?", "Phải nhìn thẳng vào sự thật, đánh giá đúng sự thật, nói rõ sự thật", "Phải đẩy nhanh tốc độ tăng trưởng", "Phải mở rộng quan hệ quốc tế", "Phải tăng cường quốc phòng", "A", "medium"),
    ("Nội dung cốt lõi của đường lối đổi mới là gì?", "Đổi mới kinh tế là trọng tâm, từng bước đổi mới chính trị phù hợp", "Đổi mới chính trị trước tiên", "Đổi mới đồng loạt mọi lĩnh vực ngay lập tức", "Chỉ đổi mới trong nông nghiệp", "A", "medium"),
    ("Chính sách khoán 10 trong nông nghiệp được ban hành năm nào?", "1981", "1986", "1988", "1993", "C", "hard"),
    ("Cương lĩnh xây dựng đất nước trong thời kỳ quá độ được thông qua tại Đại hội nào?", "Đại hội VI (1986)", "Đại hội VII (1991)", "Đại hội VIII (1996)", "Đại hội IX (2001)", "B", "medium"),
    ("Việt Nam gia nhập ASEAN vào năm nào?", "1991", "1995", "1998", "2007", "B", "medium"),
    ("Việt Nam bình thường hóa quan hệ với Hoa Kỳ vào năm nào?", "1986", "1991", "1995", "2000", "C", "medium"),
    ("Việt Nam gia nhập Tổ chức Thương mại Thế giới WTO vào năm nào?", "1995", "2001", "2007", "2010", "C", "medium"),
    ("Đại hội VIII (1996) xác định nước ta chuyển sang thời kỳ nào?", "Đẩy mạnh công nghiệp hóa, hiện đại hóa", "Khôi phục kinh tế sau chiến tranh", "Cải cách ruộng đất", "Hợp tác hóa nông nghiệp", "A", "medium"),
    ("Mục tiêu tổng quát của công cuộc đổi mới là gì?", "Dân giàu, nước mạnh, dân chủ, công bằng, văn minh", "Tăng trưởng GDP cao nhất khu vực", "Xuất khẩu nhiều nhất thế giới", "Xây dựng nhiều đô thị lớn", "A", "easy"),
    ("Nguyên nhân thắng lợi cơ bản nhất của cách mạng Việt Nam là gì?", "Sự lãnh đạo đúng đắn của Đảng Cộng sản Việt Nam", "Sự giúp đỡ của bạn bè quốc tế", "Điều kiện địa lý thuận lợi", "Sự suy yếu của đối phương", "A", "easy"),
    ("Bài học kinh nghiệm hàng đầu của Đảng qua các thời kỳ là gì?", "Nắm vững ngọn cờ độc lập dân tộc và chủ nghĩa xã hội", "Tranh thủ tối đa viện trợ", "Phát triển kinh tế bằng mọi giá", "Tránh mọi xung đột", "A", "medium"),
    ("Cao trào kháng Nhật cứu nước diễn ra vào thời gian nào?", "Từ tháng 3/1945", "Từ tháng 9/1940", "Từ tháng 5/1941", "Từ tháng 8/1945", "A", "hard"),
    ("Chỉ thị Nhật - Pháp bắn nhau và hành động của chúng ta ra đời khi nào?", "12/3/1945", "9/3/1945", "13/8/1945", "2/9/1945", "A", "hard"),
    ("Đội Việt Nam Tuyên truyền Giải phóng quân thành lập ngày nào?", "22/12/1944", "19/8/1945", "7/5/1954", "15/5/1941", "A", "medium"),
    ("Phong trào dân chủ 1936 - 1939 có mục tiêu trước mắt là gì?", "Đòi tự do, dân sinh, dân chủ, cơm áo và hòa bình", "Lật đổ chính quyền thực dân ngay lập tức", "Tiến hành cải cách ruộng đất", "Thành lập nhà nước công nông", "A", "medium"),
    ("Hội nghị Trung ương tháng 11/1939 chủ trương thành lập mặt trận nào?", "Mặt trận Thống nhất dân tộc phản đế Đông Dương", "Mặt trận Việt Minh", "Mặt trận Liên Việt", "Mặt trận Tổ quốc Việt Nam", "A", "hard"),
    ("Sau Cách mạng Tháng Tám, khó khăn lớn nhất của chính quyền non trẻ là gì?", "Giặc đói, giặc dốt và giặc ngoại xâm", "Thiếu cán bộ lãnh đạo", "Không có hiến pháp", "Không được quốc tế công nhận", "A", "medium"),
    ("Hiệp định Sơ bộ được ký ngày nào?", "6/3/1946", "14/9/1946", "19/12/1946", "2/9/1945", "A", "hard"),
    ("Đại hội II của Đảng (1951) quyết định điều gì quan trọng?", "Đưa Đảng ra hoạt động công khai với tên Đảng Lao động Việt Nam", "Giải tán Đảng", "Đổi tên thành Đảng Cộng sản Đông Dương", "Sáp nhập với các đảng khác", "A", "hard"),
    ("Chiến dịch Biên giới Thu - Đông diễn ra vào năm nào?", "1947", "1950", "1952", "1954", "B", "medium"),
    ("Kế hoạch Nava của thực dân Pháp bị phá sản bởi chiến thắng nào?", "Việt Bắc 1947", "Biên giới 1950", "Điện Biên Phủ 1954", "Tây Bắc 1952", "C", "medium"),
    ("Đường Trường Sơn - đường Hồ Chí Minh bắt đầu được xây dựng năm nào?", "1954", "1959", "1965", "1968", "B", "hard"),
    ("Đại hội XIII của Đảng diễn ra vào năm nào?", "2011", "2016", "2021", "2026", "C", "easy"),
    ("Ba đột phá chiến lược được Đảng xác định gồm những nội dung nào?", "Thể chế, nguồn nhân lực và kết cấu hạ tầng", "Nông nghiệp, công nghiệp và dịch vụ", "Giáo dục, y tế và văn hóa", "Quốc phòng, an ninh và đối ngoại", "A", "medium"),
    ("Quan điểm đối ngoại hiện nay của Việt Nam là gì?", "Độc lập tự chủ, đa phương hóa, đa dạng hóa quan hệ quốc tế", "Chỉ quan hệ với các nước xã hội chủ nghĩa", "Liên minh quân sự với nước lớn", "Khép kín không hội nhập", "A", "easy"),
    ("Công tác xây dựng, chỉnh đốn Đảng hiện nay tập trung vào nhiệm vụ nào?", "Phòng chống suy thoái, tham nhũng, tiêu cực trong cán bộ đảng viên", "Tăng nhanh số lượng đảng viên", "Mở rộng bộ máy tổ chức", "Tăng ngân sách hoạt động", "A", "easy"),
]

DATA = {
    'Triết học Mác - Lênin': TRIET_HOC,
    'Kinh tế chính trị Mác - Lênin': KINH_TE_CHINH_TRI,
    'Chủ nghĩa xã hội khoa học': CNXH_KHOA_HOC,
    'Tư tưởng Hồ Chí Minh': TU_TUONG_HCM,
    'Lịch sử Đảng Cộng sản Việt Nam': LICH_SU_DANG,
}
